Add validator joining and leaving acceptance codes
vegaprotocol/specs pull request #1050
Opened 2022-04-20 09:51 UTC by gordsport

Addition of ACs and code for tests needed around the validator joining and leaving process

@ze97286 
1. Do these new ACs supersede any of the existing ACs in this spec?
1. Do we need to add ACs around Tendermint voting power or are they covered elsewhere (I was not sure from the word doc)
1. I have not included under the `Multisig score` heading as I was not sure how to capture this as an AC
- Need to test the case where one of the top network.validators.multisig.numberOfSigners validators is not registered with the multisig contract, not sure how this can be done in the test environment. 

DS: Closes #964, if we move the appropriate ones to 0064-VALP then it also closes #965.

2022-04-20 14:29 UTC, ze97286 commented
> 1. Do these new ACs supersede any of the existing ACs in this spec?

I'll need to look case by case, there is possibly some overlap. As this was not strictly written as AC but rather to highlight test scenarios I will need to review to answer this question. 

> 2. Do we need to add ACs around Tendermint voting power or are they covered elsewhere (I was not sure from the word doc)

The coverage of the spec is already good enough no need to add anything new. 

> 3. I have not included under the Multisig score heading as I was not sure how to capture this as an AC

Indeed, I don't know, but needs to be tested.

2022-04-20 15:17 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Every 1000 blocks the performance score of the new validator should go up by 0.1 as long as it’s up with a maximum of 1.
```suggestion
  * Every 1000 blocks the performance score of the new validator should go up by 0.1 until it reaches the maximum of 1. 
```

2022-04-20 15:18 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Verify that after enough epochs to represent at least 1000 blocks, the performance score of the joining validator is 0.1.
I am a bit confused by what do epochs have to do with this.

2022-04-20 15:21 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Setup a network with 5 Tendermint validators with 4 validators with self-delegation.
```suggestion
  * Setup a network with 5 Tendermint validators but with only 4 validators that have sufficient self-delegation. 
```

2022-04-20 15:22 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Verify that the joining validator would has a multisig score of 0 and therefore would not get a reward.
```suggestion
  * Verify that the joining validator has a multisig score of 0 and therefore would not get a reward. 
```

2022-04-20 15:26 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Verify that the joining validator would has a multisig score of 0 and therefore would not get a reward.
Here I think there should be two cases:
1) the new validator has so much self-delegation that it's in fact one of the top 4 and so it should be on the multisig. If that's the case (and no-one updated the multisig) then the new validator should have multisig score of 0.
2) the new validator has so little self-delegation that it's *not* one of the top 4. So it should not be on the  multisig and thus should have a multisig score of 1.

2022-04-20 15:27 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * There are no ersatz validators in the network. regardless of ersatzRewardFactor,
```suggestion
  * There are no ersatz validators in the network. 
```

2022-04-20 15:29 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Setup a network with 5 tendermint validators, set number of ersatz validators (through factor) to 0.
```suggestion
  * Setup a network with 5 tendermint validators, set number of ersatz validators (through network parameter) to 0. 
```

2022-04-20 15:34 UTC, davidsiska-vega requested changes
Awesome, left some comments, only one really matters and I probably confused myself there.

2022-04-21 07:38 UTC, ze97286 commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Verify that after enough epochs to represent at least 1000 blocks, the performance score of the joining validator is 0.1.
performance score is only published at the beginning of an epoch (in the ranking score) so if an epoch is 5s (i.e. ~5 blocks), for a validator to have performance score of 0.1 we need to move 1000/5=200 epochs.

2022-04-21 12:11 UTC, davidsiska-vega commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +### Performance score (related to [0064-VALP-validator_performance_based_rewards.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0064-VALP-validator_performance_based_rewards.
Should these be moved to 0064-VALP? Perhaps replace the ones there as I am not sure those are accurate.

2022-04-21 12:57 UTC, gordsport commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +### Performance score (related to [0064-VALP-validator_performance_based_rewards.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0064-VALP-validator_performance_based_rewards.
@ze97286 - if you are in agreement I will move these across to 0064-VALP

@davidsiska-vega - I'd need guidance on weather or not to replace all or some of what is there as I don't want to remove something thats needed.

2022-04-21 13:00 UTC, ze97286 commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +### Performance score (related to [0064-VALP-validator_performance_based_rewards.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0064-VALP-validator_performance_based_rewards.
you can move there and replace what's in there.

2022-04-21 13:56 UTC, wwestgarth commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Let the network run for 1000 blocks more and at the following epoch check that score is up to 0.2. Keep it running until it performance score of the joining validator reaches 1, then stop it.
1000 blocks is 15 mintues, it'll take hours to get the score to 1, and then hours for it to get back to zero. Its not plausible to have a system test for this without having the 1000 blocks being configurable.

2022-04-21 20:09 UTC, gordsport commented
@davidsiska-vega - moved the 0064-VALP ACs to the correct spec and renumbers the 0069-VCBS codes. Also do you have ideas/info on how we may test:
- Need to test the case where one of the top `network.validators.multisig.numberOfSigners` validators is not registered with the multisig contract, not sure how this can be done in the test environment.
If so I will get into the correct spec if it helps.

@ze97286 - there is just the two outstanding comments I would need your input on - TIA

2022-04-22 07:46 UTC, ze97286 commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Let the network run for 1000 blocks more and at the following epoch check that score is up to 0.2. Keep it running until it performance score of the joining validator reaches 1, then stop it.
I'm thinking about making this 1000 blocks a function of the epoch duration if that would make you happy @wwestgarth

2022-04-22 08:04 UTC, ze97286 commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Let the network run for 1000 blocks more and at the following epoch check that score is up to 0.2. Keep it running until it performance score of the joining validator reaches 1, then stop it.
how about every 1% of the epoch duration in blocks, so e.g. for 1d epoch, that would be 864 blocks. For 300s epoch it will be every 3 blocks - so maybe with a minimum of 50 blocks or something.

2022-04-22 08:19 UTC, ze97286 commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Verify that the joining validator would has a multisig score of 0 and therefore would not get a reward.
Agreed. Lets change it to the following:

4. Tendermint validators missing signature test 2 (<a name="0069-VCBS-013" href="#0069-VCBS-013">0069-VCBS-013</a>): 
  * Setup a network with 4 Tendermint validators with self-delegation and number of Tendermint validators net param set to 5. 
  * **Additional setup:** ensure that the network parameter network.validators.multisig.numberOfSigners is set to **4**.
  * Announce a new node and self-delegate to it 10000 tokens.
  * Allow some time for the performance score to become 1. Note: When this happens the validator will be promoted to Tendermint validator at the beginning of the following epoch. 
  * When the validator has been promoted to a Tendermint validator, transfer 1000 tokens to the reward account. 
  * The expectation is that the new validator would have a score (stake score x performance score) in the top 4 - this can be verified in data node in the rewardScore.stakeScore x rewardScore.performanceScore. 
  * Verify that the joining validator would has a multisig score of 0 and therefore would not get a reward.

5. Tendermint validators missing signature test 2 (<a name="0069-VCBS-054" href="#0069-VCBS-054">0069-VCBS-054</a>): 
  * Setup a network with 4 Tendermint validators with self-delegation and number of Tendermint validators net param set to 5. 
  * **Additional setup:** ensure that the network parameter network.validators.multisig.numberOfSigners is set to **4**.
  * Delegate 10000 to the existing validators (can be self or party delegation) 
  * Announce a new node and self-delegate to it 1000 tokens.
  * Do not wait for the performance of the node to improve, we actually want for this test the performance score to be as low as possible. 
  * When the validator has the the delegation setup it will be promoted to tendermint status. 
  * When the validator has been promoted to a Tendermint validator, transfer 1000 tokens to the reward account. 
  * The expectation is that the new validator would have a score (stake score x performance score) NOT in the top 4 - this can be verified in data node in the rewardScore.stakeScore x rewardScore.performanceScore. 
  * Verify that the joining validator would has a multisig score of 1 and therefore gets a reward.

2022-04-22 08:40 UTC, davidsiska-vega commented
> @davidsiska-vega - moved the 0064-VALP ACs to the correct spec and renumbers the 0069-VCBS codes. Also do you have ideas/info on how we may test:
> 
> * Need to test the case where one of the top `network.validators.multisig.numberOfSigners` validators is not registered with the multisig contract, not sure how this can be done in the test environment.
>   If so I will get into the correct spec if it helps.
> 
> @ze97286 - there is just the two outstanding comments I would need your input on - TIA

I am not on top of what dockerised vega does and doesn't support but hypothetically: 
- run a test ethereum network with whatever ethereum validator nodes (or just ganache) you need to make it work. 
- run a vega network in the configuration described above create a situation where a validator joins, gets a lot delegated (so it makes it into the top `network.validators.multisig.numberOfSigners` but never bothers to put its ethereum key on the multisig contract.
- check that they get `0` for their multisig score and hence no staking reward. 

I really don't see how this is harder than any of the other multisig ones but I don't know the infrastructure we've built so well. 

Anyway, the specs *are not* the place where we worry about *how exactly* something gets tested as long as it is testable (and the above is) it's a valid AC.

2022-04-22 08:50 UTC, gordsport commented
@davidsiska-vega  I have added the AC as suggested in this commit [add additional multisig AC](https://github.com/vegaprotocol/specs-internal/pull/1050/commits/ec1f0dcd10ecf22e5e6bae667bcb442fdc2f61c9)

2022-04-22 09:44 UTC, wwestgarth commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Let the network run for 1000 blocks more and at the following epoch check that score is up to 0.2. Keep it running until it performance score of the joining validator reaches 1, then stop it.
Yes it would make me happy! And maybe with the minimum being the epoch-length in blocks, so 5s epoch -> heartbeat every 5 blocks. Because 50 blocks is still 20mins of waiting to get the score to go to 1 and back down.

2022-04-22 13:56 UTC, gordsport commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +  * Let the network run for 1000 blocks more and at the following epoch check that score is up to 0.2. Keep it running until it performance score of the joining validator reaches 1, then stop it.
@wwestgarth @ze97286 
[This commit](https://github.com/vegaprotocol/specs-internal/pull/1050/commits/14c7972174ad37abd3f83b7db9afd84e59e9ec8f) updates `0064-VALP-004` to address this - please do review and feedback.

This is the last currently open comment before we can ✅ and merge (cc @davidsiska-vega )

2022-04-22 20:00 UTC, gordsport commented on protocol/0069-VCBS-validators_chosen_by_stake.md
> +### Performance score (related to [0064-VALP-validator_performance_based_rewards.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0064-VALP-validator_performance_based_rewards.
done

2022-04-25 08:41 UTC, davidsiska-vega approved these changes

2022-04-25 08:42 UTC, merged