Add details on oracle spec referring internal oracles
vegaprotocol/specs pull request #1051
Opened 2022-04-20 10:22 UTC by ValentinTrinque

This has been implemented but not documented.

2022-06-15 10:16 UTC, barnabee requested changes
Need to update this still. I will do this.

2022-06-15 10:16 UTC, barnabee commented on protocol/0048-DSRI-data_source_internal.md
> +Today, only the time-triggered one is implemented through the property name `vegaprotocol.builtin.timestamp`.
We need to addjust this text, this is not a time trigger so much as a built in timestamp data source. We should give it a separate section for built in data sources is it behaves functionally differently. I can do this update.

2022-08-17 10:15 UTC, barnabee submitted a review, later dismissed
> We need to addjust this text, this is not a time trigger so much as a built in timestamp data source. We should give it a separate section for built in data sources is it behaves functionally differently. I can do this update. 

I've made these updates, please rereview

2022-08-17 10:21 UTC, AnExsomnis submitted a review, later dismissed

2022-08-17 11:09 UTC, AnExsomnis approved these changes

2022-08-17 11:11 UTC, merged