chore: Invalidate data sourcing ACs for Oregon Trail
vegaprotocol/specs pull request #1057
Opened 2022-04-21 11:17 UTC by gordsport

In order to accurately measure the AC coverage for Oregon Trail this PR invalidates the AC codes that have not been implemented for 
- [0045-DSRC](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0045-DSRC-data_sourcing.md)
- [0046-DSRM](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0046-DSRM-data_source_signed_message.md)

These codes now have the format nnnn-COSMICELEVATOR-nnn so that we can see then and implement for the next milestone if/as required.

2022-04-21 12:25 UTC, barnabee submitted a review, later dismissed
@gordsport Where did the decision that these were not in scope for the milestone come from, given that data sourcing is definitely in scope?

The data sourcing specs were delivered quite some time ago and I was under the impression that data sourcing was delivered. A good number of these are either required for trading to launch or in need of a significant discussion involving people outside engineering if they are to be descoped because not having them could have serious potential impacts on users and may make the creation of markets (which is already a big commitment/risk for early users) very difficult.

The starting position is that all requirements in these data sourcing specs, unless explicitly labelled otherwise, and therefore all of the ACs related to them are requirements for Oregon Trail. We can absolutely have a session to talk through the gaps and work out how much we can leave out, if it really hasn't been built, but we can't merge this PR until that has happened.

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. When no reference to a data source remains in any active part of the system (for instance a non-cancelled/settled market), data source no longer needs to be tracked and can be discarded. Any trans
Why is this excluded? We need to remove data sources once the market is settled.

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. Two data sources with the same definition that are active at the same time must always select and receive exactly the same data, in the same order. (<a name="0045-COSMICELEVATOR-010" href="#0045-C
I still don't understand the justification for why we can't test/prove this. 

Given:
- data source definition D (i.e. D includes the public key, filters, selection of field to use, etc.)
- two markets A and B, both with D as the data source say for settlement

If data source D sends valid messages M1 followd by M2, then:
- both markets A and B process M1 before M2
- both markets A and B process M1 in the same block and sequence (i.e. no other transactions from that block or other blocks are processed between the two markets processing the message M1)
- the settlement price used for both markets is the same

I would be quite worried if we can't prove this.

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever p
Are we really planning to launch trading without a way for someone to know why their transaction is rejected? If so this needs to discussed more widely than just engineering, as that might need to change. These are requirements for a reason.

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to listen to events or view logs and see all rejections and data source processing. (<a name="0045-COSMICELEVATOR-013" href="#0045-COSMICELEVATOR-013">0045-COSMICELEVATOR-013</a>)
Same comment as `-011`

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to listen to events and see all data that is supplied across all data sources or for any specific source. (<a name="0045-COSMICELEVATOR-014" href="#0045-COSMICELEVATOR-014">0045-COSM
Can someone please explain why we cannot emit this event or cannot test it?

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data node carries historic data of at least all valid data that was supplied for each data source. (<a name="0045-COSMICELEVATOR-015" href="#0045-COSMICELEVATOR-015">0045-COSMICELEVATOR-015</a>)
Would like to understand how hard this is to do (it ought to be fairly simple if the event discussed in `-015` is emitted) and whether we can include this. Again we need to discuss if we are descoping these things.

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data sources can be composed/nested arbitrarily (as long as the definition is valid), for example selecting a field on filtered data that itself was sourced by selecting a field on a message sent
Please can we have a write up of the capabilities and limits of the data sourcing functionality. These requirements are not new or recent and noone has raised a spec bug to discuss descopsiing them so we are expecting the features.

2022-04-21 12:25 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. A market proposal specifies data source where value used for settlement is integer with implied decimals; the implied decimals are included in the oracle spec; once trading terminated and settleme
Unless I am missing something, supporthing this is basically essential for trading to launch. Why is it descoped / what am I missing here?

2022-04-21 12:25 UTC, barnabee commented on protocol/0046-DSRM-data_source_signed_message.md
> +    1. `SubmitData` transactions for active ([see data sourcing framework](./0045-DSRC-data_sourcing.md)) data sources will be accepted regardless of the transaction signer.  (<a name="0046-COSMICELE
This is required for launch of trading. We need to be able to have ANY user submit data signed by Coinbase oracle and verify the Coinbase signature, not that some random user signed the submission.

2022-04-21 12:25 UTC, barnabee commented on protocol/0046-DSRM-data_source_signed_message.md
> +    - For a pubkey never used in a data source  (<a name="0046-COSMICELEVATOR-013" href="#0046-COSMICELEVATOR-013">0046-COSMICELEVATOR-013</a>)
What do we do in this case if we don't reject the data?

2022-04-21 12:25 UTC, barnabee commented on protocol/0046-DSRM-data_source_signed_message.md
> +1. Reject any SubmitData tx that is a duplicate (i.e. contains exactly the same data payload and is for the same data source), even if it is signed by a different signer (assuming the source has mult
This is ok

2022-04-22 09:09 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. When no reference to a data source remains in any active part of the system (for instance a non-cancelled/settled market), data source no longer needs to be tracked and can be discarded. Any trans
Confirmed with Jeremy this is implemented and can be tested - I will revert this change

2022-04-22 09:09 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Two data sources with the same definition that are active at the same time must always select and receive exactly the same data, in the same order. (<a name="0045-COSMICELEVATOR-010" href="#0045-C
Confirmed with Jeremy this is implemented and can be tested - I will revert this change

2022-04-22 09:13 UTC, jeremyletang commented on protocol/0045-DSRC-data_sourcing.md
> +1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever p
If a transaction is incorrect (invalid signature, invalid payload, spam, etc) then yes there's a rejection error either through returned by the mempool now that tendermint is fixed or via the TxErrEvent from the bus.

If the transaction satisfy no filters, then it's simply ignored and yes you don't have an error message, this can eventually be changed somehow I suppose (we even might have APIs for this already but I'd have to check again).

2022-04-22 09:16 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. A market proposal specifies data source where value used for settlement is integer with implied decimals; the implied decimals are included in the oracle spec; once trading terminated and settleme
Confirmed with Jeremy this is implemented and can be tested - I will revert this change

2022-04-22 09:17 UTC, gordsport commented on protocol/0046-DSRM-data_source_signed_message.md
> +    1. `SubmitData` transactions for active ([see data sourcing framework](./0045-DSRC-data_sourcing.md)) data sources will be accepted regardless of the transaction signer.  (<a name="0046-COSMICELE
Confirmed with Jeremy this is implemented and can be tested - I will revert this change

2022-04-22 09:18 UTC, jeremyletang commented on protocol/0046-DSRM-data_source_signed_message.md
> +    - For a pubkey never used in a data source  (<a name="0046-COSMICELEVATOR-013" href="#0046-COSMICELEVATOR-013">0046-COSMICELEVATOR-013</a>)
This needs to be reverted as well, a data source with which is not explicitly required is just plain ignored as it means it doesn't satisfy any filters.

2022-05-19 08:39 UTC, gordsport commented
After the final review of the [questions spreadsheet](https://docs.google.com/spreadsheets/d/1M7KeqlsU4908tWjHqxPaK_VxGu9n_vxtpzUzhgJjASQ/edit#gid=0)

### Marked as COSMICELEVATOR:
[0045-DSRC-data_sourcing.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0045-DSRC-data_sourcing.md)
- 0045-COSMICELEVATOR-002 (Settlement is covered by DSRM-015 - closing markets will come in a later milestone)
- 0045-COSMICELEVATOR-010 (this is not testable by blockchain design - should this be removed?)
- 0045-COSMICELEVATOR-016 (needs nested filtering which will come ion a later milestone)

[0048-DSRI-data_source_internal.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0048-DSRI-data_source_internal.md)
- 0048-COSMICELEVATOR-001 (the value oracle is not implemented yet)
- 0048-COSMICELEVATOR-002 (the value oracle is not implemented yet)
- 0048-COSMICELEVATOR-003 (Time triggered settlement is not an option currently. Applies only for trading termination)
- 0048-COSMICELEVATOR-004 (Time triggered settlement is not an option currently. Applies only for trading termination)
- 0048-COSMICELEVATOR-008 (Time triggered settlement is not an option currently. Applies only for trading termination)
- 0048-COSMICELEVATOR-009 (Time triggered settlement is not an option currently. Applies only for trading termination)

[0047-DSRF-data_source_filter.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0047-DSRF-data_source_filter.md)
- 0047-COSMICELEVATOR-003 (requires nested filtering that will be implemented in a later milestone)
- 0047-COSMICELEVATOR-004 (requires nested filtering that will be implemented in a later milestone)

### Testable but required work on the core side:

[0045-DSRC-data_sourcing.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0045-DSRC-data_sourcing.md)
- 0045-DSRC-011 - will require API/subscription adding to be able to test (ticket TBC)
- 0045-DSRC-013 - will require API/subscription adding to be able to test (ticket TBC)
- 0045-DSRC-013 - will require API/subscription adding to be able to test (ticket TBC)
- 0045-DSRC-015 - this requires the data retention work to be done relating to [Datanode AC](https://github.com/vegaprotocol/specs-internal/pull/1081/files)

[0047-DSRF-data_source_filter.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0047-DSRF-data_source_filter.md)
- 0047-DSRF-007 - will require API/subscription adding to be able to test (ticket TBC)
- 0047-DSRF-010 - will require API/subscription adding to be able to test (ticket TBC)


### All testable

[0046-DSRM-data_source_signed_message.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0046-DSRM-data_source_signed_message.md)
- All ACs testable in Oregon Trail

2022-05-19 10:18 UTC, barnabee commented
> 0045-COSMICELEVATOR-002 (Settlement is covered by DSRM-015 - closing markets will come in a later milestone)

I think these are _close_ to duplicate tests except that one is saying that in that situation the data source doesn't need to be tracked (assume this means it would no longer exist in core APIs, only data node) and the other is saying that for the specific signed message type of data source, the signed message should be rejected.

It is _not a distinction of closed vs settled_. From the perspective of both requirements, closed/rejected/settled/etc. are all the same and should behave the same way for both.

2022-05-19 10:19 UTC, barnabee commented
> 045-COSMICELEVATOR-010 (this is not testable by blockchain design - should this be removed?)

I guess so, if it is really untestable

2022-05-19 10:20 UTC, barnabee commented
> 0045-COSMICELEVATOR-016 (needs nested filtering which will come ion a later milestone)

I am not sure nested filtering is a good name for this. But agree we can descope this functionality from Oregon Trail and it is not going to exist until later.

2022-05-19 10:43 UTC, barnabee commented
>     0048-COSMICELEVATOR-001 (the value oracle is not implemented yet)
>     0048-COSMICELEVATOR-002 (the value oracle is not implemented yet)
>     0048-COSMICELEVATOR-003 (Time triggered settlement is not an option currently. Applies only for trading termination)
>     0048-COSMICELEVATOR-004 (Time triggered settlement is not an option currently. Applies only for trading termination)
>     0048-COSMICELEVATOR-008 (Time triggered settlement is not an option currently. Applies only for trading termination)
>     0048-COSMICELEVATOR-009 (Time triggered settlement is not an option currently. Applies only for trading termination)

I expected these to be in scope (see previous [question about scope](https://github.com/vegaprotocol/specs-internal/pull/1057#pullrequestreview-948512039) in this thread). Is there any documented decsision to descope them or are they simply something we didn't build?

2022-05-19 11:55 UTC, gordsport commented
> > ```
> > 0048-COSMICELEVATOR-001 (the value oracle is not implemented yet)
> > 0048-COSMICELEVATOR-002 (the value oracle is not implemented yet)
> > 0048-COSMICELEVATOR-003 (Time triggered settlement is not an option currently. Applies only for trading termination)
> > 0048-COSMICELEVATOR-004 (Time triggered settlement is not an option currently. Applies only for trading termination)
> > 0048-COSMICELEVATOR-008 (Time triggered settlement is not an option currently. Applies only for trading termination)
> > 0048-COSMICELEVATOR-009 (Time triggered settlement is not an option currently. Applies only for trading termination)
> > ```
> 
> I expected these to be in scope (see previous [question about scope](https://github.com/vegaprotocol/specs-internal/pull/1057#pullrequestreview-948512039) in this thread). Is there any documented decision to descope them or are they simply something we didn't build?

@RomanLeca / @ValentinTrinque - can you please update on this. I am not aware of any decision to have not implemented this, however it may have pre-dated me.

2022-06-01 11:55 UTC, davidsiska-vega commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to query an API and see all rejections and data source processing. (<a name="0045-DSRC-013" href="#0045-DSRC-013">0045-DSRC-013</a>)
```suggestion
1. Party submitting an oracle transaction that gets rejected (e.g. because no data source is listening for transactions from such key) can receive an error message detailing reason for rejection. (<a name="0045-DSRC-013" href="#0045-DSRC-013">0045-DSRC-013</a>)
```

2022-06-01 11:58 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever p
reverted changes as will be covered before enable trading is voted in

2022-06-01 11:59 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to listen to events or view logs and see all rejections and data source processing. (<a name="0045-COSMICELEVATOR-013" href="#0045-COSMICELEVATOR-013">0045-COSMICELEVATOR-013</a>)
reverted changes as will be covered before enable trading is voted in

2022-06-01 11:59 UTC, davidsiska-vega reviewed
I've looked and it looks correct to me but would be good to get @barnabee to approve this.

2022-06-01 11:59 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data sources can be composed/nested arbitrarily (as long as the definition is valid), for example selecting a field on filtered data that itself was sourced by selecting a field on a message sent
reverted changes as will be covered before enable trading is voted in

2022-06-01 12:00 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to listen to events and see all data that is supplied across all data sources or for any specific source. (<a name="0045-COSMICELEVATOR-014" href="#0045-COSMICELEVATOR-014">0045-COSM
reverted changes as will be covered before enable trading is voted in

2022-06-01 12:01 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data node carries historic data of at least all valid data that was supplied for each data source. (<a name="0045-COSMICELEVATOR-015" href="#0045-COSMICELEVATOR-015">0045-COSMICELEVATOR-015</a>)
reverted changes as will be covered before enable trading is voted in

2022-06-01 14:39 UTC, barnabee requested changes
Some changes

2022-06-01 14:39 UTC, barnabee commented on protocol/0045-DSRC-data_sourcing.md
> +1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever p
We can change “must be accompanied by a message” to something like “must either result in an event queue message, return an error to the client, or enable the rejection (or not) to be confirmed by querying a core API” but I think it remains a requirement that you can always tell what happened, both when the message was rejected pre-consensus and when it was sequenced in a block but not used anywhere etc.

2022-06-01 14:39 UTC, barnabee commented on protocol/0046-DSRM-data_source_signed_message.md
> +1. Data sources are accepted that conform to the Open Oracle specification (<a name="0046-COSMICELEVATOR-017" href="#0046-COSMICELEVATOR-017">0046-COSMICELEVATOR-017</a>)
Technically it is the message containing the data and the signature that need to conform, may be worth noting that, and that we do not support (or need to) direct connections to REST APIs, Ethereum smart contracts, etc. conforming to the open oracle spec. as part of these requirements.

2022-06-01 14:39 UTC, barnabee commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Create a filter with multiple (AND) conditions and ensure that data is only passed through if all conditions are met. (<a name="0047-COSMICELEVATOR-003" href="#0047-COSMICELEVATOR-003">0047-COSMI
“AND” is the default and is supported, this is not out of scope

2022-06-01 14:39 UTC, barnabee commented on protocol/0048-DSRI-data_source_internal.md
>  	1. Create a cash settled futures market with the trading terminated trigger source being a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
This cannot be tested, should be deferred to Cosmic Elevator. We have no time triggers or value data sources.

For Oregon Trail we need ACs for a trading terminated trigger that uses the internal block timestamp data source and filters it >= some time, to test that the market settles at the first block with a timestamp on or after that time.

2022-06-01 14:39 UTC, barnabee commented on protocol/0048-DSRI-data_source_internal.md
>  	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
As [above](https://github.com/vegaprotocol/specs-internal/pull/1057#discussion_r886888075)

2022-06-01 14:39 UTC, barnabee commented on protocol/0048-DSRI-data_source_internal.md
>  	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
As [above](https://github.com/vegaprotocol/specs-internal/pull/1057#discussion_r886888075) but the filter needs to be for a time in the past

2022-06-01 15:13 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
>  	1. Create a cash settled futures market with the trading terminated trigger source being a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
new AC added as 0048-DSRI-009 in [commit](https://github.com/vegaprotocol/specs-internal/pull/1057/commits/3fa23fc0352bda2b3b246a4385a7ccf8111e1666)

2022-06-01 15:14 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
>  	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
new AC added as 0048-DSRI-010 in [commit](https://github.com/vegaprotocol/specs-internal/pull/1057/commits/3fa23fc0352bda2b3b246a4385a7ccf8111e1666)

2022-06-01 15:14 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
>  	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
new AC added as 0048-DSRI-011 in [commit](https://github.com/vegaprotocol/specs-internal/pull/1057/commits/3fa23fc0352bda2b3b246a4385a7ccf8111e1666)

2022-06-01 15:14 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever p
corrected in [commit](https://github.com/vegaprotocol/specs-internal/pull/1057/commits/3fa23fc0352bda2b3b246a4385a7ccf8111e1666)

2022-06-01 15:14 UTC, gordsport commented on protocol/0046-DSRM-data_source_signed_message.md
> +1. Data sources are accepted that conform to the Open Oracle specification (<a name="0046-COSMICELEVATOR-017" href="#0046-COSMICELEVATOR-017">0046-COSMICELEVATOR-017</a>)
corrected in [commit](https://github.com/vegaprotocol/specs-internal/pull/1057/commits/3fa23fc0352bda2b3b246a4385a7ccf8111e1666)

2022-06-01 15:14 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Create a filter with multiple (AND) conditions and ensure that data is only passed through if all conditions are met. (<a name="0047-COSMICELEVATOR-003" href="#0047-COSMICELEVATOR-003">0047-COSMI
corrected in [commit](https://github.com/vegaprotocol/specs-internal/pull/1057/commits/3fa23fc0352bda2b3b246a4385a7ccf8111e1666)

2022-06-08 10:04 UTC, davidsiska-vega submitted a review, later dismissed

2022-06-08 13:57 UTC, barnabee requested changes
One condition that is Oregon Trail appears to be miscategorised as Cosmic Elevator, otherwise all seem good now

2022-06-08 13:57 UTC, barnabee commented on protocol/0046-DSRM-data_source_signed_message.md
> +1. Messages are accepted that contain the data and the signature (conforming to the Open Oracle specification) Note: do not support (or need to) direct connections to REST APIs, Ethereum smart contra
This is Oregon Trail

2022-06-08 13:57 UTC, gordsport commented on protocol/0046-DSRM-data_source_signed_message.md
> +1. Messages are accepted that contain the data and the signature (conforming to the Open Oracle specification) Note: do not support (or need to) direct connections to REST APIs, Ethereum smart contra
corrected

2022-06-08 14:00 UTC, barnabee approved these changes

2022-06-08 14:00 UTC, merged