Add ACs for network parameters in 0059-STKG-simple_staking_and_delega…
vegaprotocol/specs pull request #1060
Opened 2022-04-22 12:38 UTC by Jiajia-Cui

…ting

close with #1030 
close with #1031

2022-04-25 19:17 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.minValidators` will change the minimum number of validators in a new delegation. (Default value 5. Valid values are integers greater than or eq
This value also affects the stakescore, so it needs to be tested that the next reward as well as the next tendermint weight is computed correctly (the name is a bit unfortunate now, as we settled for a fixed number of validators, so this really is only affecting the validator score.
For the range check, it should be verified that this value is not bigger than the actual number of validators.

2022-04-25 19:17 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.minValidators` will change the minimum number of validators in a new delegation. (Default value 5. Valid values are integers greater than or eq
This value also affects the stakescore, so it needs to be tested that the next reward as well as the next tendermint weight is computed correctly (the name is a bit unfortunate now, as we settled for a fixed number of validators, so this really is only affecting the validator score.
For the range check, it should be verified that this value is not bigger than the actual number of validators.

2022-04-25 19:17 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +
Is there a specification on what happens if that value is increased and thus existing validators do no longer meet the criteria, i.e., if there's a grace period in which the delegators can acquire the new stake before their rewards are scrapped ? According to spec (0069), all validators that have less than reward.staking.minimumValidatorStake will be removed, though it's not specified how at this point - we want to avoid that too many validators disappear at the same time.

In either case we need ACs of the form "

- If the value is changed so that one or more validators do not have sufficient own stake anymore, they are removed (according to the removal policy). Also (this is an issue in 0069, but I add this here for now) it is not defined if an Ersatzvalidator needs to have sufficient ownstake.

- if the value is changed so that a validator that obtains sufficient own stake through the parameter change (and did not have it before) qualifies to become a validator/ersatzvalidator, they are promoted accordingly in the next epoch.

2022-04-25 19:17 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +
Is there a specification on what happens if that value is increased and thus existing validators do no longer meet the criteria, i.e., if there's a grace period in which the delegators can acquire the new stake before their rewards are scrapped ? According to spec (0069), all validators that have less than reward.staking.minimumValidatorStake will be removed, though it's not specified how at this point - we want to avoid that too many validators disappear at the same time.

In either case we need ACs of the form "

- If the value is changed so that one or more validators do not have sufficient own stake anymore, they are removed (according to the removal policy). Also (this is an issue in 0069, but I add this here for now) it is not defined if an Ersatzvalidator needs to have sufficient ownstake.

- if the value is changed so that a validator that obtains sufficient own stake through the parameter change (and did not have it before) qualifies to become a validator/ersatzvalidator, they are promoted accordingly in the next epoch.

2022-04-26 10:54 UTC, Jiajia-Cui commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +
maybe we can put a cap on how much reward.staking.delegation.minimumValidatorStake can be reduced?

2022-06-10 08:53 UTC, davidsiska-vega requested changes

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `validators.delegation.minAmount` will change the smallest fraction of the governance token that can be delegated to a validator at the beginning of the next epoch; deleg
This one doesn't say what should happen to those who have current delegation that falls below a new, lower, minimum.

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.delegatorShare` will change the fraction of a validator’s rewards is distributed between its delegators in a new delegation and at the end of a
Yes, but does impact immediately the epoch in which it's approved (as I think it should), or the next one.

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.minValidators` will change the minimum number of validators in a new delegation. (Default value 5. Valid values are integers greater than or eq
This makes no sense; this parameter impacts how the validator score is calculated. The only question is as above: does impact immediately the epoch in which it's approved (as I think it should), or the next one.

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- For the range check, it should be verified that this value is not bigger than the actual number of validators. (<a name="0059-STKG-034" href="#0059-STKG-034">0059-STKG-034</a>)
I'm not sure why there should be the range check - it's just a constant that goes into a formula for rewards - maybe governance wants to change it in anticipation of more validators joining or whatever.

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.maxPayoutPerParticipant` will change the maximum amount that can be distributed to a single participant from the reward pool at the end of a ne
I don't think there is `maxPayoutPerParticipant` anymore. 

Update: it got removed from the spec but shouldn't have been. PR correcting this: https://github.com/vegaprotocol/specs-internal/pull/1109

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +If the value is changed so that one or more validators do not have sufficient own stake anymore, they are removed (according to the removal policy). Also (this is an issue in 0069, but I add this her
Yes, ersatz validators need to meet the minimum stake requirement. Please add it to 0069 to clarify as part of this PR.

2022-06-10 08:53 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +If the value is changed so that one or more validators do not have sufficient own stake anymore, they are removed (according to the removal policy). Also (this is an issue in 0069, but I add this her
I'd suggest we clarify that "they are removed (according to the removal policy)" means one per epoch, starting with the one with lowest own stake.

2022-06-10 09:42 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `validators.delegation.minAmount` will change the smallest fraction of the governance token that can be delegated to a validator at the beginning of the next epoch; deleg
I'd say the best way is to not touch them, and apply this rule only to future delegations, or does anyone see an issue with that ?

2022-06-21 08:53 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.minValidators` will change the minimum number of validators in a new delegation. (Default value 5. Valid values are integers greater than or eq
Min Validators is a parameter used in the anti-whaling, and thus should also enter somewhere in the tender mint weight calculation. I'll check that.

2022-06-21 09:11 UTC, Jiajia-Cui commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +If the value is changed so that one or more validators do not have sufficient own stake anymore, they are removed (according to the removal policy). Also (this is an issue in 0069, but I add this her
```suggestion
If the value is changed so that one or more validators do not have sufficient own stake anymore, they are removed (according to the removal policy as defined in 0069) one per epoch, starting with the one with lowest own stake.

2022-06-21 09:12 UTC, Jiajia-Cui commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- For the range check, it should be verified that this value is not bigger than the actual number of validators. (<a name="0059-STKG-034" href="#0059-STKG-034">0059-STKG-034</a>)
```suggestion

```

2022-06-21 09:30 UTC, Jiajia-Cui commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `validators.delegation.minAmount` will change the smallest fraction of the governance token that can be delegated to a validator at the beginning of the next epoch; deleg
```suggestion
- Change of network paramter `validators.delegation.minAmount` will change the smallest fraction of the governance token that can be delegated to a validator at the beginning of the next epoch; we only apply the change to new delegations. 
New delegations with tokens less than this parameter will fail the verification at the beginning (when the command is issued and before it is put on the chain). Old delegations will not be impacted by this change of parameter. 
(<a name="0059-STKG-031" href="#0059-STKG-031">0059-STKG-031</a>)
```

2022-06-21 09:35 UTC, Jiajia-Cui commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.delegatorShare` will change the fraction of a validator’s rewards is distributed between its delegators in a new delegation and at the end of a
```suggestion
- Change of network paramter `reward.staking.delegation.delegatorShare` will change the fraction of a validator’s rewards is distributed between its delegators in a new delegation and at the end of an epoch (Default value 0.883. Valid range is between 0 and 1 inclusive). The change will impact immediately the epoch in which it's approved.(<a name="0059-STKG-033" href="#0059-STKG-033">0059-STKG-033</a>)
```

2022-06-21 18:21 UTC, Vegaklaus commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +- Change of network paramter `reward.staking.delegation.minValidators` will change the minimum number of validators in a new delegation. (Default value 5. Valid values are integers greater than or eq
Can you elaborate why it makes no sense ?

2022-06-22 17:09 UTC, gordsport commented
Closing as covered in a PR for post enable trading

2022-06-22 17:09 UTC, closed without merging