feat: add ACs for keeping data in sync
vegaprotocol/specs pull request #1081
Opened 2022-04-29 12:16 UTC by gordsport

Adding ACs to cover key requirements of datanodes keeping historical data after restarts, upgrades and joining the network (latter currently being targeted for  ☄️)

2022-04-29 13:30 UTC, davidsiska-vega requested changes

2022-04-29 13:30 UTC, davidsiska-vega commented on non-protocol-specs/0011-NP-DANO-data-node.md
> +1. To ensure no loss of historical data access; data nodes must be able to have access to and syncronise all historical data after a restart (<a name="0011-NP-DANO-001" href="#0011-NP-DANO-001">0011-
Should we say something like "from Genesis block"? We won't store date across LNL restarts.

2022-04-29 13:31 UTC, davidsiska-vega commented
They are a good set of ACs btw.

2022-04-29 15:41 UTC, gordsport commented on non-protocol-specs/0011-NP-DANO-data-node.md
> +1. To ensure no loss of historical data access; data nodes must be able to have access to and syncronise all historical data after a restart (<a name="0011-NP-DANO-001" href="#0011-NP-DANO-001">0011-
Updated to say from Genesis block in [a318ada](https://github.com/vegaprotocol/specs-internal/pull/1081/commits/a318ada6d9fee5e486bc6f053b7e1c1249692877)

Should this need further editing please suggest @pscott31 @jeremyletang

2022-05-18 10:04 UTC, gordsport commented on non-protocol-specs/0011-NP-DANO-data-node.md
> +1. To ensure no loss of historical data access; data nodes must be able to have access to and synchronise all historical data after a restart (<a name="0011-NP-DANO-001" href="#0011-NP-DANO-001">0011
```suggestion
1. To ensure no loss of historical data access; data nodes must be able to have access to and synchronise all historical data since genesis block or LNL restart (<a name="0011-NP-DANO-001" href="#0011-NP-DANO-001">0011-NP-DANO-001</a>)
```

2022-05-18 10:05 UTC, gordsport commented on non-protocol-specs/0011-NP-DANO-data-node.md
> +1. To ensure no loss of historical data access; data nodes must be able to have access to and synchronise all historical data after a software upgrade  (<a name="0011-NP-DANO-002" href="#0011-NP-DANO
remove this AC

2022-05-18 11:40 UTC, gordsport commented
Hi @davidsiska-vega,
This has now been updated as per the discussion in the protocol-design meeting - if OK please ✅ and I will merge. Thanks.

2022-05-25 10:02 UTC, davidsiska-vega approved these changes

2022-05-25 10:02 UTC, merged