fix: spec 0042, delayed LP fee
vegaprotocol/specs pull request #1095
Opened 2022-05-27 16:07 UTC by Jiajia-Cui

2022-05-30 11:35 UTC, davidsiska-vega requested changes
I think we should go with the design that the delayed LP fees go into a per LP per market account and are paid out from there. 

It's no harder or easier than tracking a minimum (or average or another statistic) and it's cleaner. 

If rounding means that very small stakes don't get anything I view this as a feature not a bug (avoids having lots of tiny LPs).

2022-05-31 08:59 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +LPs with very small satkes will not get anything from rounding.
```suggestion
```

2022-05-31 10:41 UTC, Jiajia-Cui commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +LPs with very small satkes will not get anything from rounding.
resolved by updating Distribution chapter

2022-05-31 10:54 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +Once there is a trade happens, liquidity fee should be collected immediately into an account for each liquidity provider (we call it LP account) according to their share of that fee; therefore any LP
```suggestion
Once there is a trade happens, liquidity fee should be collected immediately into an account for each liquidity provider (call it LP fee account). Each party will have an LP fee account on every market on which they committed liquidity by providing LP stake. 
```

2022-05-31 10:55 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +Once there is a trade happens, liquidity fee should be collected immediately into an account for each liquidity provider (call it LP fee account). Each party will have an LP fee account on every mark
```suggestion
On every trade, liquidity fee should be collected immediately into an account for each liquidity provider (call it LP fee account). Each party will have an LP fee account on every market on which they committed liquidity by providing LP stake. 
```

2022-05-31 10:55 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +This account is not accessible by liquidity providers until the fee is distributed to them according to the below mechanism.
```suggestion
This account is not accessible by liquidity providers until the fee is distributed to them according to the mechanism below.
```

2022-05-31 11:10 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +We will create a new network parameter (which can be 0 in which case fees are transferred at the end of next block) called `market.liquidity.providers.fee.distributionTimeStep` which will define how
```suggestion
A network parameter `market.liquidity.providers.fee.distributionTimeStep` will control how often fees are distributed from the LP fee account. Starting with the end of the opening auction the clock starts ticking and then rings every time `market.liquidity.providers.fee.distributionTimeStep` has passed. Every time this happens the fees are transferred to the liquidity provider's general account for the relevant asset. If `market.liquidity.providers.fee.distributionTimeStep` is set to `0` then the fees are distributed either immediately upon collection or at then end of a block. 
```

2022-05-31 11:12 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +Trade happened, and the fee bucket contains `103.5 ETH`. Liquidity fee should be collected immediately into the following LP account:
```suggestion
Trade happened, and the trade value for fee purposes multiplied by the liquidity fee factor is `103.5 ETH`. The following amounts be collected immediately into the LP fee accounts for the market:
```

2022-05-31 11:13 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +A network parameter `market.liquidity.providers.fee.distributionTimeStep` will control how often fees are distributed from the LP fee account. Starting with the end of the opening auction the clock s
```suggestion
A network parameter `market.liquidity.providers.fee.distributionTimeStep` will control how often fees are distributed from the LP fee account. Starting with the end of the opening auction the clock starts ticking and then rings every time `market.liquidity.providers.fee.distributionTimeStep` has passed. Every time this happens the fees are transferred to the liquidity provider's margin account for the market. If `market.liquidity.providers.fee.distributionTimeStep` is set to `0` then the fees are distributed either immediately upon collection or at then end of a block. 
```

2022-05-31 11:15 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +- [ ] If a market has `market.liquidity.providers.fee.distributionTimeStep` set to more than `0` and such market settles then the fees are distributed as part of the settlement process, see [market l
```suggestion
- [ ] If a market has `market.liquidity.providers.fee.distributionTimeStep` set to more than `0` and such market settles then the fees are distributed as part of the settlement process, see [market lifecycle](./0043-MKTL-market_lifecycle.md). Any settled market has zero balances in all the LP fee accounts. (<a name="0042-LIQF-014" href="#0042-LIQF-014">0042-LIQF-014</a>)
```

2022-05-31 19:36 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +This account is not accessible by liquidity providers until the fee is distributed to them according to the mechanism below.
```suggestion
This account is not under control of the LP party (they cannot initiate transfers in or out of the account). The account is under control of the network and funds from this account will be transferred to the owning LP party according to the mechanism below.
```

2022-05-31 19:38 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +A network parameter `market.liquidity.providers.fee.distributionTimeStep` will control how often fees are distributed from the LP fee account. Starting with the end of the opening auction the clock s
```suggestion
A network parameter `market.liquidity.providers.fee.distributionTimeStep` will control how often fees are distributed from the LP fee account. Starting with the end of the opening auction the clock starts ticking and then rings every time `market.liquidity.providers.fee.distributionTimeStep` has passed. Every time this happens the balance in this account is transferred to the liquidity provider's margin account for the market. If `market.liquidity.providers.fee.distributionTimeStep` is set to `0` then the balance is distributed either immediately upon collection or at then end of a block. 
```

2022-05-31 19:39 UTC, davidsiska-vega approved these changes

2022-05-31 19:39 UTC, merged