Update ACs in 0007 to include multiple markets
vegaprotocol/specs pull request #1306
Opened 2022-10-06 10:16 UTC by Jiajia-Cui

[#1296](https://github.com/vegaprotocol/specs/issues/1296)

2022-10-06 10:33 UTC, davidsiska-vega requested changes
I suggest you leave the original ones untouched and add the new ones separately with new codes.

2022-10-06 12:03 UTC, TomMcL commented on protocol/0007-POSN-non_core_positions_api.md
> +- [ ] when a party does not have any postion, the realised PnL and unrealised PnL should be 0 (<a name="0007-POSN-009" href="#0007-POSN-009">0007-POSN-009</a>)
Should this be "has never had a position"? Because a trader with a 0 position *now* could have had one in the past and so have non-0 realised PnL

2022-10-06 12:03 UTC, TomMcL commented on protocol/0007-POSN-non_core_positions_api.md
> +- [ ] when a party has a non-zero postion, and no closeout position, the unrealised PnL should be only impacted by change of position or change of mark price while realised PnL should not be updated
Should this be "Only the unrealised PnL should be change by.." rather than "the unrealised PnL should be only changed by..." ?

2022-10-06 12:03 UTC, TomMcL commented on protocol/0007-POSN-non_core_positions_api.md
> +- [ ] During settlement, unrealised PnL and realised PnL should be unchanged (<a name="0007-POSN-012" href="#0007-POSN-012">0007-POSN-012</a>)
Surely unrealised should become 0 and realised should update?

2022-10-07 17:58 UTC, TomMcL submitted a review, later dismissed

2022-10-10 12:12 UTC, davidsiska-vega commented on protocol/0007-POSN-non_core_positions_api.md
> +- [ ] when a party has a non-zero postion, and no closeout position, only the unrealised PnL should be changed by change of position or change of mark price while realised PnL should not be updated (
```suggestion
- [ ] when a party has a non-zero postion, and has not closed any part of it, only the unrealised PnL should be changed by increase in position or change of mark price while realised PnL should stay constant (<a name="0007-POSN-010" href="#0007-POSN-010">0007-POSN-010</a>)
```

2022-10-10 12:14 UTC, davidsiska-vega commented on protocol/0007-POSN-non_core_positions_api.md
> +The Position API stores a net position for each trader who has ever traded in a market. Specifically,
```suggestion
The Position API provides access to net position per party per market. Specifically,
```

2022-10-10 12:39 UTC, TomMcL approved these changes

2022-10-10 14:11 UTC, davidsiska-vega approved these changes

2022-10-10 14:52 UTC, merged