Added Acs
vegaprotocol/specs pull request #1499
Opened 2023-01-09 12:26 UTC by Vegaklaus

2023-01-09 14:22 UTC, gordsport requested changes, later dismissed
changes requested related to spelling not content 

@claudiumilea or @vega-paul to review content

2023-01-09 14:22 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> + - If a party gets banned, the ban ends due to the epoch ending, and it gets banned again at the beginning of the new epoch, the bann still laasts the entire time (or until the next epoch end), i.e.,
```suggestion
 - If a party gets banned, the ban ends due to the epoch ending, and it gets banned again at the beginning of the new epoch, the ban still lasts the entire time (or until the next epoch end), i.e., the ban-expiration timer is reset. (<a name="0062-SPAM-017" href="#0062-SPAM-017">0062-SPAM-017</a>)  
```

2023-01-09 14:22 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> + - If a party gets banned several times duting an epoch, all banns last for the defined time or until the epich ends (try with at least three banns) (<a name="0062-SPAM-018" href="#0062-SPAM-018">006
```suggestion
 - If a party gets banned several times during an epoch, all banns last for the defined time or until the epoch ends (try with at least three banns) (<a name="0062-SPAM-018" href="#0062-SPAM-018">0062-SPAM-018</a>)  
```

2023-01-09 14:31 UTC, vega-paul commented
Can I suggest we add a few more ACS to cover undelegation trx and to cover ensuring this trx does not impact core performance unduly.

Could we add....

More than 360 undelegation changes in one epoch (or, respectively, the value of spam.protection.max.undelegation)

Undelegating while having less than one vega (10^18 of our smallest unit) (spam.protection.undelegation.min.tokens)

2023-01-09 14:47 UTC, gordsport commented
@Vegaklaus 
from paul:
> Can I suggest we add a few more ACS to cover undelegation trx and to cover ensuring this trx does not impact core performance unduly.

Could we add....

More than 360 undelegation changes in one epoch (or, respectively, the value of spam.protection.max.undelegation)

Undelegating while having less than one vega (10^18 of our smallest unit) (spam.protection.undelegation.min.tokens)

2023-01-10 14:36 UTC, claudiumilea approved these changes

2023-01-10 14:39 UTC, merged