Update 0042-LIQF-setting_fees_and_rewarding_lps.md
vegaprotocol/specs pull request #1598
Opened 2023-02-23 16:57 UTC by vega-paul

2023-02-24 09:53 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +- An LP joining a market that is below the target stake with a higher fee bid than the current fee: their fee is used (<a name="0042-LIQF-019" href="#0042-LIQF-019">0042-LIQF-019</a>)
```suggestion
- An LP joining a market that is below the target stake with stake that will take the market over the target with a higher fee bid than the current fee: their fee is used (<a name="0042-LIQF-019" href="#0042-LIQF-019">0042-LIQF-019</a>)
```

2023-02-24 09:55 UTC, davidsiska-vega commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +- An LP leaves a market that is above target stake when their fee bid is lower than the one currently being used and their commitment size doesn't the LP that meets the target stake: fee doesn't chan
I am struggling to parse this sentence.

2023-02-24 09:56 UTC, davidsiska-vega requested changes
Apart from one comment and the linting errors it looks good.

2023-02-27 13:53 UTC, barnabee commented on protocol/0042-LIQF-setting_fees_and_rewarding_lps.md
> +- An LP leaves a market that is above target stake when their fee bid is lower than the one currently being used and their commitment size doesn't the LP that meets the target stake: fee doesn't chan
```suggestion
- An LP leaves a market that is above target stake when their fee bid is lower than the one currently being used and their commitment size doesn't change which LP meets the target stake: fee doesn't change (<a name="0042-LIQF-027" href="#0042-LIQF-027">0042-LIQF-027</a>)
```

2023-02-27 13:53 UTC, gordsport commented
@vega-paul 
I have fixed the liniting / spelling. Just this review comment to address:

- https://github.com/vegaprotocol/specs/pull/1598#discussion_r1116749182

2023-02-27 20:50 UTC, davidsiska-vega approved these changes

2023-02-27 22:54 UTC, merged