chore: add decision about market-depth with regard to iceberg orders
vegaprotocol/specs pull request #1747
Opened 2023-06-08 10:00 UTC by wwestgarth

2023-06-08 10:16 UTC, gordsport requested changes
@wwestgarth - I have made a few suggestions to fix the approbation. If the first change is accepted I will close this open PR: https://github.com/vegaprotocol/specs/pull/1742

2023-06-08 10:16 UTC, gordsport commented on protocol/0014-ORDT-order_types.md
>  2. The additional fields relating to iceberg orders should be available in the streaming api end points
```suggestion
2. The additional fields relating to iceberg orders should be available in the streaming api end points (<a name="0014-ORDT-040" href="#0014-ORDT-040">0014-ORDT-040</a>)
```

2023-06-08 10:16 UTC, gordsport commented on protocol/0014-ORDT-order_types.md
> +3. API end points showing market-depth or price-level volume should include the full volume of iceberg orders (<a name="0014-ORDT-039" href="#0014-ORDT-039">0014-ORDT-039</a>)
```suggestion
3. API end points showing market-depth or price-level volume should include the full volume of iceberg orders (<a name="0014-ORDT-041" href="#0014-ORDT-041">0014-ORDT-041</a>)
```

2023-06-08 12:47 UTC, witgaw commented on protocol/0014-ORDT-order_types.md
> +* Any API that returns information about market-depth or the orderbook volume will include an iceberg orders full volume and not just its `display quantity`.
```suggestion
* Any API that returns information about market-depth or the orderbook volume will include an iceberg order's full volume and not just its `display quantity`.
```

2023-06-08 12:48 UTC, witgaw approved these changes, later dismissed

2023-06-14 11:02 UTC, witgaw approved these changes

2023-06-14 11:07 UTC, gordsport approved these changes

2023-06-14 11:07 UTC, merged