Govt mkt closure AC clarification
vegaprotocol/specs pull request #1851
Opened 2023-07-24 09:41 UTC by witgaw

2023-07-24 19:37 UTC, vega-paul requested changes

2023-07-24 19:37 UTC, vega-paul commented on protocol/0028-GOVE-governance.md
>  - Enacting a market closure governance proposal on a market that is not in a settled state always uses the final price supplied with the proposal, even when the oracle settlement price is available a
This one is confusing, there is no closing proposal, only terminate, resume, suspend. Terminating (close state) proposals will reject unless active market. What does final price man here - there is only one price supplied on the proposal.

2023-07-25 09:08 UTC, witgaw commented on protocol/0028-GOVE-governance.md
>  - Enacting a market closure governance proposal on a market that is not in a settled state always uses the final price supplied with the proposal, even when the oracle settlement price is available a
Closure and termination proposal is the same, specs refer to it as "move market to a closed state" in the spec. 
There is only one price supplied on the proposal and there's only one price that will be final from market's point of view, it's meant to be the same price. Rephrased now.

2023-07-25 14:36 UTC, vega-paul approved these changes

2023-07-25 14:36 UTC, merged