Markets in suspension can be resumed or terminated after a protocol u…
vegaprotocol/specs pull request #1855
Opened 2023-07-26 08:54 UTC by vega-paul

…pgrade restarts the network

2023-07-26 09:43 UTC, gordsport requested changes
Please also add the new AC to:

- https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/features.json

BEFORE it is merged

2023-07-26 10:12 UTC, Jiajia-Cui commented on protocol/0028-GOVE-governance.md
> +- Markets in suspension can be resumed or terminated after a protocol upgrade restarts the network. (<a name="0028-GOVE-145" href="#0028-GOVE-145">0028-GOVE-145</a>)
Markets is suspended by governance

2023-07-28 15:06 UTC, Jiajia-Cui submitted a review, later dismissed
LGTM

2023-07-28 15:09 UTC, vega-paul commented
@gordsport https://github.com/vegaprotocol/specs/pull/1868

2023-07-28 15:55 UTC, gordsport approved these changes
Approving as the content has not changed since the last approval

2023-07-28 15:55 UTC, merged