Feat eth oracles ac updates
vegaprotocol/specs pull request #1871
Opened 2023-07-31 14:26 UTC by MuthuVega

Updates to the acceptance criteria to match implementation

2023-07-31 14:41 UTC, AnExsomnis submitted a review, later dismissed

2023-08-02 09:03 UTC, pscott31 submitted a review, later dismissed

2023-08-02 09:54 UTC, gordsport requested changes
@MuthuVega 

Please can you update the protocol/features.json file with the additions/removals

2023-08-02 10:09 UTC, Jiajia-Cui commented on protocol/0082-ETHD-ethereum-data-source.md
> +1. Protocol upgrade should have no impact on a market using an ethereum oracle for settlement and/or termination (<a name="0082-ETHD-042" href="#0082-ETHD-042">0082-ETHD-042</a>)
more specific wording 

more than 1 AC

@jgsbennett @vega-paul

2023-08-02 10:09 UTC, Jiajia-Cui commented on protocol/0082-ETHD-ethereum-data-source.md
> +1. Update an existing market using the market update proposal to change the smart contract address and read method. The changes take effect after the market update proposal is enacted and data is sou
do we have enough coverage?

more ACs 

@MuthuVega

2023-08-03 14:36 UTC, MuthuVega commented
Closing this PR as opened a new one - https://github.com/vegaprotocol/specs/pull/1875

2023-08-03 14:36 UTC, closed without merging