Clarify perps API considerations
vegaprotocol/specs pull request #1907
Opened 2023-08-22 15:13 UTC by witgaw

Clarify data requirements related to perps.

Closes https://github.com/vegaprotocol/specs/issues/1849

2023-08-22 15:27 UTC, davidsiska-vega requested changes
Some comments...

2023-08-22 15:27 UTC, davidsiska-vega commented on protocol/0053-PERP-product_builtin_perpetual_future.md
> +- funding payment,
I am assuming this is on a per-party basis?

2023-08-22 15:27 UTC, davidsiska-vega commented on protocol/0053-PERP-product_builtin_perpetual_future.md
> +- funding payment,
Or for a hypothetical position of size `1`?

2023-08-22 15:27 UTC, davidsiska-vega commented on protocol/0053-PERP-product_builtin_perpetual_future.md
> +- estimate time,
This is a bit unclear to me; is it like "funding period end time", if the end was now?

2023-08-22 15:31 UTC, witgaw commented on protocol/0053-PERP-product_builtin_perpetual_future.md
> +- estimate time,
Hopefully clarified now.

2023-08-22 15:31 UTC, witgaw commented on protocol/0053-PERP-product_builtin_perpetual_future.md
> +- funding payment,
Yes, clarified now.

2023-08-22 15:48 UTC, JonRay15 commented
As mentioned on Slack the only thing I still dont see anywhere here is the static on the market details API related to funding duration & frequency, which we need in order to handle the countdown to the next funding event.  Would like to see this added before merging please.

2023-08-23 10:01 UTC, davidsiska-vega approved these changes

2023-08-23 10:40 UTC, merged