feat: updates for transfers from vested accounts
vegaprotocol/specs pull request #2033
Opened 2023-11-03 11:37 UTC by cdummett

closes #2032

2023-11-03 15:02 UTC, davidsiska-vega commented on protocol/0057-TRAN-transfers.md
> +A fee is taken from all transfers (except transfers from a vested account), and paid out to validators in a similar manner to the existing [infrastructure fees](0061-REWP-pos_rewards.md). For recurri
```suggestion
A fee is taken from all transfers (except transfers from a vested account to a general account held by the same key), and paid out to validators in a similar manner to the existing [infrastructure fees](0061-REWP-pos_rewards.md). For recurring transfers, the fee is charged each time the transfer occurs.
```

2023-11-03 15:03 UTC, davidsiska-vega commented on protocol/0057-TRAN-transfers.md
> +- As a user I can do a transfer from a vested account without incurring any fees (<a name="0057-TRAN-066" href="#0057-TRAN-066">0057-TRAN-066</a>).
```suggestion
- As a user I can do a transfer from a vested account to a general account held by the same key without incurring any fees (<a name="0057-TRAN-066" href="#0057-TRAN-066">0057-TRAN-066</a>).
```

2023-11-03 15:05 UTC, davidsiska-vega commented on protocol/0085-RVST-rewards_vesting.md
> +Once vested rewards are transferred to the vested account, the party will be able to transfer funds to their general account using a normal transfer. When transferring funds from a vested account a p
```suggestion
Once vested rewards are transferred to the vested account, the party will be able to transfer funds to their general account using a normal transfer.
When transferring funds from a vested account to the general account held by their key a party will incur no transfer fees and if transferring the full balance they will not be subject to the minimum quantum transfer amount.
```

2023-11-03 15:05 UTC, davidsiska-vega commented on protocol/features.json
> +      "0057-TRAN-068"
"0057-TRAN-069",

2023-11-03 15:05 UTC, davidsiska-vega requested changes
I've left a few suggestions, please have a look.

2023-11-06 10:23 UTC, davidsiska-vega approved these changes, later dismissed

2023-11-06 10:24 UTC, TomMcL commented on protocol/0057-TRAN-transfers.md
> +If a user is transferring funds from a vested account, if their balance (expressed in quantum) is less than the minimum amount, they should be able to transfer the full balance (note, transferring le
```suggestion
If a user is transferring funds from a vested account, if their balance (expressed in quantum) is less than the minimum amount, they should be able to transfer the full balance (note, transferring less than the full balance is not permitted).
```

2023-11-06 10:40 UTC, davidsiska-vega approved these changes

2023-11-06 10:57 UTC, merged

2023-11-06 11:30 UTC, gordsport commented
Core change in:

- https://github.com/vegaprotocol/vega/pull/9984