feat: update 0057
vegaprotocol/specs pull request #2350
Opened 2024-08-20 11:17 UTC by Jiajia-Cui

2024-08-20 14:45 UTC, davidsiska-vega commented on protocol/0013-ACCT-accounts.md
> +A party can transfer governance tokens in and out of the "LOCKED_FOR_STAKING" account. The balance in this account should count towards the tokens "associated" with the Vega key for staking purposes
```suggestion
A party can transfer governance tokens in and out of the "LOCKED_FOR_STAKING" account. The balance in this account should count towards the tokens [associated](./0059-STKG-simple_staking_and_delegating.md) with the Vega key for staking purposes and can be staked to specific validators, earning staking rewards for that key.
```

2024-08-20 14:45 UTC, davidsiska-vega commented on protocol/0057-TRAN-transfers.md
> +- A user can transfer funds from and to a locked account used for staking [LOCKED_FOR_STAKING](./0059-STKG-simple_staking_and_delegating.md).
```suggestion
- A user can transfer the governance token only from and to a locked account used for staking [LOCKED_FOR_STAKING](./0059-STKG-simple_staking_and_delegating.md).
```

2024-08-20 14:46 UTC, davidsiska-vega commented on protocol/0057-TRAN-transfers.md
> +- As a user I can transfer funds from a general account I control to a LOCKED_FOR_STAKING account. Such transfer can be immediate or delayed. (<a name="0057-TRAN-003" href="#0057-TRAN-003">0057-TRAN-
```suggestion
- As a user I can transfer the governance token from a general account I control to a LOCKED_FOR_STAKING account. Such transfer can be immediate or delayed. (<a name="0057-TRAN-003" href="#0057-TRAN-003">0057-TRAN-003</a>).
```

2024-08-20 14:47 UTC, davidsiska-vega commented on protocol/0057-TRAN-transfers.md
> +- As a user I can transfer funds from a LOCKED_FOR_STAKING account under my control to any party's general account. Such transfer can be immediate or delayed.  (<a name="0057-TRAN-004" href="#0057-TR
```suggestion
- As a user I can transfer the governance token from a LOCKED_FOR_STAKING account under my control to any party's general account. Such transfer must be immediate.  (<a name="0057-TRAN-004" href="#0057-TRAN-004">0057-TRAN-004</a>)
```

2024-08-20 14:47 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +Any rewards paid in governance tokens that are locked should be included in the same [account].
What does this mean?

2024-08-20 14:47 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +Any rewards paid in governance tokens that are locked should be included in the same [account].
Also we'd want ACs for locked rewards.

2024-08-20 14:48 UTC, davidsiska-vega requested changes
We need more detail around staking locked rewards.

2024-08-21 14:12 UTC, davidsiska-vega commented on protocol/0013-ACCT-accounts.md
> +[Parties](./0017-PART-party.md) are identified by Vega public keys. Each party that makes a deposit on one of the asset bridges, currently only [Ethereum ERC20 bridge](./0031-ETHB-ethereum_bridge_spe
```suggestion
[Parties](./0017-PART-party.md) are identified by Vega public keys. Each party that makes a deposit on one of the asset bridges, currently only [Ethereum ERC20 bridge](./0031-ETHB-ethereum_bridge_spec.md) will have a general account for the relevant [asset](./0040-ASSF-asset_framework.md) created.
A party that transfers any balance of the governance token into  its "LOCKED_FOR_STAKING" account will have that account created.
```

2024-08-21 14:15 UTC, davidsiska-vega commented on protocol/0057-TRAN-transfers.md
> +- A user can transfer the governance token only from and to a locked account used for staking [LOCKED_FOR_STAKING](./0059-STKG-simple_staking_and_delegating.md).
This isn't true. You can also transfer vega tokens from general account to another key's general account.

2024-08-21 14:18 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +Governance tokens locked in the "LOCKED_FOR_STAKING" account are associated with a VEGA key. To stake these locked governance tokens, the party must delegate them to one or more validators. When toke
```suggestion
Governance tokens locked in the "LOCKED_FOR_STAKING" account count as associated with the VEGA key of the party controlling the account.
To stake these locked governance tokens, the party must delegate them to one or more validators.

When governance token balance is transferred out of the "LOCKED_FOR_STAKING" account, the key's balance of associated token will be reduced accordingly and the staking balances removed from validators.
```

2024-08-21 14:24 UTC, davidsiska-vega commented on protocol/0013-ACCT-accounts.md
> +Vega core listens to events on other chains (currently Ethereum) for events on the bridge contract. If governance token reward is locked on the bridge contract with a Vega party key associated then t
```suggestion
```

2024-08-21 14:25 UTC, davidsiska-vega commented on protocol/0013-ACCT-accounts.md
> +
AC for rewards are in a different place, I wouldn't randomly add them here.

2024-08-21 14:27 UTC, davidsiska-vega submitted a review, later dismissed
more changes discussed

2024-08-21 15:25 UTC, davidsiska-vega commented on protocol/0056-REWA-rewards_overview.md
> +When a party earns rewards (in governance token), they are transferred into the party's locked account and locked for the appropriate period before vesting. Sum of rewards in vesting account and lock
```suggestion
When a party earns locked rewards (in governance token), they are transferred into the party's locked rewards account and locked for the appropriate period before vesting.
Sum of rewards in vesting account and locked account should count toward the party's staking balance and they can be [staked](0059-STKG-simple_staking_and_delegating.md).
```

2024-08-21 15:25 UTC, davidsiska-vega commented on protocol/0056-REWA-rewards_overview.md
> +- When a party transfers locked tokens out of the [Locked_FOR_REWARD] account, the balance for the party is decreased by the corresponding amount. (<a name="0056-REWA-201" href="#0056-REWA-201">0056-
```suggestion
```

2024-08-21 15:26 UTC, davidsiska-vega commented on protocol/0056-REWA-rewards_overview.md
> +- A party can stake the assets in the [Locked_FOR_REWARD] account. (<a name="0056-REWA-202" href="#0056-REWA-202">0056-REWA-202</a>).
```suggestion
- Balance of the governance asset in the [Locked_FOR_REWARD] account counts towards the party's staking balance and can be nominated to a validator and earn staking rewards. (<a name="0056-REWA-202" href="#0056-REWA-202">0056-REWA-202</a>).
```

2024-08-21 15:27 UTC, davidsiska-vega commented on protocol/0059-STKG-simple_staking_and_delegating.md
> +Governance tokens locked in the "LOCKED_FOR_STAKING" account count as associated with the VEGA key of the party controlling the account.
```suggestion
Governance tokens that have been transferred into the "LOCKED_FOR_STAKING" account count as associated with the VEGA key of the party controlling the account.
```

2024-08-21 15:30 UTC, Jiajia-Cui commented on protocol/0056-REWA-rewards_overview.md
> +- When a party transfers locked tokens out of the [Locked_FOR_REWARD] account, the balance for the party is decreased by the corresponding amount. (<a name="0056-REWA-201" href="#0056-REWA-201">0056-
why delete this AC?

2024-08-22 10:14 UTC, jeremyletang commented on protocol/0013-ACCT-accounts.md
> +Each party that has locked and vesting rewards will have a "LOCKED_FOR_STAKING" account for the relevant [asset] created, party can transfer the tokens in and out of this LOCKED_FOR_STAKING account.
I believe that the funds will be staying in the vesting / vested accounts, LOCKED_FOR_STAKING should be used only from a general account. 

The account will be created on demand if needed.

2024-08-22 10:26 UTC, cdummett requested changes

2024-08-22 10:26 UTC, cdummett commented on protocol/0056-REWA-rewards_overview.md
> +Sum of rewards in vesting account and locked account should count toward the party's staking balance and they can be [staked](0059-STKG-simple_staking_and_delegating.md).
Small clarification, in cores implementation there are no separate locked rewards and vesting accounts, they are one single account.
```suggestion
When a party earns locked rewards (in governance token), they are transferred into the party's vesting account account but locked for the appropriate period before vesting.
The rewards in the vesting account (both locked and unlocked) should count toward the party's staking balance and they can be [staked](0059-STKG-simple_staking_and_delegating.md).
```

2024-08-22 10:26 UTC, cdummett commented on protocol/0056-REWA-rewards_overview.md
> +- When a party receives a governance token reward that is locked, the [Locked_FOR_REWARD] balance for the party is incremented by the corresponding amount. (<a name="0056-REWA-200" href="#0056-REWA-2
```suggestion
- When a party receives a governance token reward that is locked, the [LOCKED_FOR_STAKING] balance for the party is incremented by the corresponding amount. (<a name="0056-REWA-200" href="#0056-REWA-200">0056-REWA-200</a>).
```

2024-08-22 10:26 UTC, cdummett commented on protocol/0056-REWA-rewards_overview.md
> +- Balance of the governance asset in the [Locked_FOR_REWARD] account counts towards the party's staking balance and can be nominated to a validator and earn staking rewards. (<a name="0056-REWA-202"
```suggestion
- Total balance of the governance asset in the relevant vesting account counts towards the party's staking balance and can be nominated to a validator and earn staking rewards. (<a name="0056-REWA-202" href="#0056-REWA-202">0056-REWA-202</a>).
```

2024-08-22 10:26 UTC, cdummett commented on protocol/0057-TRAN-transfers.md
> +- A user can transfer governance tokens from and to a locked account used for staking [LOCKED_FOR_STAKING](./0059-STKG-simple_staking_and_delegating.md).
Don't think we need this any more? Tokens should contribute automatically without transfer.

2024-08-23 10:06 UTC, cdummett requested changes

2024-08-23 10:06 UTC, cdummett commented on protocol/0057-TRAN-transfers.md
> +- As a user I can transfer the governance token from a LOCKED_FOR_STAKING account under my control to any party's general account. Such transfer must be immediate.  (<a name="0057-TRAN-004" href="#00
Think these need to be added to features.json as well.

2024-08-23 10:06 UTC, cdummett commented on protocol/features.json
> +      "0056-REWA-221"
These need to go in a new feature section, otherwise they will come under reward scaling.

2024-08-23 11:00 UTC, cdummett approved these changes

2024-08-23 11:09 UTC, merged