WIP: Resolve "Auction spec"
vegaprotocol/specs pull request #256
Opened 2020-03-27 16:19 UTC by ashleyvega

In GitLab by @tamlyn10 on Dec 13, 2019, 15:48

Closes #187

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @jeremyletang on Dec 19, 2019, 13:36

added 1 commit

<ul><li>1ad96b8d - add initial auctions specs</li></ul>

[Compare with previous version](/vega-protocol/product/merge_requests/38/diffs?diff_id=68377835&start_sha=90af572bc5acafe26ea15c2877d3c73a052bd228)

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @peterbarrow on Feb 25, 2020, 14:46

At the end of an auction period (in frequent batch mode), do the orders that do not get filled remain on the book for the next auction period?

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @peterbarrow on Feb 25, 2020, 14:47

Do we still want to do this: `We can also imagine that an auction period could come to an end once a give number of orders have been placed on the system`

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @peterbarrow on Feb 25, 2020, 14:50

added 1 commit

<ul><li>31efea72 - Fixed some typos</li></ul>

[Compare with previous version](/vega-protocol/product/-/merge_requests/38/diffs?diff_id=77102031&start_sha=1ad96b8d52f1fa8b6c46b74f6fd7e3ef410e96eb)

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @edd on Mar 25, 2020, 16:21

Note: We have a trading Mode field for a market, which should change when the mode changes.
Another API change: Candles for an auction period should be noted in the API with some sort of flag
Another API change: We need to be able to see the parameters of the auction - when it started, etc

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @jeremyletang on Mar 25, 2020, 16:33

I do not thing it should change. The market you get through the api, is the market framework / the market definition as decided through the governance.

We can create a new api for you tho, with information about the mode of the market, and how long it's been in the mode, how long the period last etc.

2020-03-27 16:19 UTC, ashleyvega commented
In GitLab by @edd on Mar 25, 2020, 17:06

That makes some sense and I'm alright with that as longs it ends up being clear, which might mean changing some field names

2020-05-07 15:13 UTC, barnabee requested changes
See comments in file - a few changes needed but it isn't too far off

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +An auction's purpose is to help with price discovery, and are mostly useful in very liquid markets. In traditional markets (where markets open and close every day) we can run an open and closing auct
Suggested change to:

They are mostly useful in less liquid markets, or in specific scenarios where a price must be determined, i.e. at opening of a market, when a potentially excessively large price move might occur (price monitoring) or when liquidity needs to be sourced and aggregated (liquidity monitoring). In traditional markets (where markets open and close every day) we can run an open and closing auction for the price to stabilise at both ends.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +As mentioned earlier, this specification introduces new trading modes. A first one which purpose is to calibrate a market / help with price discovery when a new market is started. A second one meant
This specification introduces auctions as a new method of trade execution. This is used in two new trading modes:

- A temporary trading mode (aka 'auction period') where the auction call period begins and ends either at a time or when certain conditions are met. This mode overrides the market's price determination method when in effect. Initially it will be used at the creation of a new market (for a length of time determined by a market parameter). Market monitoring features (price monitoring, liquidity monitoring) will also be able to invoke and determine the end of an auction period.
- A price determination method that can be used instead of _continuous trading_ as the main execution mode of a market. This is set in the market framework for the market when it's created and can be changed via a standard market governance action proposal.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +## First mode (name to be find, but it may just be actually the continuous trading changing to always start with an auction ?)
name: Auction period at market creation

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +This trading mode is very similar to the Continuous trading mode for a market. In this configuration, a market will start in auction mode, then once the auction comes to an end the market will switch
When auctions are implemented, all new markets with price determination type continuous trading or frequent batch auction will begin at creation with an auction period of the length specified in the market creation proposal rather than entering continuous trading. There will be a network parameter that sets the minimum allowable duration of this auction period and proposals must specify a period of at least this duration.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +A market cannot be in both mode at the same time and will trade ever in a auction or continuous trading.
A market always has one trading mode. That is either the configured mode in the market framework (continuous trading or frequent batch auction) OR it is a period (i.e. an auction period) that temporarily overrides that mode, i.e. at opening or after price/liquidity monitoring is triggered.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +As a first implementation this feature is expected to only support starting the markets in auctions, then once the auction reaches an end, switch back to the continuous trading mode forever.
As a first implementation auction periods will be used at opening only as price/liqudity monitoring will not exist.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +The frequent batch auction mode is a trading mode in perpetual auction, meaning that all uncrossing on the book is done at the end of auction period, then once this is done, and trades happen, a new
Note that a frequent batch auction will still have an opening auction (which must have a duration equal to or greater than the normal batch auction duration, as well as meeting the minimum opening auction duration network parameter). Additionally, price and liquidity monitoring will also be able to override the trading mode and push the market into a longer auction to resolve the triggering event.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +## An auction comes to an end
title: Duration of frequent batch auctions

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +As part of the market framework, we need to be able to specify the duration of auctions period. This should be added as a new setting to the trading modes.
This parameter is modifiable via a standard market parameter governance action

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +Once the auction period finishs, vega needs to figure out the best price for the order range in the book which can be uncrossed. This is called volumed maximising pricing.
The first stage in this is to calculate the volume maximising price range. That is, the range of prices (which will be a contiguous range in an unconstrained order book) at which the highest total quantity of trades can occur.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +Once this range is decided we will run an algorithm in order to decided what's the best price to create the trades at (the algorithm is specified in a separate specification, @barney, @tamlyn, please
Initially we will use the mid price within this range, i.e. if the volume maximising range is 98–102 we would price all trades in the uncrossing at 100. In future there will be other options, these should be selectable via a market parameter specified at market creation and changeable via governance action.

2020-05-07 15:13 UTC, barnabee commented on specs/0026-auctions.md
> +- the indicative uncrossing price (e.g: if we uncross now what would be the best bid/ask prices of the trades)
indicative uncrossing price = what price would all trades occur at if we uncrossed the auction now. This will need to be streamed like a normal price but also API users need a way to know it's an indicative uncrossing price not a last traded price, mid price, etc. (i.e. it gets its own market data field)

2020-05-07 15:14 UTC, barnabee commented
> In GitLab by @peterbarrow on Feb 25, 2020, 14:47
> 
> Do we still want to do this: `We can also imagine that an auction period could come to an end once a give number of orders have been placed on the system`

🤷  I'd be fine with not having this initially. I'm not sure how useful it would be… @tamlyn10 ?

2020-05-07 15:16 UTC, barnabee commented
> In GitLab by @peterbarrow on Feb 25, 2020, 14:46
> 
> At the end of an auction period (in frequent batch mode), do the orders that do not get filled remain on the book for the next auction period?

@peterbarrow yes, normally they remain, however we will need to add GFA (Good For Auction) as a time in force type which will cause orders of that type to be expired after the uncrossing if still on the book.

2020-05-07 15:16 UTC, edd commented
> 🤷 I'd be fine with not having this initially. I'm not sure how useful it would be… @tamlyn10 ?

https://github.com/vegaprotocol/product/issues/201 Is mildly relevant

2020-05-07 15:17 UTC, barnabee commented
> In GitLab by @edd on Mar 25, 2020, 16:21
> 
> Note: We have a trading Mode field for a market, which should change when the mode changes.
> Another API change: Candles for an auction period should be noted in the API with some sort of flag
> Another API change: We need to be able to see the parameters of the auction - when it started, etc

@edd we will need to know both the configured trading mode (continuous trading or frequent batch auction), AND the current period (either the configured mode OR a temporary auction period due to market opening, price monitoring, liquidity monitoring, etc.)

2020-05-07 16:49 UTC, tamlyn10 commented on specs/0026-auctions.md
> + - [] I can define an opening auction for a continuous trading market, and the duration of the call period.
subject to a minimum call period that is specified by a market parameter

2020-05-11 11:32 UTC, edd commented
I’ve incorporated all the changes on this one. I think we’re ready to merge and ticket this.

2020-05-12 16:42 UTC, barnabee requested changes
Looks good except one part of description I think still needs updating

2020-05-12 16:42 UTC, barnabee commented on specs/0026-auctions.md
> +As mentioned earlier, this specification introduces new trading modes. A first one which purpose is to calibrate a market / help with price discovery when a new market is started. A second one meant
I don't think the current text accurately represents the auctions we're representing. We need to build the ability to have a market in a temporary auction period at any time, not only "to calibrate a market / help with price discovery when a new market is started".

2020-05-12 16:43 UTC, barnabee commented
Agree ready to merge subject to the one caveat in my review 👍

2020-06-16 12:56 UTC, tamlyn10 commented
Could someone please answer @barnabee question here?

2020-07-01 15:03 UTC, tamlyn10 commented
@barnabee going to update this as suspects it's minor updates..

2020-07-13 14:46 UTC, edd requested changes
This spec needs more detail on:

 - Auctions mode for continuous markets

Specifically the range of factors that can start and end an auction. It seems to me like the early version will be a price discovery auction and a liquidity sourcing auction. The spec needs to detail:

- What happens to the book at auction start
- How the exit conditions are defined
- What happens to the book at auction end

2020-07-14 13:29 UTC, davidsiska-vega commented
@barnabee, how does an opening auction end?
Do I wait for a defined period letting people post prices, see if I have any potential trades at the end, if yes run the trades resulting in a mark price and switch to continuous trading, if no then go back to waiting for a fixed period?

2020-07-14 14:53 UTC, barnabee commented
> @barnabee, how does an opening auction end?
> Do I wait for a defined period letting people post prices, see if I have any potential trades at the end, if yes run the trades resulting in a mark price and switch to continuous trading, if no then go back to waiting for a fixed period?

Hmm, good question. I think we do need trades to occur to set a mark price confidently, so if no trades would happen I think yes, it should be extended. Perhaps there's a network parameter that says how long the extension is for.

Additionally, we cannot end the opening auction if there would be insufficient liquidity afterwards (i.e. the criteria for exiting liquidity monitoring apply, too).

Finally, if for either lack of trading or lack of liquidity, the auction does not end after some longer period (another network param should specify this), the market should be closed without trading.

2020-07-16 17:29 UTC, witgaw commented
@davidsiska-vega @barnabee I've added the details discussed during the liquidity monitoring meeting today: https://github.com/vegaprotocol/product/pull/256/commits/3c854cc95e1f40f48a0d6aa98ff5f7d42db0e7e9

2020-07-17 14:13 UTC, merged