WIP: Resolve "Spec pegged orders"
vegaprotocol/specs pull request #262
Opened 2020-03-27 16:24 UTC by ashleyvega

In GitLab by @barnabee on Feb 10, 2020, 15:39

Closes #216

2020-03-27 16:24 UTC, ashleyvega commented
In GitLab by @barnabee on Feb 10, 2020, 16:34

added 1 commit

<ul><li>4e17c58a - WIP first draft marker maker and pegged orders</li></ul>

[Compare with previous version](/vega-protocol/product/-/merge_requests/47/diffs?diff_id=74813012&start_sha=79188028b06bb19c8dca91cb672d40a94e6d5cf4)

2020-07-01 14:59 UTC, tamlyn10 commented
Pete to let Barney know if it would be preferable for Barney to make further progress on this before handing over.

2020-07-08 14:22 UTC, peterbarrow commented
Questions still needing to be answered:
1. Do we want hidden orders?
2. Do we want to publish all order updates?
3. Do we want to include pegged orders in market depth/best-bid/best-ask?
4. Are FOK+IOC orders OK?

@tamlyn10 @davidsiska-vega Do you have any thoughts please?

2020-07-08 15:24 UTC, barnabee commented
Been chatting a bit to @peterbarrow on the "hidden" order thing (1 & 2) - obviously we can't actually hide orders but deciding what the core emits and what the APIs expose around pegs is interesting. I think he's going to propose some ideas but going to need a wider discussion to choose as it will be a question of trade-offs... (doesn't affect how the protocol works but how the APIs do and what someone sees through them and in Console)

2020-07-08 15:26 UTC, barnabee commented
> 4. Are FOK+IOC orders OK?

Unless @tamlyn10 disagrees I propose yes, we allow non-persistent orders to be pegged. Given latency it makes sense someone might want to do an IOC at an offset from the BBO/mid IMO.

2020-07-09 09:37 UTC, campbellssource commented on 0000-pegged-orders.md
> +* A market must specifically support pegged orders
Clarification question: Does this mean that when proposing a market I'd have to say I want it to accept pegged orders? Or that there will be some types of markets that for some set of rules shouldn't be allowed to accept pegged orders?
If the former it might be worth updating market framework spec?

2020-07-09 10:11 UTC, peterbarrow commented on 0000-pegged-orders.md
> +* A market must specifically support pegged orders
From my understanding I think your first option is right, when creating a market you must specify that it can handle pegged orders during continuous trading. Once @barnabee confirms I will update the market framework spec.

2020-07-09 11:08 UTC, campbellssource commented
@peterbarrow fyi I sketch out some thoughts for what an order ticket might look like in console. https://github.com/vegaprotocol/console/issues/4035 
As I read the spec there is a notion of a group or orders, in the mock ups there is an option for each order in the group to share parameters: size, Reference, and TIF, or set them separately for each order. I'm not sure what will/should be should be supported.

2020-07-12 06:45 UTC, campbellssource commented
More considerations of pegged orders in console fyi: https://github.com/vegaprotocol/console/issues/4044

2020-07-13 14:08 UTC, peterbarrow commented
We had a meeting to discuss what events would be emitted from the core when handling pegged orders and how it would happen. These probably apply to the market depth spec more than pegged orders. We produced the following points:

Market Depth Data
* Market Depth should include pegged order volume
* We should separate the volume at each level into normal, pegged and market making order volumes to allow them to be drawn with different attributes in the console
* We should generate a best bid/ask pair for all orders and for all order excluding pegged.

Order Stream
* We will not distribute price level updates as they might be too frequent and overload the handlers

2020-07-15 14:41 UTC, witgaw commented
@peterbarrow (cc @barnabee) just pushed some minor edits, hope you don't mind - please let me know if you disagree with any on them.

The spec looks really good to me, just a few comments/questions from me:

1. I'd suggest removing the bit about Market Maker orders from this spec and moving it to a separate one. I don't think it contains enough detail for those orders and it's already fairly complex for pegged orders themselves thus I think it would make sense to split the two.

2. These things seem somewhat at odds with each other to me:

> Pegged orders can be GTC, GTC, IOC or FOK TIF orders. 

and 

> Pegged orders are restricted in what values can be used when they are created, these can be defined by a list of rules each order must abide with.
> 
> Buy orders must be pegged against best bid or mid and the offset must be negative (<0).
> Sell order must be pegged against best ask or mid and the offset must be positive (>0).

My understanding is that we never resolve orders off the book (we process them sequentially and an order either matches with another order(s) already on the book resulting in a trade or it gets added to the book). If that's the case and the restrictions on offset signs for buy/sell orders mentioned above apply then I don't see the IOC or FOK pegged orders ever having any effect.

Do you agree with the above interpretation or am I missing something? If so which of those assumption do we want to change? In my naive view a buy order with a positive offset (and sell order with a negative one) would still make sense if I'm interested in being a very active market maker that always posts the most competitive prices. However, there may be some practical reasons against that - please let me know if that's the case.

3. `PeggedOrder{
    PeggedType type
    OrderID    orderID
}`

Would `PeggedType` contain the `Offset` field or should it be added to the `PeggedOrder`?

I'm happy to make those modifications to the spec myself as long as you agree.

2020-07-15 15:26 UTC, barnabee commented on 0000-pegged-orders.md
> +* A market must specifically support pegged orders
Initially all markets should accept pegged orders — they are _required_ for market makers anyway.

2020-07-15 15:54 UTC, barnabee commented
@witgaw IOC and FOK pegged orders should be accepted IMO (though see the last part of this comment, too) but the below needs a slight tweak I think:

> Buy orders must be pegged against best bid or mid and the offset must be negative (<0).
> Sell order must be pegged against best ask or mid and the offset must be positive (>0).

Persistent pegged orders must not execute on entry or on being repriced because then you can have pegs interacting (trading) with other pegs, which means that as market maker orders are refreshed automatically they could get into a loop. We could do this by checking on each entry or reprice if they'd execute and cancelling them (like a true post only order) but that means that we couldn't guarnatee a market makers orders would always be valid. By restricting the peg offsets such that they cannot possibly trade on entry or reprice, this problem is avoided. (Imagine also the scenario of a low enough spread that the MM's orders are constantly price takers — they are then also supplying no useful liquidity under our model.) Similarly, a non-persistent pegged order must have a non-zero chance of trading on entry, otherwise it's pointless,

I think the above leads to the following set of rules (but someone please check!):

Type | Side | Bid Peg | Mid Peg | Offer Peg
------ | ---- | -------- | -------- | --------
Persistent (GTC, GTT, etc.) | Buy | `<= 0` | `< 0` | Not alllowed
Persistent (GTC, GTT, etc.) | Sell | `>= 0` | `> 0` | Not alllowed
Non persistent (IOC, FOK, etc.) | Buy | > 0 | > 0 | >= 0
Non persistent (IOC, FOK, etc.) | Sell | `<= 0` | `< 0` | `< 0`

> In my naive view a buy order with a positive offset (and sell order with a negative one) would still make sense if I'm interested in being a very active market maker that always posts the most competitive prices. 

Whilst that may be true, it causes problems as described above. One away from mid is pretty competitive — if it happens on both sides it'd lead to a spread of 2. 

In fact there is a futher question here of **what to do if mid is at a 1/2 tick size interval**. A suggestion is that when pegging, the mid is adjusted up or down depending on the side of the pegged order, i.e.

Best bid = 100, best offer = 105 => **mid = 102.5**
A buy pegged to `Mid - 1` should take the mid as 103, and thus be at `102`
A sell pegged to `Mid + 1` should take the mid as 102, and thus be at `103`

This looks good for peristent pegs, but I am not as sure for IOC/FOK.

To be honest it'd be OK to drop non-peristent (IOC/FOK) pegged orders from the first version of this spec. if it's make things simpler…? I think they're desirable because of our block latency, but maybe waiitng for someone to ask would save us some hassle? 🤷‍♂️

2020-07-23 12:44 UTC, jeremyletang commented
@peterbarrow @witgaw @barnabee what are the action to be done to get this spec merged now?

2020-07-23 14:17 UTC, barnabee commented
> @peterbarrow @witgaw @barnabee what are the action to be done to get this spec merged now?

I'm unsure. I made a comment above, can anyone tell me if either there are further questions that need answering or if it's updated and I need to review?

2020-08-05 14:53 UTC, tamlyn10 commented
@peterbarrow to take the lead on finishing this.

2020-08-11 13:22 UTC, peterbarrow commented
I have integrated all the updates from above and I am happy for this to be merged if others are.

2020-08-11 13:55 UTC, tamlyn10 commented on 0000-pegged-orders.md
> +
>Following a price move margin checks take place on the positions of the parties. 

Is this a generic statement or specific to this spec? In future, margins may be calculated under different triggers than a price move, trade etc.

2020-08-11 13:55 UTC, tamlyn10 commented on 0000-pegged-orders.md
> +
minor thing - is this meant to be one sentence?

2020-08-11 13:55 UTC, tamlyn10 commented on 0000-pegged-orders.md
> +
We just wrote this into the market making mechanics spec...

>As pegged orders are parked during an auction are parked and not placed on the book, margin checks will not occur. This includes checking the orders margin when checking the validity of the transaction.

>Engineering notes:
>- check that other pegged orders are treated the same

2020-08-12 13:08 UTC, peterbarrow commented on 0000-pegged-orders.md
> +
This is a generic comment as all orders entering the book must have their margin level checked before it will be allowed to be inserted. We currently do that with amends in that as we are removing the order from the book and re-inserting, we perform a margin check for the new amended order details. Do you think this is incorrect going forward?

2020-08-12 13:17 UTC, peterbarrow commented on 0000-pegged-orders.md
> +
Thanks, fixed.

2020-08-12 15:37 UTC, peterbarrow commented on 0000-pegged-orders.md
> +
I added a section to the spec to cover this, thanks Tamlyn.

2020-08-13 13:10 UTC, barnabee requested changes

2020-08-13 13:10 UTC, barnabee commented on 0000-pegged-orders.md
> +| Persistent (GTC, GTT, etc.)	  | Sell  | >= 0    | > 0     | Not allowed |
For persistent sells the bid peg is not allowed and you may peg to mid with > 0 or the best offer with >= 0

2020-08-14 06:38 UTC, tamlyn10 commented on 0000-pegged-orders.md
> +
When pegged orders are returned to the continuous trading limit order book after auction, I'm assuming they have lost time priority relative to the uncrossed limit orders that migrate back to a limit book after auction? If so, could we write here just for abundant clarity?

2020-08-14 13:02 UTC, barnabee commented on 0000-pegged-orders.md
> +
I don’t understand this comment, but may be missing something? Limit orders (that are not parked and don’t expire) stay on the book through the auction and into continuous trading. No migration of orders occurs going into or out of auction or continuous trading, they are both trading modes on the same order book. We may want to note that when pegs are unparked they don’t receive special treatment and are added to the back of the price level (lowest time priority).

**Some descriptions generally about peg pricing and time priority that may be useful to check the spec against and add in if anything is missing:**

Pegged orders being added back into the book after being parked (either due to an auction or their reference price not being available) are treated the same as any other order being added to the book and therefore come after all persistent orders at that price level that are already on the book (i.e. the pegs are added to the end/back of the price level as if new incoming orders). This is also true if a pegged order is re-priced _and its price changes_, as price amendments are equivalent to a cancel/replace so the order enters at the back of its new price level. 

When there are multiple pegged orders needing reprice, they must be repriced in order of entry (note: certain types of amend are considered amend in place and others as cancel/replace, for the cancel replace type, the entry time becomes the time of the amend, i.e. a pegged order loses its reprice ordering priority). Generally the way I’ve seen this is to maintain an ordered list of pegged orders for use in re-pricing (and parking/unparking), with new pegged orders added to the end of this list and cancel/replace amends causing the order to be removed from the list and re-added at the end.

2020-08-14 13:24 UTC, barnabee requested changes
This is pretty close I think! Few quite small comments/additions and clarifications but nothing major

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +- [ ] A markets ability to handle pegged orders is set at creation time and should be turned on by default.
Currently all markets must support pegged orders as they are required for liquidity provision (market making). This could be revisited if/when we have other liquidity sources.

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +- [ ] Parked orders are returned to the order book once continuous trading is resumed.
"returned to the order book in entry order"

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +- [ ] Pegged orders are repriced when their reference price moves.
Add: Pegged orders are not repriced and do not lose time priority when their specific reference price is unchanged, even if other peg reference prices move.

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +- [ ] An expired pegged order is removed from the book and the pegged/parked slice.
Add case for removal when they are filled?

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +
After re-reading the spec we say "parked in time priority". I do think this should be tightened up with something from the above because time priority is not defined at book level, only per price level (it can't necessarily be ascertained by looking at creation or update timestamp, for example after an amend), so we should be clear about how the ordering of peg reprices happens across the whole book.

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +**Offset:** This is a value added to the reference price. It can be negative.
Add that this must be a multiple of the tick size.

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +When a party submits a new pegged order, only a LIMIT order is accepted. The party also specifies the reference price to which the order will be priced along with an offset to apply to this price. Th
Note that the allowable peg reference + offset combinations should prevent a persistent (GTT/GTC) peg from hitting another order on reprice so this should not need to be checked for pegged limit orders.

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +Whenever the reference price changes all the pegged orders that rely on it need to be repriced. We run through a time sorted list of all the pegged orders and remove each order from the book, recalcu
When running through the sorted list of pegs we need to ensure we do not remove and replace any pegged orders that are pegged to an unmoved reference, so that they don't lost time priority. 

The sorted list of pegged orders should be sorted by entry time (i.e. when they were submitted OR last underwent a cancel/replace amend).

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +If the reference point moves to such a value that it would create an invalid order once the offset was applied, the pegged order is parked. As the reference price moves, any orders on the parked list
I guess this covers if the reference value does not exist (i.e. there is no best bid)?

2020-08-14 13:24 UTC, barnabee commented on 0000-pegged-orders.md
> +A sell pegged to Mid + 1 should take the mid as 102, and thus be at 103
I think we need acceptance criteria for this nuanced case

2020-08-18 12:50 UTC, peterbarrow commented on 0000-pegged-orders.md
> +| Persistent (GTC, GTT, etc.)	  | Sell  | >= 0    | > 0     | Not allowed |
Updated, thanks.

2020-08-18 13:04 UTC, peterbarrow commented on 0000-pegged-orders.md
> +
I liked your description above and have added it to the spec, thanks.

2020-08-18 13:08 UTC, peterbarrow commented on 0000-pegged-orders.md
> +- [ ] A markets ability to handle pegged orders is set at creation time and should be turned on by default.
Updated, thanks.

2020-08-18 13:14 UTC, peterbarrow commented on 0000-pegged-orders.md
> +- [ ] Parked orders are returned to the order book once continuous trading is resumed.
Updated, thanks.

2020-08-18 13:21 UTC, peterbarrow commented on 0000-pegged-orders.md
> +- [ ] Pegged orders are repriced when their reference price moves.
Added.

2020-08-18 13:21 UTC, peterbarrow commented on 0000-pegged-orders.md
> +- [ ] An expired pegged order is removed from the book and the pegged/parked slice.
Yes, added.

2020-08-18 13:52 UTC, peterbarrow commented on 0000-pegged-orders.md
> +**Offset:** This is a value added to the reference price. It can be negative.
Done, thanks,

2020-08-18 13:52 UTC, peterbarrow commented on 0000-pegged-orders.md
> +When a party submits a new pegged order, only a LIMIT order is accepted. The party also specifies the reference price to which the order will be priced along with an offset to apply to this price. Th
Removed old details.

2020-08-18 13:52 UTC, peterbarrow commented on 0000-pegged-orders.md
> +If the reference point moves to such a value that it would create an invalid order once the offset was applied, the pegged order is parked. As the reference price moves, any orders on the parked list
Added no best bid example.

2020-08-18 13:58 UTC, peterbarrow commented on 0000-pegged-orders.md
> +Whenever the reference price changes all the pegged orders that rely on it need to be repriced. We run through a time sorted list of all the pegged orders and remove each order from the book, recalcu
Done

2020-08-18 13:58 UTC, peterbarrow commented on 0000-pegged-orders.md
> +A sell pegged to Mid + 1 should take the mid as 102, and thus be at 103
Added and for tests too.

2020-08-18 14:21 UTC, barnabee approved these changes
Looks great! Thanks @peterbarrow

2020-08-19 12:13 UTC, merged