Create Event Queue Spec
vegaprotocol/specs pull request #271
Opened 2020-04-09 19:11 UTC by C0deMunk33

2020-04-09 22:19 UTC, C0deMunk33 commented
Now open for comment

2020-05-12 10:14 UTC, edd commented on specs/0000-event-queue.md
> +* Vega nodes accept events submitted to `Propagate_Event` and verifies them against valid Ethereum node
If a transaction is not verified (I.e. the data received via the event does not match the data received when looking up the transaction) we should explicitly error. `Event_Acceptance_Status` only provides a Boolean. Perhaps it could be an enum and contain an entry for events rejected for failing verification? I am not married to that solution, so anything that properly lets us represent that status is fine by me.

2020-05-12 10:17 UTC, edd requested changes
One change in the acceptance criteria, which is just around clarity. It might also be good to add some details on how what verification with Ethereum looks like. I assume it is:

- Talk to a local Ethereum API
- Talk to a remotely hosted Ethereum API
- Fetch transaction ID
- Check that balances and accounts involved match the event

What would cause it to fail this check? That’s what we need to capture. Otherwise this looks good to me.

2020-05-28 10:28 UTC, barnabee commented on specs/0000-event-queue.md
> +The first, `Get_Subscribed_Event_Sources`, returns a list of smart contract addresses that consensus has deemed valid as sources of events
Do we also need to be able to specify the specific event that will be subscribed to? (I think this will likely be useful for Ethereum based data sources aka oracles, for instance)

2020-05-28 10:28 UTC, barnabee commented on specs/0000-event-queue.md
> +enum Event_Types {
How will this scale when we add events for use as general data sourcing and other uses (control Vega accounts/position from Eth smart contract for instance)? Is this something we need to think about now?

2020-05-28 10:28 UTC, barnabee commented on specs/0000-event-queue.md
> +        string target_party_id = 6; // provided Vega public key of party to target the event to
This seems like it would be part of the event detail rather than the propagation request? (Some events in future won't have a target party)

2020-05-28 10:28 UTC, barnabee commented on specs/0000-event-queue.md
> +message Event_Propagation_Request {
Where is the event content sent?

2020-05-28 10:28 UTC, barnabee commented on specs/0000-event-queue.md
> +The second function, `Propagate_Event`, allows an event queue to send events raised on 3rd party blockchains (deposits, withdrawals, etc) through Vega consensus to ensure an event has been seen by th
Should clarify that Vega transactions and APIs must support:
- multiple blockchains as sources
- multiple source on any given blockchain (i.e. if we had two bridge contracts on the same Ethereum network for different asset types or multiple contracts being used as data sources/oracles)

2020-06-02 07:32 UTC, ashleyvega reviewed
I've made some cosmetic changes, and have no further comments on this high-level spec, though I'd like to see a tech spec with some implementation details at some stage.

2020-06-16 13:27 UTC, barnabee requested changes
Looking for an update on commetns I requested

2020-06-16 17:34 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +The first, `Get_Subscribed_Event_Sources`, returns a list of smart contract addresses that consensus has deemed valid as sources of events
indeed. I've updated this to say:
"returns a list of smart contract addresses and events that consensus has deemed as a valid source."

and the Vega node sim spits out the events as well as the contract addresses.

2020-06-16 18:20 UTC, C0deMunk33 reviewed
updated doc based on comments:
https://github.com/vegaprotocol/product/commit/e01a8759eeb38fecd8c55e0c77d96e3ca92cd75c

2020-06-16 18:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +message Event_Propagation_Request {
It's not. The node verifies the contents from the source. this request simply lets the node know that there is an event it should care about. Since there's no point in trusting the event queue for info like that, there's no real reason to send it along.

2020-06-16 18:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +        string target_party_id = 6; // provided Vega public key of party to target the event to
indeed. and something that would be verified by the node... I will remove this

2020-06-16 18:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +enum Event_Types {
I see this enum as an expandable list and, as each of these Event_Types are individually parsed, adding a new event type would be pretty straight forward.

2020-06-16 18:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +The second function, `Propagate_Event`, allows an event queue to send events raised on 3rd party blockchains (deposits, withdrawals, etc) through Vega consensus to ensure an event has been seen by th
noted and updated

2020-06-16 18:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +* Vega nodes accept events submitted to `Propagate_Event` and verifies them against valid Ethereum node
I agree. Having an explicit "rejected" status makes sense

2020-06-16 18:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +* Vega nodes accept events submitted to `Propagate_Event` and verifies them against valid Ethereum node
Added enum for this

2020-06-16 18:26 UTC, C0deMunk33 commented
> What would cause it to fail this check? That’s what we need to capture. Otherwise this looks good to me.

The only reason it would fail is if the event queue gives bad information to the node, but the node must verify all the info before accepting the event. I've added these verifications to the list.

2020-06-16 18:38 UTC, edd commented
@barnabee / @ashleyvega as previous reviewers, the ball is back in your court!

2020-06-17 09:23 UTC, ashleyvega approved these changes
LGTM

2020-06-19 09:36 UTC, barnabee commented on specs/0000-event-queue.md
> +enum Event_Types {
I guess I mean the address of a contract and name of the event may be added in a Vega transaction, i.e. 

```
ProposeMarket { 
    settlementEvent = EthereumEvent {
       contract: 0xblahblahblah
       event: "MyCustomEvent"
       path: "data.value"
    } 
}
```

Where that could even be referring to the Vega bridge contract and events it produces, or any other contract/event on the Ethereum chain. I was wondering what the event type/data model might look like in this case, and if the current design works to be expanded that way.

2020-06-19 09:38 UTC, barnabee commented on specs/0000-event-queue.md
> +message Event_Propagation_Request {
Again thinking about the oracle scenario really. Where the data payload from the tx/event is used for a calculation in Vega, how do you see that info getting into the core?

I have assumed this is via consensus in the same way it's agreed that the event occurred, but am wondering how that data would make it physically into the transaction, had asssumed that might be this event queue?

2020-06-19 09:40 UTC, barnabee reviewed
@C0deMunk33 I've left a couple of questions on your responses

2020-06-24 14:47 UTC, edd commented
@C0deMunk33 this is currently waiting on comments from you. I'll rebase it so it's mergeable again

2020-07-01 14:45 UTC, tamlyn10 commented
@C0deMunk33 can you give a status update on this spec writing task?

2020-07-16 18:59 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +message Event_Propagation_Request {
> @C0deMunk33 can you give a status update on this spec writing task?

I need to add the Oracle and market action Triggers thing, but for now the oracle spec takes precedent. @tamlyn10  This is effectivly on hold while some of the deeper/tertiary discussions happen.

2020-07-30 11:19 UTC, jeremyletang commented
Updated the code samples to show an example of how would the ERC20 events would work.
Rest of the spec looks good to me.

2020-07-30 11:20 UTC, jeremyletang approved these changes
@C0deMunk33 looks good, feel free to merge if you are done with this.

2020-08-03 19:20 UTC, C0deMunk33 commented on specs/0000-event-queue.md
> +message Event_Propagation_Request {
> Where the data payload from the tx/event is used for a calculation in Vega, how do you see that info getting into the core?

This is what @jeremyletang and I have worked out:

The event is picked up by the Event Queue and the tx_hash, block number, and transaction index are sent to the Vega API.

The Validator node takes those values to validate the exact events that core cares about on their local Ethereum node. 
The final values that end up on-chain come from the validators Ethereum node, not from the Event queue. Once a validator has accepted the event, gossip will cause all the other validators to validate that same event locally.  This allows Core to not have to waste cycles scanning for events as opposed to directly calling for the data and one Event Queue could potentially service more than one validator (maybe).

This general pattern holds for BTC and TBD chains.

2020-08-05 14:54 UTC, tamlyn10 commented
@C0deMunk33 can we merge this?

2020-08-10 11:29 UTC, merged