Cancel orders spec
vegaprotocol/specs pull request #301
Opened 2020-06-11 14:49 UTC by peterbarrow

Creation of the spec to define how the different types of cancels are performed in the core.

2020-06-11 15:32 UTC, jeremyletang commented
Looks pretty good to me as it is.
Just thinking of one thing, the margins are not re-calculated when an order is cancel, maybe it's worth mentionning in the specs?
Also they are not re-calculated as of now, where we can cancel only a single order at the time, would this be the same thing with the 2 others way of cancelling orders?

2020-06-11 16:22 UTC, edd reviewed
Found a pretty trivial edge case. Well, really, just something that isn’t explicitly forbidden. Also added some acceptance criteria, but they might be better off as tests

2020-06-11 16:22 UTC, edd commented on 0000-cancel-orders.md
> +- All orders for a given party across all marekts will be removed from the vega system when a cancel all orders message is sent
Typo: marekts

2020-06-11 16:22 UTC, edd commented on 0000-cancel-orders.md
> +
Can I mix and match these? Can I submit a partyID and an orderID and have an order cancelled whatever market it is on? (Not covered below either.) (I guess because it’s not in a list even further down, it’s not supported. This should be explicit.

2020-06-11 16:22 UTC, edd commented on 0000-cancel-orders.md
> +- Orders which are not currently on the orderbook but are being held `offline` due to being in auction should also be affected by cancels.
+ - A cancellation for a party that does not match the party on the order will be rejected
+ - A cancellation without a party ID will be rejected

2020-06-11 19:38 UTC, peterbarrow commented on 0000-cancel-orders.md
> +
It's not part of the current list but if you need it we can add it?

2020-06-11 19:40 UTC, peterbarrow commented on 0000-cancel-orders.md
> +- Orders which are not currently on the orderbook but are being held `offline` due to being in auction should also be affected by cancels.
Nice, added.

2020-06-16 14:07 UTC, barnabee requested changes
Ok to merge when comments addressed. No need to re-review on my part.

2020-06-16 14:07 UTC, barnabee commented on 0000-cancel-orders.md
> +The orderbook is looked up using the marketID and then we issue a cancel on that orderbook. Validation takes place to make sure the partyID supplied matches the partyID stored with the order. At most
When we say "party ID supplied" we should be explicit that it is the party ID in each case is owned by the signer of the transaction

2020-06-16 14:07 UTC, barnabee commented on 0000-cancel-orders.md
> +The orderbook is looked up using the marketID. We then scan through all the orders on that orderbook looking for orders which match the partyID. Depending on the number of orders in the orderbook, th
I would expect that a lookup table of party -> orders is needed based on what I've seen elsewhere.

2020-06-24 14:22 UTC, tamlyn10 commented
> Just thinking of one thing, the margins are not re-calculated when an order is cancel, maybe it's worth mentionning in the specs?
> Also they are not re-calculated as of now, where we can cancel only a single order at the time, would this be the same thing with the 2 others way of cancelling orders?

I think this is a really important point from @jeremyletang . If we batch cancel orders, and orders are all we have, then the margin requirement should immediately drop.

2020-06-30 12:59 UTC, peterbarrow commented on 0000-cancel-orders.md
> +The orderbook is looked up using the marketID and then we issue a cancel on that orderbook. Validation takes place to make sure the partyID supplied matches the partyID stored with the order. At most
I have added a statement to make this explicit.

2020-06-30 13:00 UTC, peterbarrow commented on 0000-cancel-orders.md
> +The orderbook is looked up using the marketID. We then scan through all the orders on that orderbook looking for orders which match the partyID. Depending on the number of orders in the orderbook, th
I have updated the spec to mention the per market partyID->order lookup table.

2020-06-30 13:26 UTC, edd approved these changes

2020-06-30 13:27 UTC, merged