Add open interest to market data
vegaprotocol/specs pull request #304
Opened 2020-06-15 15:57 UTC by campbellssource

Should open interest be added here? does it make sense as a core API?

2020-06-16 09:35 UTC, tamlyn10 requested changes
Suggested making definition of open interest more explicit

2020-06-16 09:35 UTC, tamlyn10 commented on specs/0021-market-data-spec.md
I'd make this slightly more explicit by saying 

The Open interest returns **the sum of the size** of all open positions where positions size is greater than 0.

2020-06-16 09:35 UTC, tamlyn10 commented on specs/0021-market-data-spec.md
> +  - **Open interest:** the sum of all positions above 0.
as per above comment

2020-06-16 09:41 UTC, tamlyn10 approved these changes
Needs a member of core team to approve.

2020-06-24 14:16 UTC, tamlyn10 commented
@jeremyletang are  you able to approve this?

2020-06-24 14:32 UTC, jeremyletang approved these changes

2020-06-24 14:38 UTC, merged