WIP: 318 spec for mm order type
vegaprotocol/specs pull request #335
Opened 2020-08-06 16:33 UTC by davidsiska-vega

@tamlyn10 This is where I got to with the MM order type. I think it's ready, at a high level. It may need an iteration with someone from engineering.

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
@davidsiska-vega what is the rationale for this being a **per-asset** network parameter?  Worth noting that if it is, we need to make sure that when a new asset is added on Vega that this network parameter is set. cc @barnabee

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
I think that [the way we last discussed this](https://docs.google.com/document/d/1V3YTlSOTU9Do_dmYhqtOqLO6lee_UeRHS_ikHoD7v4E/edit#heading=h.eypadvah1g9f) using [order books sheet](https://docs.google.com/spreadsheets/d/10kQxWBtJ5czoke4hDHEBqAV_dzo3OS1r-7VK_fVbtCc/edit#gid=364089557) from MM data sheet mucking spreadsheet we worked out that the market maker only specifies the distance from peg OR the fraction of liquidity commitment - i.e. not both. I will push a new commit with my proposed amendments.

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
<img width="517" alt="image" src="https://user-images.githubusercontent.com/16691275/89645317-727fa380-d8b1-11ea-9933-91e2875ac4b8.png">

Screenshot of example order...

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +1) the amount of liquidity to commit and how they want to distribute it (details follow below) and
If this is part of every MM order, fee change transaction (i.e. those actions all live together), we should have an option for them to leave it empty if they don't want to adjust their stake (and the same goes for fees). I'm not sure how this all plays out if they want to amend their orders and their stake together but the orders are malformed for whatever reason - do we still amend the stake? 

I know we've discussed MM transactions for orders vs stake vs fees but don't think we landed on whether to make 1tx handle all of them. @barnabee do you recall or have a preference?

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
One thing I'd note about above screenshot is that we were thinking that we were going to have 1 x transaction for buy orders and one for sell orders. I don't recall why - @barnabee may?

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
We should permit pegging to best bid / offer on either side. 

## Logic for missing peg price
This is an interesting one, because if a market has 0 open interest, then we don't want to be putting it into a liquidity auction if there is not BBOs. I would vote that in this case, we make all market making orders be the "least competitive but compliant" version and allow them to amend them from there (because they can specify using proportions at price levels).




Then, if there is no best bid or offer then liquidity monitoring should be triggered IMO... (this may require a

2020-08-07 12:51 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
As per above screenshot I think we were going to just normalise whatever numbers they provided.

2020-08-07 13:21 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +Market makers are allowed to decrease the liquidity commitment 3. subject to there being sufficient liquidity committed to the market so that we stay above `liquidity supplied >= c_2 x liquidity dema
Just realised we also need to add in auto-refreshing of market maker orders.

2020-08-07 13:48 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +1) the amount of liquidity to commit and how they want to distribute it (details follow below) and
OK just discovered this covered in this doc which I missed meeting around.. https://docs.google.com/document/d/15_gXcUorYmCgLnBquQxZ5Vx_amtemMCSOFqSoj73U_g/edit which covers off some of this.

2020-08-07 16:55 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +Market makers are allowed to decrease the liquidity commitment 3. subject to there being sufficient liquidity committed to the market so that we stay above `liquidity supplied >= c_2 x liquidity dema
Add in price monitoring threshold as price limit on either side?

2020-08-11 09:00 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +
Agree I think it should be a single network parameter. The asset units cancel out anyway I think as siskas are an asset-dependent unit?

2020-08-12 09:21 UTC, davidsiska-vega commented on specs/0000-market-making-order-type.md
> +
That's right the asset units cancel out do it can be a network param.

2020-08-12 09:24 UTC, davidsiska-vega commented on specs/0000-market-making-order-type.md
> +
To me that only worked with some implicit assumption and I forgot what it was. It seems deeply unnatural to me. 

Specifying what fraction of your liquidity at what distance remains the most natural to me which is why I wrote it up that way.

2020-08-12 10:49 UTC, tamlyn10 commented on specs/0000-market-making-order-type.md
> +
OK, since this has now moved over to the mm-mechanics spec, I will amend there.

2020-08-12 11:12 UTC, barnabee requested changes

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +- Is a batch order: allows simultaneously specifying multiple orders in one message/transaction
Perhaps we should leave the batch part to the MM mechanics spec and just specify what a valid single order row looks like so we don't get duplicative here?

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +- The order is always refreshed after trading (once the tx is processed so not refreshed before closeouts, etc.) based on the above requirements so that the full commitment is always supplied (spec c
NB: "refresh" occurs at the same tame as peg price updates

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +
@tamlyn10 it's either distance OR quantity plus a liquidity fraction IIRC, the other of price/quantity is calculated from the two provided values

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +# Example 1:
I can redo this how I see it

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +
I would like to stick to what we discussed and agreed, or reopen the discussion

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +The set of buy orders are applied to the resulting order price and volume.
Should be explicit. The calculation above is performed along with the peg re-pricing, whenever pegs are repriced as per pegged order spec

2020-08-12 11:12 UTC, barnabee commented on specs/0000-market-making-order-type.md
> +Market makers are always allowed to amend their orders by submitting a market maker network transaction with a set of revised orders (see [market making mechanics spec](./0000-mm-mechanics.md))
Note: futiure an individual order's params may be amendable by using it's order ID and an Amend tx

2020-09-02 10:42 UTC, peterbarrow approved these changes
This all makes sense to me but I would like to see all the questions already listed resolved before this is merged as they will impact the way the spec is used.

2020-09-02 14:34 UTC, merged