new mm mechanics
vegaprotocol/specs pull request #336
Opened 2020-08-10 10:32 UTC by tamlyn10

2020-08-10 15:26 UTC, witgaw reviewed
Looks ok to me, added some comments.

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +1. FEES: nominated fee amount (TODO: UNITS?). Default equals zero.
Maybe "FEES: nominated liquidity fee factor. Default equals zero." to keep it in line with the fees spec?

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +Invalid if:
I'd write "Invalid if any of the following is true:" to avoid confusion.

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +- [ ] If nominated fee amount is malformed or less than zero, the network should assign a default amount of zero.
Wouldn't it be safer to just reject the transaction in that case?

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +### How fee amounts are used
Shouldn't this section just refer https://github.com/vegaprotocol/product/pull/323?

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +When a commitment is made the liquidity commitment amount is transferred to the market making bond account (new account type, 1 per market) for the market.
Is this one account for all market maker bonds? If so, wouldn't keeping them separate make it easier to deal with slashes, commitment changes etc.?

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +1. Adjust the market maker's commitment amount to match the amount netted from the penalty: `actual-commitment-amount = previous-commitment-amount - market-maker-bond-penalty`
Shouldn't it be: `actual-commitment-amount = previous-commitment-amount - market-maker-bond-penalty - margin-shortfall`?

2020-08-10 15:26 UTC, witgaw commented on specs/0000-mm-mechanics.md
> +***Case:*** `margin-shortfall >= market-maker-commitment-amount - market-maker-bond-penalty`
Shouldn't it be "<=" ?

2020-08-11 08:55 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +- [ ] If nominated fee amount is malformed or less than zero, the network should assign a default amount of zero.
I think the show should go on.. their fee nomination is only one of many. If it is set to zero, traders just get cheap prices for a bit..

2020-08-11 08:56 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +### How fee amounts are used
yeah, I hadn't spotted that David had done that already, a later commit fixed it..

2020-08-11 08:57 UTC, barnabee requested changes

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] The participant has sufficient collateral in their general account to meet the size of their nominated commitment amount, as specified in the transaction.
Add and the margin required for their liquidity provision orders?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] The market is active
Or proposed, or pending (need to make clear you can commit during proposal period and after a proposed market is approved but before it's created)

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] The nominated fee amount is not less than zero.
Should we also have a global "MAX_LIQUIDITY_FEE" network parameter, which the bid must be <=?

I think maybe necessary to prevent attack where someone comes into a low liquidity market with a fee of 100% (or extremely high). Would assume noone would trade until someone else comes in but if I could force a liquidation then the MMs take all the value in fees.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] There are a set of valid buy and sell orders (see MM orders spec)
"valid buy and sell liquidity provision orders ..." might be better?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. ORDERS: a set of _buy orders_ and _sell orders_ to meet the market making obligation.
We should think about naming. Do we call this orders or something like "bid liquidity" and "offer liquidity"?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +    - [ ] Only the network may withdraw collateral from this account.
What does this mean. If I reduce my committment and it's accepted I can withdraw? If we consider that the network then I'd say increasing my commitment or creating a new one is also done by the network so only the network can transfer to or from the account. I think this is mostly unhelpful though as everything in the system can only be done by the network.

Suggest something like this instead: "a market maker can only transfer funds to or from this account by submitting a valid transaction to create, increase, or decrease their commitment to the market, which must be validated and pass all checks (e.g. including those around minimum liquidity commitment required, when trying to reduce commitment)"

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +    - [ ] Collateral withdrawn from this account may only  be transferred to either:
Add: the market maker's margin account, in the event that they fall below the maintenance level and have zero balance in their general account.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +The commitment transaction is also used to amend any aspect of their market making obligations.
We should clarify in this section that to end their commitment a MM must submit an accepted Commit Liquidity transaction with a commitment size of zero. We should also clarify that in this case it cannot contain any liquidity bids/offers and if accepted all their liquidity provision orders will be cancelled off the book and any bond returned, margin returned only if they now have no position/orders at all or if the margin now falls below the recalculated release level.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +## Market making network transaction
We should call the the `Commit Liquidity` transaction IMO

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +A participant may apply to amend their commitment amount by submitting a transaction for the market with a revised commitment amount.
Use name i.e. "by submitting a `Commit Liquidity` transaction"

If they are amending an existing commitment, the participant may omit / leave blank the orders section to use their existing orders (these will be scaled to the new commitment automatically) or provide a new valid set of bid and offer liquidity orders.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +A market maker can always increase their commitment amount as long as they have sufficient collateral in the settlement asset of the market to meet the new commitment amount.
and any margin increase for their revised orders

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +    - [ ] any other details contained within the new transaction is ignored by the network, i.e.
"the entire transaction is rejected, and any other details..."

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +`maximum-reduction-amount = max(1/siskas_to_bond_in_asset_X x (total-market-making-liquidity - (c_2 x liquidity-demand-estimate)), 0)`
I think we should calculate the c1 and c2 levels and expose these on APIs (say, the market data API, or a new market making data API). Will be pretty fundamental to know this.

I also think we should maybe calculate and mostly talk about these in terms of _base asset commitment (bond) requirement_ rather than siskas — only a slight reaarrangement I know, but I think will aid education and understanding. We can calculate and show siskas but at the moment siskas aren't a universal unit, they're a different unit per asset and until we find a way to talk about that (i.e. normalise to siskas/USD or something?) I think they're perhaps going to be confusing.

Not sure this changes this section BTW, I just thought about it here and didn't want to lose. Will delete if it's covered elswhere.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +`actual-reduction-amount = min (abs(proposed-reduction-amount), maximum-reduction-amount)`
I had assumed we'd reject a reduction that was too large outright and wait for a valid new commitment to be entered. It seems cleaner and easier to reason about to me that if a `Commit Liquidity` transaction isn't rejected then my liquidity commitment is equal to the commitment I requested.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] the difference between their previous commitment and new commitment is transferred back to their general account, i.e.
Unless the current balance of their bond is below par i.e. they have been penalised + bond has been used as margin. So the difference between their current bond balance and new commitment is transferred rather than diff to their previous commitment.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +When `actual-reduction-amount = 0`:
Add the entire `Commit Liquidity` transaction is rejected.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +The network will amend the commitment amount if they market maker's obligations have not been met (see section below)
Is this right? I think the amount committed ought to remain the same and the _actual amount supplied / bond balance_ would be what's amended, and if they realise a general account increase (deposite, settlement, reduce other commitment, etc.) the actual bond would be topped back up to the commitment amount.

Unless we discussed this and agreed something else that I forgot?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] If nominated fee amount is malformed or less than zero, the network should assign a default amount of zero.
Yes. Always reject if we can't do what the TX asks for IMO.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +- [ ] A nominated fee amount must be greater than or equal to zero. The units of the fee amount are a percentage. A number greater than 1 is permitted.
Per above comment too, should we have a MAX set by network param?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +Market makers may amend their nominated fee amount by submitting a market maker transaction to the network with a new fee amount. If the fee amount is valid, this new amount is used. Otherwise, the n
See above

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +In a market  maker proposal transaction the participant must submit a valid set of orders, comprised of:
"liquidity provision orders"

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. A set of valid buy orders
"A set of buy orders which must be valid pegged orders of type liquidity provision order"

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. A set of valid sell orders
"A set of sell orders which must be valid pegged orders of type liquidity provision order"

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +Market maker orders are a special order type described in the [market maker order spec](). Validity is also defined in that spec.
Per discussion on Slack - probably rename market maker orders to luqidity provision orders or whatever we decide.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +A market maker can amend their orders by providing a new set of orders in the market maker network transaction. If the amended orders are invalid, the previous set of orders will be retained.
`Commit Liquidity` transaction

If amending orders only, the commtiment amount, fee bid can be omitted.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +	- [ ] Market makers are not required to place orders during an auction period.
Not sure this is worded quite right. A market maker with a valid commitment should be required to have a valid set of liqudity provision orders at all times as part of their commitment. These will just be parked in an auction so they will not be on the book, and a market maker is not required to place any _additional_ orders during the auction or participate in the auction.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +If at any point in time, the market maker has insufficient capital to meet their margin requirements arising from their market making orders and open positions, the network will utilise their market
Does this happen before or after the usual cancellation of [other] orders, position resolution of open position. Assume before, but would we want to cancel non-liquidity-providing orders first?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +Let `market-maker-bond-penalty = bond-fine-parameter * margin-shortfall` be the amount of commitment that has been slashed, where `bond-fine-parameter` is a network parameter and the `margin-shortfal
Probably prefer the term penalty to fine? i.e. "liquidity penalty factor"?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +Note: in future versions, the degree to which a market maker has met their obligation may be measured over a rolling time period (specified by a network parameter, initially set to 24 hours) and calc
I'm not sure how this would work. Are you saying that perevious breaches/breach history would be used when a new or further breach occurred to decide how much penalty to apply?

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +The network will consider the market maker to be distressed and immediately place it into position resolution.
I think we would be better off saying after the penalty is applied we transfer the shortfall (or as much of it as available) from the bond account to the margin (so it can be used in MTM or taken to insurance pool, otherwise it just sits in bond account) and then things proceed as normal i.e. if it is still in shortfall then position resolution will occur. 

Should avoid special cases like if X then immediately go to position resolution where we can reuse exisitng flow and logic, for simplicity/consistency.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +***Case:*** `margin-shortfall >= market-maker-commitment-amount - market-maker-bond-penalty`
Per my above comment, I think this is the only case

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. Confiscate an amount equal to `market-maker-bond-penalty` from the market's _market maker bond account_ and add it to the insurance pool.
Transfer penalty amount (or everything is less) to the insurance pool. I'd avoid terms like confiscate here in the spec. It's just a transfer.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. Transfer an amount equal to `margin-shortfall` from the market's _market maker bond account_ into the market maker's margin account.
Continue as normal. With margin management - we should amend collateral search to search first general account then their bond account for the market.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. Adjust the market maker's commitment amount to match the amount netted from the penalty: `actual-commitment-amount = previous-commitment-amount - market-maker-bond-penalty`
As aboce (and I think what @witgaw is getting at) — I don't think we amend their commitment amount but record the actual level of commitment they are making.

2020-08-11 08:57 UTC, barnabee commented on specs/0000-mm-mechanics.md
> +1. List of all market makers and their commitment sizes and their “equity-like share” for each market (https://github.com/vegaprotocol/product/pull/323/files)
Add their actual amount provided (current bond balance)

2020-08-11 08:58 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +When a commitment is made the liquidity commitment amount is transferred to the market making bond account (new account type, 1 per market) for the market.
I'm actually OK to use account management up to the engineers.. originally I'd specced separate accounts, then Barney's doc said one. I don't mind.

2020-08-11 08:59 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +1. Adjust the market maker's commitment amount to match the amount netted from the penalty: `actual-commitment-amount = previous-commitment-amount - market-maker-bond-penalty`
Actually last we discussed this the idea was to keep the commitment the same.. to give them a chance to top back up their margin.. this does remind me, however, that we don't talk about this account periodically doing a "search" to top itself back up. mmm.

2020-08-11 09:00 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +***Case:*** `margin-shortfall >= market-maker-commitment-amount - market-maker-bond-penalty`
why?

2020-08-11 09:01 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +- [ ] The participant has sufficient collateral in their general account to meet the size of their nominated commitment amount, as specified in the transaction.
yeah, I wasn't clear on how the ordering of this would work. we could accept the commitment and then go through the normal flow of using their bond account for margin if needed.

2020-08-11 09:01 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +- [ ] The market is active
When we have a market lifecycle spec this will be easier to define! (on your list I believe ;-)

2020-08-11 09:02 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +- [ ] The market is active
(but I'll add your wording meanwhile)

2020-08-11 11:16 UTC, edd commented on specs/0000-mm-mechanics.md
> +* the measure of liquidity that a market maker actually supplies is the ACTUAL STAKE referred to as the SUPPLIED liquidity (measured in siskas).
**question (blocking)** I think there's a copy and paste error here - remove ACTUAL STAKE?

2020-08-11 11:18 UTC, edd commented on specs/0000-mm-mechanics.md
> +1. COMMITMENT AMOUNT: liquidity commitment amount
**thought (non-blocking)** It's obvious with some thought, but I think it's worth clarifying that this is in the settlement asset for the market.

2020-08-11 11:21 UTC, edd commented on specs/0000-mm-mechanics.md
> +1. FEES: nominated [liquidity fee factor](./0029-fees.md).
**thought (non-blocking)** This is cleared up later, but as someone who understands fees this surprised me. I assumed they'd earn the fee that is configured for the market. It might be worth making this a link to the fees section below to help get people to the answers they might have on this field.

2020-08-11 11:26 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +* the measure of liquidity that a market maker actually supplies is the ACTUAL STAKE referred to as the SUPPLIED liquidity (measured in siskas).
fixed..

2020-08-11 11:26 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +1. COMMITMENT AMOUNT: liquidity commitment amount
haha.. i just deleted that as that doesn't need to be specified in the transaction. I'll make a note to make that explicit.

2020-08-11 12:12 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +1. FEES: nominated [liquidity fee factor](./0029-fees.md).
I don't know how to link to a line.. but, I also think that it's more important it links to the fee spec?

2020-08-11 12:12 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +A market maker can always increase their commitment amount as long as they have sufficient collateral in the settlement asset of the market to meet the new commitment amount.
done

2020-08-11 12:12 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +    - [ ] any other details contained within the new transaction is ignored by the network, i.e.
Unbelievably, I don't recall if we got resolution on this in the end?

2020-08-11 12:12 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +`maximum-reduction-amount = max(1/siskas_to_bond_in_asset_X x (total-market-making-liquidity - (c_2 x liquidity-demand-estimate)), 0)`
I don't understand this sentence:  _I also think we should maybe calculate and mostly talk about these in terms of base asset commitment (bond) requirement rather than siskas — only a slight reaarrangement I know, but I think will aid education and understanding._

2020-08-11 13:01 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +    - [ ] Only the network may withdraw collateral from this account.
amended

2020-08-11 13:02 UTC, tamlyn10 commented on specs/0000-mm-mechanics.md
> +    - [ ] Collateral withdrawn from this account may only  be transferred to either:
added

2020-10-02 14:53 UTC, merged