WIP: Update Market Lifecycle
vegaprotocol/specs pull request #375
Opened 2020-10-06 06:15 UTC by tamlyn10

@davidsiska-vega @barnabee @witgaw  would you guys be able to review this WIP PR to see if you agree with my interpretation of market lifecycle stuff?

2020-10-06 06:16 UTC, tamlyn10 commented
I'll keep adding to it, but table and the figure are the main things I want to get agreement on initially.

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds should not be started (e.g. if the market is nearing the end of its open period / active trading).
Is the `min_auction_length` a network parameter?

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0026-auctions.md
> +A newly created market will start in auction mode, then once the auction comes to an end the market will switch to the default trading mode, and will stay like until there's a need for it to go in au
"stay like until" feels like there's a word missing.

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0026-auctions.md
> +The auction should not exit unless at least one trade an ending criteria for the opening auction rather than restart it, we already extend if liquidity criteria aren’t met and I think these things wi
"The auction should not exit unless at least one trade an ending criteria" perhaps missing "matching" or a similar word?

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0026-auctions.md
> +The auction should not exit unless at least one trade an ending criteria for the opening auction rather than restart it, we already extend if liquidity criteria aren’t met and I think these things wi
I am not sure how "extend if liquidity criteria aren’t met" would work. 

In my imagination it was: end opening auction. 
If there are no trades resulting, restart the auction for the same period. 
If the opening auction results in open interest and stake is zero start a liquidity auction.

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0026-auctions.md
> +Please note auction should only ever be exited if doing so wouldn't trigger entry triggers of any other auction types defined for the market (e.g. price monitoring auction, liquidity monitoring aucti
Why? Let's say I have a price monitoring auction, it ends, uncrosses and results in a price that would trigger price monitoring. Then I start this new price monitoring auction.

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0043-market-lifecycle.md
> +<br>
Markdown is not HTML so instead of <br> you can just use newline.

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
Where /  how is the proposer minimum defined?

2020-10-07 14:12 UTC, davidsiska-vega commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
From risk point of view: the gap between "trading terminated" and "settlement time" should always be lower than \tau. Otherwise it's very likely that margin balances won't cover settlement.

2020-10-07 16:07 UTC, tamlyn10 commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds should not be started (e.g. if the market is nearing the end of its open period / active trading).
Good question.. @barnabee ?

2020-10-07 18:05 UTC, tamlyn10 commented on specs/0026-auctions.md
> +The auction should not exit unless at least one trade an ending criteria for the opening auction rather than restart it, we already extend if liquidity criteria aren’t met and I think these things wi
Gracious, I had pasted some Slack or Git chat and forgot to edit properly.. let me fix and have  you review!

2020-10-07 18:21 UTC, tamlyn10 commented on specs/0026-auctions.md
> +Please note auction should only ever be exited if doing so wouldn't trigger entry triggers of any other auction types defined for the market (e.g. price monitoring auction, liquidity monitoring aucti
yeah.. agree..  please see revised edits

2020-10-07 18:22 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
it's not yet.. line 16 talks of it as a future feature.. it will be a network param in the future I guess..

2020-10-07 18:26 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
@davidsiska-vega  fact, I'm not sure why this is a future feature.. should we not require a minimum of 1 ccy-siska of liquidity? cc @barnabee

2020-10-07 18:29 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
well, actually no.. it's the gap between "trading terminated"  and "product expiry" that's important..  settlement can happen days after - the calc of what is owed is about expiry. However, expiry is actually defined on the oracle.. hence me excluding it from this lifecycle description.

I think that maybe we have to restrict that "trading terminated" market parameter to make sure that `oracle-data-time` - `trading-termination-time` >= tau

2020-10-08 07:57 UTC, davidsiska-vega commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
The special market making order type rounds up when it comes to volume (or it should anyway). So any non-zero stake implies non-zero liquidity commitment which implies non-zero volume on the book. So strictly speaking, I don't see a need for minimum even in the future. This is from the point of view how the liquidity mechanics work. 

There may be a "spam protection" angle or an "DOS attack vector" angle. Say that there are 10^5 liquidity providers in a market each with a miniscule stake - does the core grind to a halt cycling through these and distributing fees?

From this point of view I would say that we should have network-wide-per-asset parameters that say what a minimum commitment is in each asset which would be say roughly USD 1000. 

And I agree - it doesn't have to be future feature, let's discuss and spec what we agree now.

2020-10-08 07:59 UTC, davidsiska-vega commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
@tamlyn10 I see and I agree with you. Please add this restriction and mark as resolved.

2020-10-08 08:01 UTC, davidsiska-vega approved these changes

2020-10-08 08:14 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
Yeah, my point is that at the moment you can create markets without submitting a liquidity transaction (because that feature hasn't commenced implementation yet). I think we need to make sure that as part of implementing liquidity, we have this specced properly (and so far it's not, anywhere).  For example, we've not decided whether they need to submit the 2 tx's separately but within x time of eachother, or reference the 1 in the other, or allow them to embedd a liquidity submission tx in with the governance proposal (that would have my vote).

2020-10-09 12:28 UTC, barnabee requested changes
Think this is looking really good. Few small things but nothing major.

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds should not be started (e.g. if the market is nearing the end of its open period / active trading).
Yes, its purpose is to prevent auction calls that are too short given the network latency/granularity, so should be some multiple of the worst case expected block time at some confidence level, which I think is best maintained by governance voting. We should update and be explicit here that it's a network param, possibly explain why it exists too.

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +A newly created market will start in auction mode, then once the auction comes to an end, the market will switch to the default trading mode, and will stay like that until there's a need for it to go
Think this should now be something like:

>  A market that has passed the governance vote and is in Pending state will be in an auction period. The auction will never uncross while the market is in a Pending state, and only does so when it moves to another state (i.e. becomes Active, see Market Lifecycle for criteria for transiiton out of Pending state).

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +The enactment period of the governance proposal refers to the time between the proposal being accepted and active trading commencing, therefore inclusive of the opening auction period (see [market li
Maybe ref. Pending state here too

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +where `calculated_end_time` is the call period of the auction.
Worth noting this may be ∞ (e.g. for liquidity monitoring)

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +If the market is going to expire the auction must end and uncross at or before expiry.
Current term here seems to be "Trading Terminated" rather then expired, so I think this should be updated, but see comment below in Market Lifecycle spec.

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds should not be started.
Should cover here and/or in Market Lifecycle (maybe just Market Lifecycle, thinking about it) what happens if this occurs in a pending/new market (i.e. because we're that close to the end date of the market).

2020-10-09 12:28 UTC, barnabee commented on specs/0026-auctions.md
> +- there has been at least one trade on the market
Should we be adding somewhere that during an auction we should not accept an order from a party that is crossed with another order from the same party, to "prevent"[1] wash trading. 

[1] well, barely, as I can use sybils, but it at least puts a cost on it and I end up with positions and margins and have to deal with other people/prices in the market afterwards, plus if I close out straight away we're back in an auction if OI = 0, as I understand it from recent discussions.

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +All markets have a "trading mode" (plus its coniguration) as part of the [market framework](0001-market-framework.md). When a market is Active (i.e. it is open for trading), it will be in a trading p
probably should be:

> for the life of the market _unless changed by governance_

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +| State              | New LP         | Trading    | Entry                                                     | Exit
I think we should add a trading mode column per the 3 bullets above under the "Market status" heading, and it should be either "N/A", "Opening auction", "Exceptional auction" (or similar), or "Normal trading".

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +| Rejected          |   Yes          |  No        | Governance vote fails/loses                               | N/A
New LP = No

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +| Closed            |   Yes          |  No        | Governance vote (to close)                                | Governance vote (to reopen)
New LP = No

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +| Closed            |   Yes          |  No        | Governance vote (to close)                                | Governance vote (to reopen)
I also don't think reopen should be allowed. IMO it should be a new proposal, it's simpler and it ensure it get's properly reviewed like any other market opening.

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +| Settled           |   No           |  No        | Settlement event concludes                                | N/A
I'm wondering whether we need to differentiate between **settled** and **closed** — I suspect not, and if that's the case let's drop either one of them or pick something new?

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +If a "new market" governance proposal is successful the market is opened into a "pending" state, where the price determination method is an auction period with a callPeriod that ends at the enactment
Do we want to make it clear that this is a state for _any market that is due to be created_ and that currently this means by governance proposal, but in future there may be automated market creations? e.g. a series of markets, creation from an oracle/data source, etc.

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +  - Market change governance vote approves closure/cancellation of market → Cancelled
Cancelled is not described or in the table

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> -- No market data (price, etc.) is emitted, no positions exist on the market, and no risk management occurs
I had mentioned this for clarity in my draft, maybe worth adding here?

> Only market data related to auctions (indicative uncrossing price/volume, etc.) are emitted, no positions exist on the market, and no risk management occurs

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +Once the enactment date is reached the market becomes Active. This status indicates it is trading via it's normally configured trading mode according to the market framework (continuous trading, freq
it's → its

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Conditions specified in [price monitoring](./0032-price-monitoring.md) and [liquidity monitoring](./0035-liquidity-monitoring.md) are met for the market to exit the suspended status back to Active.
Above you used this to specify exiting an auction, which I quite like, would it also work here?

> the usual [ending of auction checks pass](./0026-auctions.md)

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +Once the enactment date is reached the market becomes Active. This status indicates it is trading via it's normally configured trading mode according to the market framework (continuous trading, freq
expired → something about trading terminated

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Trading termination is triggered (defined by a market parameter) → Trading Terminated
> by a product trigger (for futures, if the trading termination date, set by a market parameter, is reached)

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Conditions specified in [price monitoring](./0032-price-monitoring.md) and [liquidity monitoring](./0035-liquidity-monitoring.md) are met for the market to exit the suspended status back to Active.
Same comment as above re: using this instead, it means only one place to change if we add more checks:

> the usual [ending of auction checks pass](./0026-auctions.md)

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
> A market that has a finite lifetime and thus a defined final settlement terminates trading at some point prior to, or at, the final settlement driven by the product.

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
We may not always have a way to know that `oracle-data-time - trading-termination-time >= tau` as it may just not be published data, even if it is, you're trusting the proposer at proposal time.

So if we add a check for this we'll basically be saying "enter a time and we'll validate that it's reasonable, but the governance voters have to validate that the oracle feed supplies a data point for the time the proposer said" whereas without the validation it will be "governance voters have to check they believe oracle feed specified will supply a data point that meets the tau criteria"… not hugely different.

There may still be value in the slightly more explicit version, but just wanted to be clear that we cannot get certainty on this until after the fact, and are trsuting the governance process either way.

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Triggered by market parameter OR defined on the product.
It's just triggered by the product. The futures product uses the market parameter to effect the trigger, and this can be noted, though, i.e. something like this wording again:

> by a product trigger (for futures, if the trading termination date, set by a market parameter, is reached)

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- No market data are emitted
Is this right? (I know I wrote it...) 

Wondering if it should be something like: 

> A single set of market data may be emitted for the final settlement data (e.g. settlement mark price), after which no market data are emitted.

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- No risk management of price/liquidity monitoring occurs
of → or

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +Once the required data to calculate the settlement cashflows is available for an Expired market, these cashflows are calcualted and applied to all traders with an open position (settlement). The posi
calcualted → calculated

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +Once the required data to calculate the settlement cashflows is available for an Expired market, these cashflows are calcualted and applied to all traders with an open position (settlement). The posi
Probably should link section of insurance pool spec on funds redistribution

2020-10-09 12:28 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Market is over and removed.
Probably should link section of insurance pool spec on funds redistribution

2020-10-09 12:29 UTC, barnabee commented
I can update the diagram in OmniGraffle if you need me to @tamlyn10 - pls just let me know what to change when ready, if it's not obvious.

2020-10-09 14:53 UTC, tamlyn10 commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds should not be started (e.g. if the market is nearing the end of its open period / active trading).
ok, thanks, will include, and resolve this.

2020-10-09 14:57 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
@barnabee have you had any thoughts on this?

2020-10-09 15:33 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
@barnabee to clarify, you mean that the `oracle-data-time` represents the product expiry (i.e. not the time the data is expected to be delivered).. I'm sure you do, just writing for future selves.

So yes, agree that this is all encapsulated in the governance vote, anyway. But I do think that there is value in making this explicit, if just for the teaching it provides of what margins actually are.

2020-10-09 15:45 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Triggered by market parameter OR defined on the product.
OK, so you think that this should always be a parameter that is set in reference to the oracle data date? I have a slightly odd feeling about that, not sure why... perhaps because in future, there may be products that settle against more that one underlying.

2020-10-09 15:49 UTC, tamlyn10 commented
@barnabee I'll take you up on offer to edit diagram - let's do as final thing once we have agreement on above points.

2020-10-12 18:56 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +| Settled           |   No           |  No        | Settlement event concludes                                | N/A
Mmm... I think it's useful to know if a market has been settled by expiry rather than closed and then arbitrarily (or at least unspecced) settlement / unwind of positions procedure.

2020-10-12 19:03 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +  - Market change governance vote approves closure/cancellation of market → Cancelled
changed to closed

2020-10-12 19:08 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> -- No market data (price, etc.) is emitted, no positions exist on the market, and no risk management occurs
no positions exist on the market, and no risk management occurs doesn't seem correct to me. If it's a price monitoring auction positions do exist and orders are charged margin.. as per the 0019 margin spec.

2020-10-12 19:12 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Conditions specified in [price monitoring](./0032-price-monitoring.md) and [liquidity monitoring](./0035-liquidity-monitoring.md) are met for the market to exit the suspended status back to Active.
i encorporated it..

2020-10-12 19:15 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Conditions specified in [price monitoring](./0032-price-monitoring.md) and [liquidity monitoring](./0035-liquidity-monitoring.md) are met for the market to exit the suspended status back to Active.
there isn't just one place tho'.. is there? or should there be.. mmmm

2020-10-13 11:55 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
I think I'd be happy with something like a per-asset) minimum proposer liquidity stake_ as a network parameter, to provide a barrier to entry that means we only accept sufficiently "serious" proposals to create markets and supplied liquidity.

Re @davidsiska-vega's DOS angle… good point, I think we should have a per-asset absolute _minimum liquidity stake_ for all providers too, which would be needed to prevents 1000s of 0.000000000000000001 ETH stakers screwing up the system.

2020-10-13 12:00 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
So @barnabee this would form part of the validation of the proposal itself?

2020-10-13 12:01 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +- Triggered by market parameter OR defined on the product.
I think I made this edit anyway.. so will resolve this.

2020-10-13 12:17 UTC, barnabee commented on specs/0043-market-lifecycle.md
> -- No market data (price, etc.) is emitted, no positions exist on the market, and no risk management occurs
Isn't this describing the Pending state? (Genuine question - the Github view is full of comments and diffs that makes it hard to see the whole doc.)

If so then it can't be in price monitoring.

2020-10-13 12:17 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Conditions specified in [price monitoring](./0032-price-monitoring.md) and [liquidity monitoring](./0035-liquidity-monitoring.md) are met for the market to exit the suspended status back to Active.
There used to be: https://github.com/vegaprotocol/product/pull/375/files#diff-9993b28fdf1ab342cc13c1be8a941439355efb8054883586f1db86da001c94acL83

I don't really see why we wouldn't want there to be? It makes sense to me that there would be a standard set of conditions to enter and exit "Suspended" mode, and that these would be enumerated and refernced in a single place (either in auction or market lifecycle spec), so we only have one place to update if we add new monitoring capabilities.

2020-10-13 12:17 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Triggered by market parameter OR defined on the product.
No, I think this is **never** triggered directly by a parameter. It is triggered by code in the product implementation, it just so happens that for futures the code references a product parameter (which all sit in the market framework). I don't think this would relate to the oracle, it's a parameter that the product needs to decide whether to trigger the state change.

2020-10-13 12:19 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> -- No market data (price, etc.) is emitted, no positions exist on the market, and no risk management occurs
OMG I find Github soooo difficult to do this review. I often don't know where in the file the snippet sits! If it is pending, I agree with you and will change if so!

2020-10-13 12:29 UTC, barnabee commented on specs/0026-auctions.md
> +Please note auction should only ever be exited if doing so wouldn't trigger entry triggers of any other auction types defined for the market (e.g. price monitoring auction, liquidity monitoring aucti
I don't think this is correct. the [price monitoring spec.](https://github.com/vegaprotocol/product/blob/master/specs/0032-price-monitoring.md) states explicitly that:

- price monitoring is extended if further levels are breached (i.e. you'd never uncross price monitoring then go back into another price monitoring auction).
- "price monitoring is meant to stop large market movements that are not "real" from occuring, rather than just detect them after the fact. To that end, it is necessary to pre-process every transaction and check if it triggers the price monitoring action" — that is, we would not process an uncrossing and generate trades if they would trigger price monitoring.

So I think it's correct that auctions shouldn't be exited if price monitoring would be triggered, but should be extended with the call duration defined as per the price monitoring spec.

2020-10-13 12:30 UTC, edd commented on specs/0026-auctions.md
> +- there has been at least one trade on the market
Also: Please clarify how an opening auction acts if it has not had a single trade. I know the high level @the auction happens again' - presumably for the same period?

2020-10-13 13:37 UTC, campbellssource commented on specs/0026-auctions.md
> +- there has been at least one trade on the market
And what if it never ends? Is there a max amount of time or attempts before it becomes a failed market? What happens to peoples liquidity if/when it fails?

2020-10-13 13:44 UTC, tamlyn10 commented on specs/0026-auctions.md
> +- there has been at least one trade on the market
Seriously.. Github???? Where do you hide these comments.. 

@edd yes, we need to clarify that - it's not explicit. I'm going to suggest that after the enactmentDate, any single trade could be the trigger to make it exit (subject to other exit conditions such as liquidity).

@campbellssource good question. LP's may add and remove their stake over this period (unclear if the proposor can) and yes, with no trade, the market may just remain in a pending state forever. However, I'd expect it to be closed by governance vote (this is unspecced).

2020-10-16 11:07 UTC, barnabee commented on specs/0026-auctions.md
> +- there has been at least one trade on the market
We _could_ have a _max opening auction extension_ network param so that market creation/opening is "cancelled" if it doesn't get created within reasonable time of the planned creation. This could be infinite/extremely large to mimic the current functionality but having it would allow community experimentation and engagement through governance.

2020-10-16 11:07 UTC, barnabee commented on specs/0043-market-lifecycle.md
> -- No market data (price, etc.) is emitted, no positions exist on the market, and no risk management occurs
Yep... I actually can't tell either. GH is infuriating!

2020-10-16 11:07 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +- Liquidity providers can make, change, or exit commitments (proposer can't commit below proposer minimum)
Minimum proposer liquidity stake = proposal validation
Minimum liquidity stake = new/amended commitment validation

2020-10-16 11:16 UTC, barnabee reviewed
Final comments as far as I can tell

2020-10-26 15:06 UTC, witgaw commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds (network parameter) should not be started (e.g. if the market is nearing the end of its open period / active trading). This is to prev
What if the auction length is less than `min_auction_length`, but there's still plenty of time until end of open period? Shouldn't we just run the auction until it's at least ``min_auction_length` long? 

Otherwise one can never be sure if price monitoring triggers will work as that network parameter can be changed later on effectively rendering them inactive.

2020-10-27 07:54 UTC, tamlyn10 commented
Adding a link to the google sheet from yesterday's meeting where we should all contribute any changes we notice that will need implementation work. This will help with prioritisation. https://docs.google.com/spreadsheets/d/1XVFcvuiEvYcU2JPKxIsYZp1InRABSP0koWSM_RR8I-Y/edit?usp=sharing

2020-10-27 11:46 UTC, barnabee commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds (network parameter) should not be started (e.g. if the market is nearing the end of its open period / active trading). This is to prev
Hmm yes I think for price monitoring it should be the price monitoring spec that specificies the end time as `max(now + configured_period_length, now + min_auction_length)` and then this auction logic does not need to contain a specific case for price monitoring and can remain generic.

2020-10-27 11:47 UTC, tamlyn10 commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds (network parameter) should not be started (e.g. if the market is nearing the end of its open period / active trading). This is to prev
@witgaw could you make any changes that arise from this or anything else you come across in the PR?

2020-10-27 11:50 UTC, tamlyn10 commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
I'm just reviewing this and I think that I'm not going to make any market creation / market framework spec changes for this. I'll copy the thinking into an analysis ticket to not lose it.

2020-10-27 12:14 UTC, barnabee commented on specs/0043-market-lifecycle.md
> +A market terminates trading at some point prior to, or at, the settlement of the product. Markets in this state accept no trading but retain the positions and margin balances that were in place after
Tamlyn's ticket is here FYI https://github.com/vegaprotocol/product/issues/392

2020-10-29 16:18 UTC, tamlyn10 commented
I will put in a meeting for Monday 2nd November. Core to read through the spec prior. Tamlyn to make further updates as in spreadsheet.

2020-11-03 10:36 UTC, witgaw commented on specs/0026-auctions.md
> +Any auction that would be less than `min_auction_length` seconds (network parameter) should not be started (e.g. if the market is nearing the end of its open period / active trading). This is to prev
Sure, will do.

2021-01-04 15:25 UTC, jeremyletang commented on specs/0026-auctions.md
> +All auctions have a `min_auction_length`, which defines the minimum `call period` for an auction.
Where / how is this defined?
At the proposal stage as part of the proposal? Should we reject a proposal with a min_auction_length shorter than the network parameter?

If the min_auction_length network parameter change after the market is started what's supposed to happen and the min_auction_lenght of the market become shorter than the network parameter?

Also if not mistaken price monitoring auction duration is calculated dynamically, so what should happen if the duration calculated is shorted than the network parameter?

2021-01-04 15:25 UTC, jeremyletang commented on specs/0026-auctions.md
> +Auction periods may be ended which an uncrossing and the creation of any resulting trades due to:
which -> with?

2021-01-04 15:25 UTC, jeremyletang commented on specs/0026-auctions.md
> +If the auction period specifies and end time and the market is about to transition to the "Trading Terminated" state before the auction end time is reached, then the auction must end immediately befo
I'm not sure to understand this whole sentence?
I can see only 1 reference to Trading Terminated in this file, does that mean, that if the market is about to reach expiry before an auction end time is reached, we need to get back to the normal trading mode before we expire?

2021-01-04 15:25 UTC, jeremyletang commented on specs/0028-governance.md
> +1. a liquidity provision commitment via LP commitment data structure, specifying stake amount, fee bid, plus buy and sell shapes [see lp-mechanics](0044-lp-mechanics.md).
So this is literally required as part of the proposal right?

if the liquidity provision commitment submitted is not enough / the party does not have enough funds the proposal should be rejected?

2021-01-04 15:25 UTC, jeremyletang commented on specs/0028-governance.md
> +Note that additional requirements on validity of the governance proposal may in future include a requirement that the proposer also commits to [supply liquidity to the market](./0044-lp-mechanics.md)
Well how does that work with my previous comment, this seems to imply that the things at line 158 are not required as of now?

2021-01-04 15:25 UTC, jeremyletang commented on specs/0026-auctions.md
> +If the auction period specifies and end time and the market is about to transition to the "Trading Terminated" state before the auction end time is reached, then the auction must end immediately befo
I see it's in the list of market states..

2021-01-04 15:25 UTC, jeremyletang commented
Would it be possible to commit this file: specs/0029-market-lifecycle-flow-diagram.graffle in a format that can be shown in the github UI?

2021-01-05 11:57 UTC, barnabee commented on specs/0026-auctions.md
> +All auctions have a `min_auction_length`, which defines the minimum `call period` for an auction.
* min auction length is a network param and not provided on the proposal
* a proposal should be rejected if it would require an auction shorter min_auction_length
* for price/liquidity monitoring, etc. the auction must last for at least the min_auction_length and therefore we can avoid checking other conditions until that length is reached
* if the parameter is changed it needs to be re-applied to any current auctions, this means that shortening it could trigger an auction ending

I've added these in the latest commit to the spec

2021-01-05 12:04 UTC, barnabee commented on specs/0026-auctions.md
> +Auction periods may be ended which an uncrossing and the creation of any resulting trades due to:
fixed

2021-01-05 12:07 UTC, barnabee commented on specs/0026-auctions.md
> +If the auction period specifies and end time and the market is about to transition to the "Trading Terminated" state before the auction end time is reached, then the auction must end immediately befo
updated the spec, the auction uncrosses immediately in this case and does not go back to normal trading

2021-01-05 12:18 UTC, barnabee commented on specs/0028-governance.md
> +1. a liquidity provision commitment via LP commitment data structure, specifying stake amount, fee bid, plus buy and sell shapes [see lp-mechanics](0044-lp-mechanics.md).
yes, updated spec

2021-01-05 12:18 UTC, barnabee commented on specs/0028-governance.md
> +Note that additional requirements on validity of the governance proposal may in future include a requirement that the proposer also commits to [supply liquidity to the market](./0044-lp-mechanics.md)
removed, this note was from a previous version of the spec when we hadn't specced liqudiity yet

2021-01-05 12:29 UTC, merged