WIP trusted party oracles
vegaprotocol/specs pull request #421
Opened 2020-11-23 11:29 UTC by tamlyn10

2020-11-23 12:52 UTC, jeremyletang commented on specs/trusted-party-oracles.md
> +### What happens when Oracle Data doesn't arrive?
Is this a market parameter? Or defined per market?

2020-11-23 12:53 UTC, jeremyletang commented on specs/trusted-party-oracles.md
> +### What happens when Oracle Data doesn't arrive?
Should we also default to this if no oracle is provided for a market? Or is it mandatory to provide one?

2020-11-23 12:55 UTC, jeremyletang commented on specs/trusted-party-oracles.md
> +	    sourcePubkeys: ["A VEGA_PUBKEY_HERE"],
would we want some maybe slightly more complex datastructure to specify the pubkeys?
I'm thinking of something like metada, just string this would allow maybe to add information about the pubkey, just so people may know/help identify what's the entity behind the pubkey providing the oracle data?

2020-11-23 12:56 UTC, jeremyletang commented on specs/trusted-party-oracles.md
> +A invalid Trusted Party Oracle (TPO) is:
Would we want something as well like: The pubkey needs to have some funds deposited on vega, like governacne token or something?

2020-11-23 12:56 UTC, jeremyletang commented on specs/trusted-party-oracles.md
> +A invalid Trusted Party Oracle (TPO) is:
OK this is answered line 114.

2020-11-25 14:08 UTC, barnabee requested changes

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +Trusted Party Oracles are the name for the Minimum Viable Data Source. Rather than implement the entire [Data Sourcing spec](https://github.com/vegaprotocol/product/pull/289), we are going to add a V
This is not _instead of_ it is the first part and a key building block of. Point is this shouldn't be considered throwaway or something that is a non-strategic part of the protocol and I think this sentence may give that impression.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +Trusted Party Oracles are the name for the Minimum Viable Data Source. Rather than implement the entire [Data Sourcing spec](https://github.com/vegaprotocol/product/pull/289), we are going to add a V
> add a Vega transaction that represents a data result, which can be used when [settling a market at expiry](./0004-settlement-at-instrument-expiry.md)

I would reword to say this spec adds:

- a transaction that allows arbitrary signed data to be submitted to the Vega blockchain (creating a stream of data that can be identified by a data source definition)
- a way to define a data source that reads specific data from such a stream (and discards other data)
- the ability to define the settlement oracle for a market to use such data source definition (NB: there can and will be other places the EXACT SAME features described above will be used, but for now, it is just settlement data)

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +_Trusted Party Oracles_ refer to a type of oracle that may be specified on a market. This data source consists of nominating one or more Vega participants (pubKeys) who are permitted to submit and at
They can submit data at any time. Not all of it will be used, and a single stream of submissions could be used by many markets.

For example, the Coinbase oracle API provides a stream of signed messages for many different crypto prices, so for one source we could be receiving many messages that aren't used by any given market, for instance if someone set a bot to submit the latest Coinbase oracle signed messages to the Vega chain once per hour. (Hence the "filters" section in the definition to determine which messages to look at.)

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +Data is supplied through a transaction being posted directly on the Vega network that is signed by one (or more) of the valid signers for that specific data source.
One or more transactions

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +When a market is proposed, the settlement data source is specified as part of specifying the instrument. This data source may be a TPO. Note, a TPO may submit data that is used by multiple markets. E
Per above, different field or a differerent message, selected from the stream of messages by the filters

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +        signedMessage: {
We should move this "signedMessage:…" part out of the Futures section and have a section which is "defining a TPO data source", then this section should make clear that in "settlementPriceSource" for Futures we should accept **any valid data source definition** (the obvious next one will be to allow the same filters/field spec to be run on Vega's own [Market Data](https://github.com/vegaprotocol/product/blob/master/specs/0021-market-data-spec.md) stream.

The Futures bit really should be in the spec for the Futures product, actually.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +	        { "field": "mark_time", "equals": "31/12/20" }
We'll probably need to add types to the filters, and to support string, number, and at least one (possibly several) date/time formats. We should check if we need to support number-as-string here too (or decide if we would quietly accept a number-as-string in a numeric field...

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +SubmitOracleData {
We should probably support this key/value IMO but I also want to make sure that we support the [Open Oracle](https://github.com/compound-finance/open-oracle) message format used by the messages in [Coinbase oracle](https://docs.pro.coinbase.com/#oracle) and others - I am not 100% sure of the encoding format, it may be JSON in which case we might need to flatten json keys/array indices to paths like `key.1.subkey` or it might be that it's encoding specifically to their `kind, timestamp, key, value` format in which case those become the keys.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +1. If the _mark_time_ of the transaction does not equal the _mark time_ specified on the Product (e.g. `settlementPriceSource.filters.field.mark_time` ) then this data is not valid for use in the set
If any of filters do not match (or are of the wrong type) the message is ignored and not passed as a valid data point to whatever defined the source.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +1. If the _mark_time_ of the transaction does not equal the _mark time_ specified on the Product (e.g. `settlementPriceSource.filters.field.mark_time` ) then this data is not valid for use in the set
Also if the specified field is of the wrong type, the data is not passed as a valid data point, but this should create a warning event i.e. "data event passed filter but format of XX field doesn't match data soruce definition" as the format may have changed and it could be necessary for a [market, in the case of settlement] governance action to change the data source.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +A future feature requirement - any participant may propose a change to a market's oracle data source via on-chain governance. This includes:
This is not really part of this spec. The inclusion of a valid data source definition in the market proposal/market framework should be defined by the spec for the Futures product and normal rules apply re: governance actions.

So to be clear: this would be expected to be addressed as part of market change governance actions.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +1. Proposing a change to the oracle values, such as a change in the sourcePubkeys or filters.
The entire data source definition should be replaceable in a change. Includes the above and any other valid changes.

2020-11-25 14:08 UTC, barnabee commented on specs/trusted-party-oracles.md
> +For the minimum requirement, a (network parameter) timeout should be implemented, whereby if the oracle price data doesn't arrive, the market is settled by another means. See [settlement at expiry sp
Not sure about this... I think the minimum would be to simply do nothing until something arrives and allow a market param change to specify a new oracle. In future voting to "close" the market instead may also be possible.

2020-11-25 14:25 UTC, tamlyn10 commented on specs/trusted-party-oracles.md
> +A future feature requirement - any participant may propose a change to a market's oracle data source via on-chain governance. This includes:
Makes sense

2020-11-25 14:37 UTC, barnabee commented on specs/trusted-party-oracles.md
> +    - Identified by its public key
Needs to cover more of the spec

2021-01-10 16:24 UTC, barnabee commented
~Closing, rebased branch into https://github.com/vegaprotocol/product/pull/289~

2021-01-10 16:24 UTC, closed without merging

2021-01-12 14:46 UTC, barnabee commented
Data source/oracles now here: https://github.com/vegaprotocol/product/pull/450