Shift peg prices when outside the valid price range
vegaprotocol/specs pull request #422
Opened 2020-11-23 12:01 UTC by witgaw

Add the bit saying that if the price for a given peg is outside the valid price range as implied by the price monitoring module then it should get shifted "in" so that it's at the last valid tick for that side of the order book.

Closes #412

2021-01-20 15:59 UTC, tamlyn10 commented
@barnabee just to check this is as per agreed and then merge..

2021-01-22 14:34 UTC, barnabee requested changes
One update to be explicit about the valid price otherwise looks good

2021-01-22 14:34 UTC, barnabee commented on specs/0038-liquidity-provision-order-type.md
> +Note: if the resulting price for any of the entries in the buy / sell shape is outside the valid price range as provided by the price monitoring module it should get shifted to the valid price that's
I think we should be explicit how to calculate the price here or make sure we are referring a specific part of the price monitoring spec. and linking there.

2021-01-26 13:41 UTC, tamlyn10 commented on specs/0038-liquidity-provision-order-type.md
> +Note: if the resulting price for any of the entries in the buy / sell shape is outside the valid price range as provided by the price monitoring module it should get shifted to the valid price that's
@witgaw do you mind addressing this comment then merging?

2021-01-27 11:09 UTC, witgaw commented on specs/0038-liquidity-provision-order-type.md
> +Note: if the resulting price for any of the entries in the buy / sell shape is outside the valid price range as provided by the price monitoring module it should get shifted to the valid price that's
Clarified now I believe:

> Note: if the resulting price for any of the entries in the buy / sell shape is outside the valid price range as provided by the price monitoring module (the min/max price that would not trigger the price monitoring auction per triggers configured in the market, see [price monitoring](./0032-price-monitoring.md#view-from-quant-library-side) spec for details) it should get shifted to the valid price that's furthest away from the mid for the given order-book side.

Will merge tomorrow morning if I don't hear any objections before.

2021-02-03 15:51 UTC, witgaw commented on specs/0038-liquidity-provision-order-type.md
> +Note: if the resulting price for any of the entries in the buy / sell shape is outside the valid price range as provided by the price monitoring module it should get shifted to the valid price that's
Now merging for real!

2021-02-03 15:51 UTC, witgaw commented
Merging as I wasn't challenged on this for a week.

2021-02-03 15:51 UTC, merged