Allow modifying of existing orders (#426)
vegaprotocol/specs pull request #427
Opened 2020-11-24 12:11 UTC by peterbarrow

Any orders that were already placed that are not part of the LP shape can be cancelled and amended like a normal order.

2020-11-25 15:37 UTC, tamlyn10 commented on specs/0038-liquidity-provision-order-type.md
> +Existing orders that are used as part of the liquidity commitment can be cancelled and amended just like normal orders on the book which are not part of liquidity provisioning.
I think we should be clear this is about limit orders..

2020-11-25 15:37 UTC, tamlyn10 requested changes
one minor comment - if fixed then good to merge

2020-11-25 16:21 UTC, peterbarrow commented on specs/0038-liquidity-provision-order-type.md
> +Existing orders that are used as part of the liquidity commitment can be cancelled and amended just like normal orders on the book which are not part of liquidity provisioning.
I understood it to mean all persistent orders which includes limit and pegged orders?

2020-11-25 16:46 UTC, barnabee commented on specs/0038-liquidity-provision-order-type.md
> +Existing orders that are used as part of the liquidity commitment can be cancelled and amended just like normal orders on the book which are not part of liquidity provisioning.
@peterbarrow yeah, I think that's correct, the only orders that can't be amended are those that are derived from the liquidity commitment, as far as I know (i.e. this should include any order that would normally be amendable)

2020-11-25 17:16 UTC, tamlyn10 commented on specs/0038-liquidity-provision-order-type.md
> +Existing orders that are used as part of the liquidity commitment can be cancelled and amended just like normal orders on the book which are not part of liquidity provisioning.
ah i thought it referred to this question.... https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1606217324042000

2021-01-20 15:59 UTC, davidsiska-vega commented
@peterbarrow I've not seen this one when dealing with the #426 so I ended up creating a different pull request. Decide which one you want to keep and delete the other one (the other one being https://github.com/vegaprotocol/product/pull/459 ). 

D

2021-01-20 18:36 UTC, peterbarrow commented
Has been superseded, closing.

2021-01-20 18:36 UTC, closed without merging