WIP Training wheels (aka safety limits) for Vega
vegaprotocol/specs pull request #467
Opened 2021-01-27 17:12 UTC by davidsiska-vega

This  will eventually be a spec for what limits we want to be able to place on Vega and how these will interact with token holders voting on things. @C0deMunk33 .

2021-01-27 21:16 UTC, C0deMunk33 commented
In general, the less on-chain (eth-side) the better. 

Notes:
"should we create limits in core that can be circumvented with multiple accounts? Yes! It sends a message."
- agreed, we can't prevent sybil, but we can let people know that if you want to sybil, you have to make a conscious decision to risk more of your money.

"how do we compare across assets? Maximum deposit is a multiple of minimum stake per asset (already in asset in framework) or constant per asset - for the life of the vega chain, changeable via governance"
- this should not be changable by governance for WWN, constant per asset makes most sense. I can code this into the contract and we can hard-set this before launch.

"maximum deposit per asset from any given Ethereum address and to any Vega address"
- I will add this to the post-audit smart contract itself.

"withdrawals amount and timing? e.g. withdrawals only allowed 1 week after last settlement?"
- we have withdrawal expiry built in already, just set that in governance

"withdrawals over certain amount during a time period subject to Vega token holder vote?"
- I will have a hard time coding this, but if CORE delays issuing of the signature bundle, this can be easily accomplished. 

"do we need a lever to stop all withdrawls are automatically moved to DAO?"
- if we want this, I can wire in a BIG RED BUTTON to halt withdrawals that requires multisigControl

"here is BIG RED BUTTON on the ethereum side which can move all locked assets to the DAO"
- no? this doesn't exist yet and all it would be able to do is kill despoits/withdrawals. It can't move anything. (the asset pool exists because of this problem). if we do this, we need some sort of emergency "disable multisig control" that is triggered by... someone... 

"insurance pool money after all settlement and Vega net shutdown will go into DAO."
- this will require CORE to write a withdrawal order to it's target.

2021-01-28 14:25 UTC, barnabee commented
> * this should not be changable by governance for WWN, constant per asset makes most sense. I can code this into the contract and we can hard-set this before launch.

WWN will be "launched" multiple times, and assets will be added. I think it makes sense to make this part of the allow-listing of a new asset, even if not _changeable_ by governance initially.

2021-01-28 14:27 UTC, barnabee commented
> * no? this doesn't exist yet and all it would be able to do is kill despoits/withdrawals. It can't move anything. (the asset < pool exists because of this problem). if we do this, we need some sort of emergency "disable multisig control" that is triggered by... someone...

this could all be triggered by the validaotrs so I think it could use multisig control

2021-02-03 19:46 UTC, davidsiska-vega commented
@tamlyn10 - ready for review... (and @jeremyletang  if you're interested).

2021-02-25 13:57 UTC, tamlyn10 approved these changes

2021-02-25 14:10 UTC, peterbarrow approved these changes

2021-02-25 16:30 UTC, edd requested changes
I don't think this is ready to be merged. It should be detailed enough that we can plan an implementation off it, and it isn't there yet.

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- how do we compare across assets? Maximum deposit is a multiple of minimum stake per asset (already in asset in framework) or constant per asset - for the life of the vega chain, changeable via gove
**question (blocking)**: Decision required. Is it? What multiple?

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +### Questions:
```suggestion
```

Remove header

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +
```suggestion
- users can circumvent limits via sybil attack. This is known and accepted.
```

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- should we create limits that can be circumvented with Sybil accounts? Yes! It sends a message.
Remove, accept above change

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- maximum deposit per asset from any given Ethereum address and to any Vega address. The limits per asset should be configurable via governance. Limits should be part of whitelisting a new asset.
**question (blocking)**: Where should this block happen. Governance param suggests in Vega, but if it's in Vega then the deposit has already happened to the smart contract, and thus needs to be returned

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
**question (blocking)**: Needs more detail. What does this look like in practice? @C0deMunk33 ?

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- orderly withdrawal of funds at the end of life of Vega network is in (link to TODO limited network life spec). This will cover insurance pool money too.
**nitpick (blocking)**: Please add a link before merging.

2021-02-25 16:30 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- orderly withdrawal of funds at the end of life of Vega network is in (link to TODO limited network life spec). This will cover insurance pool money too.
**question (blocking)**: Please document a workflow of how this works. The end of a network life to me is when validators stop producing blocks, at which point obviously they can't multisig anything. This needs some design thought.

2021-02-25 16:54 UTC, barnabee commented
Thanks @edd, I'll make some updates and be sure to get your _seal_ of approval before merging

2021-02-26 11:36 UTC, Vegaklaus commented on non-protocol-specs/0002-training-wheels.md
> +- should we create limits that can be circumvented with Sybil accounts? Yes! It sends a message.
I can generalise the text I put on Discord about Sybil attacks for that case so we can put something in an FAQ on why we accepted this

2021-03-01 09:14 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- maximum deposit per asset from any given Ethereum address and to any Vega address. The limits per asset should be configurable via governance. Limits should be part of whitelisting a new asset.
Expected to be in bridge. My understanding is supported assets are added via governance but this also triggers an Ethereum "allowlisting", I expect the parameter would be passed as part of the same governance.

2021-03-01 09:25 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- how do we compare across assets? Maximum deposit is a multiple of minimum stake per asset (already in asset in framework) or constant per asset - for the life of the vega chain, changeable via gove
Will clarify and reword

2021-03-01 09:38 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
@edd I am trying to work out wha'ts missing here, will try splitting this to the wording suggested below but please clarify what you'd like to see here if this doesn't do it, or I'll add this when I make updates:

- each withdrawal will be subject to some (possibly 0) amount of delay between the withdrawal bundle being created and the withdrawal being committed to the Vega (and possible Ethereum) chain(s) and therefore publicly broadcast and "known" to anyone who cares to see it
- the delay will be definable by threshold based on withdrawal amount as a multiple of the deposit limit (so it is cross-asset and thresholds need to be defined once for the whole system), so larger withdrawals can be subject to longer delays
- during that delay period multisigcontrol will be able to prevent a withdrawal succeeding via an Ethereum transaction

2021-03-01 09:40 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- orderly withdrawal of funds at the end of life of Vega network is in (link to TODO limited network life spec). This will cover insurance pool money too.
Spec does not exist yet, do you want us to delay merging (once issues are fixed) until it does?

2021-03-01 09:41 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- orderly withdrawal of funds at the end of life of Vega network is in (link to TODO limited network life spec). This will cover insurance pool money too.
The point of that comment is that this documentation is not in the scope of this spec. Does not seem like the other spec should be blocking this one merging to me, as the functionality described herein has no dependency on this, it's just a helpful note.

2021-03-01 11:06 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- orderly withdrawal of funds at the end of life of Vega network is in (link to TODO limited network life spec). This will cover insurance pool money too.
I would prefer that, but I'll live without

2021-03-01 11:10 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
That's most of the detail that is required. For point 1, the multisig process has no interaction with ethereum, so point 3 becomes more interesting - what is broadcast on Ethereum that blocks the withdrawal. If it's a withdrawal ID, that can't be known before the bundle is broadcast on the Vega event bus, as otherwise there's no way for the person sending this TX to know the ID. So I guess it would have to be a Vega address to ban from withdrawals? That's my first thought, but it's easily dismissable. 

tldr more thought on point three please. Where does that TX happen and what data does it contain and who, in practice, broadcasts it?

2021-03-01 12:03 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
> the multisig process has no interaction with ethereum

I'm not sure I understand this... the multisig process creates a tx that will be processed on Ethereum so it can interact with it by including a parameter like `withdrawalCreatedTimestamp` that can be queried by the bridge to determine whether to allow the withdrawal bundle to be processed in a block.

My understanding is it's possible for humans operating the validator nodes to manually sign ad-hoc transactions. This would be done by a quorum of validators signing something like a call to `blockWithdrawal(tx_bundle_id)`. Then you can refuse to accept the bundle on Ethereum before the delay expires, or ever, if its ID was blocked.

Some of these things feel a bit like implementation details rather than specs though?

What we want is: 
- The delay between generation of the withdrawal bundle which others can know about and the funds leaving the bridge pool
- The ability of a manual quorum-of-validator signed transaction submitted on Ethereum before that delay expires to prevent the withdrawal happening

2021-03-01 12:17 UTC, edd commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
# My summary of what I think you have proposed
That helps somewhat. So a withdrawal request is created by the user, which will be visible and have an ID, but the multisig bundle will not start being created until `timeout` is reached, at which point it will be signed - even if it is going to be blocked.

Then we're going to add a new function to the bridge smart contract** that allows a multisig bundle to block a withdrawal by the vega event ID. This signature bundle gathering process will be started manually by a Vega validator runer, and submitted to Ethereum manually by a Vega validator runner

* This specifically relates to your point here that uses the phrases 'committed' and 'known', which it's worth being clear about because they are not specific:
> each withdrawal will be subject to some (possibly 0) amount of delay between the withdrawal bundle being created and the withdrawal being committed to the Vega (and possible Ethereum) chain(s) and therefore publicly broadcast and "known" to anyone who cares to see it

# Alternative
If the delay is added, then can't we simply make the WithdrawalBlock action a Vega-only TX that doesn't interact with the smart contract? That way we don't need to add a new function to the solidity, or require validators to spend gas.

2021-03-01 14:32 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
> That helps somewhat. So a withdrawal request is created by the user, which will be visible and have an ID, but the multisig bundle will not start being created until timeout is reached, at which point it will be signed - even if it is going to be blocked.

No I think validators can sign the bundle immediately. It can be checked by the bridge contract when the withdrawer tries to submit it to Ethereum and if it's too early the Ethereum transaction would be rejected (and I think not incur any fees) and they would submit again later. I'm pretty sure it is fine to sign it before you know if it will be blocked and before the delay is up.

We want to ensure blocks work even if someone has managed to bring down the Vega chain, so the delay/block needs to be enforced on Ethereum. Only time a validator (or us!) incurs fees is if there's a need to block something.

2021-03-01 14:34 UTC, barnabee commented on non-protocol-specs/0002-training-wheels.md
> +- withdrawals over certain amount during a defined time period will be delayed (e.g. 72 hours). During that delay period the Vega validators can blacklist the bundle to prevent a suspicious withdrawa
@C0deMunk33 please correct me if any of what I'm stating/proposing here differs from what you think we discussed

2021-03-01 16:04 UTC, C0deMunk33 commented
So here's what I distilled from all that, we want:
1. Delayed withdrawal - configurable delay before contract accepts withdrawal order
2. Multisig controlled halt order that can be issued any time before withdrawal/expiry

2021-03-02 07:39 UTC, barnabee commented
> So here's what I distilled from all that, we want:
> 
>     1. Delayed withdrawal - configurable delay before contract accepts withdrawal order
> 
>     2. Multisig controlled halt order that can be issued any time before withdrawal/expiry

@edd in reply to [this thread on Slack](https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1614621212079400?thread_ts=1614614672.077900&cid=CAHA5EX0F):

Yes, that's what we want. It is quite close to the original text, are you happy for me to change the wording to this? Are there other details you would like to see included from the discussion above?

2021-03-02 07:41 UTC, barnabee commented
@C0deMunk33 can you confirm my [assumptions here](https://github.com/vegaprotocol/specs/pull/467#discussion_r584757389) are ok?

2021-03-02 08:50 UTC, edd commented
> It is quite close to the original text, are you happy for me to change the wording to this? Are there other details you would like to see included from the discussion above?

Yeah it’s quite close, so yes I think it’s the clarifications from above that need to get included. 

# Delayed withdrawal
Withdrawals above a configured size (see below) will be forced to wait for a configured delay. This is being introduced to protect us from end users abusing a previously unknown loophole and running off with all the collateral. The logic lives mostly in the bridge smart contract.

The delay period defaults to 72 hours in order to give validators a chance to skim all the pending deposits. If any are suspicious looking, they can be blacklisted by withdrawal ID

## Multisign halt order
1. A validator identifies a withdrawal bundle they would like to blacklist
2. Validator submits a new Vega TX - `multisigWithdrawalhalt`
3. Validators gather multisig bundle
4. Anyone submits the multisigned halt signature bundle to the smart contract
5. If the withdrawal ID is submitted after the configured wait, it will be rejected
 
## User Workflow
1. A user requests a withdrawal from the system
1. As it does now, Vega will sign a multisig bundle to pass to the user, for submission to the smart contract on Ethereum
1. When the user submits the multisig bundle to the bridge contract:
    1. Submission of the multisig bundle to the bridge contract before `delayed_time`, but below `delay_deposit_value` will be accepted and processed as before
    1. Submission of the multisig bundle to the bridge contract before `delayed_time`, but at or above  will be rejected
    1. Submission of the multisig bundle to the bridge contract at or after `delayed_time`:
        1. Unless explicitly blacklisted, will be accepted

## Limitations
- A user could submit multiple withdrawals just below the configured limit. As users pay the gas costs on Ethereum, this would be expensive, and so we’re not protecting against that
- This will be annoying for people who have genuinely traded well and want to exit the system. Documentation will clarify that this limit will go away.

## Configuration

There are no new network parameters for the system, as the delay and value limits are defined in the bridge smart contract. The smart contract will need to allow: 
- delayed_deposit_value - the value (defined once for all assets, representing the tokens)* above which withdrawals will be delayed
- delay_time - the amount of time (defined in seconds) that must have passed before the bridge will process a withdrawal request


* This is unclear. I mean not defined in dollars/gbp. It’s early 🤷 

> > So here's what I distilled from all that, we want:
> > ```
> > 1. Delayed withdrawal - configurable delay before contract accepts withdrawal order
> > 
> > 2. Multisig controlled halt order that can be issued any time before withdrawal/expiry
> > ```
> 
> @edd in reply to [this thread on Slack](https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1614621212079400?thread_ts=1614614672.077900&cid=CAHA5EX0F):
> 
> Yes, that's what we want. It is quite close to the original text, are you happy for me to change the wording to this? Are there other details you would like to see included from the discussion above?

2021-03-02 16:21 UTC, barnabee commented
I am significantly rewriting/improving this spec and have come across a question that might result in a change (simplification). I discussed this briefly with @tamlyn10 earlier but would like everyone's input here… 

With the delay-plus-block transaction option, given that:

- If there is an issue that's possibly been exploited it could be exploited in other withdrawals (both in progress and not-yet-made), including those that are beneath the threshold size, so any issue being investigated would likely require stopping other transactions or a significant ovehread of checking them all; and
- As the delay is finite (and would be kept as short as reasonably practical), any serious investigation (and possible fix) would quite likely require employing the 🛑 BIG RED STOP BUTTON 🛑 until the investigation is complete and if necessary, a fix is deployed.

SO, given these points, do we need to build the withdrawal halt feature at all or would the delay plus the ability to temporarily stop all withdrawals and deposits be just as good (or even preferable)?

@C0deMunk33 @davidsiska-vega @edd @tamlyn10

2021-03-02 16:33 UTC, edd commented
> SO, given these points, do we need to build the withdrawal halt feature at all or would the delay plus the ability to temporarily stop all withdrawals and deposits be just as good (or even preferable)?
 
I prefer this approach as it's simpler. I assume that the 'Allow Deposits or not' flag is still set with a multisig bundle on the smart contract, rather than being implemented in the nodes?

2021-03-02 16:41 UTC, barnabee commented
> I prefer this approach as it's simpler. I assume that the 'Allow Deposits or not' flag is still set with a multisig bundle on the smart contract, rather than being implemented in the nodes?

I believe it would implemented using the fact that we have a simple asset pool contract that has a designated "asset controller" aka bridge contract that accepts bridge deposits and executes withdrawals. Multisig control has the ability to change this controller contract (including setting it to no contract), and so the "stop deposits and withdrawals" flag is in reality _using an action that is already built_ to remove/restore the bridge's ability to interact with the asset pool.

So as I understand it, we'd simplify twice by not building the "halt individual withdrawal" logic and also not needing any new features for stopping withdrawals that don't exist already. We just need to build the delays, for the withdrawal limits, in that case. 

@C0deMunk33 please correct me if this is wrong

2021-03-12 11:57 UTC, edd approved these changes
New version is nice and clear, thanks

2021-03-12 12:01 UTC, barnabee commented
Merging, further changes can be addressed w/ new issues

2021-03-12 12:01 UTC, merged