Update to liquidity auctions
vegaprotocol/specs pull request #483
Opened 2021-02-09 15:53 UTC by davidsiska-vega

Closes #482

2021-02-10 09:39 UTC, barnabee approved these changes
Pushed some tweaks, approved

2021-02-10 12:38 UTC, barnabee approved these changes
Approve

2021-02-10 13:43 UTC, witgaw requested changes
Overall looks good to me, just two comments.

2021-02-10 13:43 UTC, witgaw commented on specs/0035-liquidity-monitoring.md
> +With `target_liquidity` and `present_firm_liquidity` defined as above we exit if
Isn't `present_firm_liquidity` redundant now?

2021-02-10 13:43 UTC, witgaw commented on specs/0035-liquidity-monitoring.md
> +The auction is triggered when
I'd start the paragraph with this and move "Here 0 < c<sub>1</sub> < 1 (...)" below it, reads more easily to me that way.

2021-02-10 14:26 UTC, witgaw commented on specs/0035-liquidity-monitoring.md
> +Similarly to [price monitoring](0032-price-monitoring.md), the auction should be triggered pre-emptively. That is, the transaction that would have triggered the liquidity auction should be [re-]proce
This is comment is not related to other changes in this PR, but came up during my work on this and thought we could take care of it here too:

The pre-emptive bit should exclude LP closeouts, right? As in we want to closeout anyway (because the guy just can't afford margin) and switch to auction. Or are we just assuming that a closeout isn't an explicit transaction and hence it's ok?

2021-02-10 14:41 UTC, barnabee commented on specs/0035-liquidity-monitoring.md
> +Similarly to [price monitoring](0032-price-monitoring.md), the auction should be triggered pre-emptively. That is, the transaction that would have triggered the liquidity auction should be [re-]proce
I think that'scorrect, yeah. If the price move is real I think we probably shouldn't reject/delay until the auction the whole transaction that caused the price move, which we'd do if pre-empting. It seem probably right that we fill the order or whatever and then closeout the LP if needed and enter a liquidity auction. It's definitely not the only way we could handle it but it feels right....

Main alternative is we detect the LP would be closed out and enter an auction. But this seems bad because from the PoV of the auction there's no reason to be there and we end up creating a situation where some prices become less "valid" / not hittable due to LPs margin position, which I don't like.

cc @tamlyn10 @davidsiska-vega

2021-02-10 15:25 UTC, davidsiska-vega commented
@barnabee @witgaw I have another question: we say 
``` 
supplied_stake is the sum the stake amounts committed by all the LPs in the market (see LP mechanics).
```
but in fact isn't the relevant amount the LPs bond account balance (so the sum of all the LPs bond account balances)? The fact that an LP "committed" to something but then they don't have the margin / bond balance to keep commitment doesn't seem right to me.

2021-02-10 15:32 UTC, barnabee commented
> @barnabee @witgaw I have another question: we say
> 
> ```
> supplied_stake is the sum the stake amounts committed by all the LPs in the market (see LP mechanics).
> ```
> 
> but in fact isn't the relevant amount the LPs bond account balance (so the sum of all the LPs bond account balances)? The fact that an LP "committed" to something but then they don't have the margin / bond balance to keep commitment doesn't seem right to me.

No because we put **all** the orders for their commitment on the book even if their balance is lower because of penalties IIRC. They are either supplying their full commitment or nothing cos they got closed out. As in:

> 4. If the liquidity provider's orders or positions were closed out, and they are therefore no longer supplying the liquidity implied by their Commitment: In this case the liqudity provider's Commitment size is set to zero and they are no longer a liquidity provider for fee/reward purposes, and their commitment can no longer be counted towards the supplied liquidity in the market. (From a Core perspective, it is as if the liquidity provider has exited their commitment entirely and they no longer need to be tracked as an LP.)

Also we removed the definition of `supplied stake` from LP mechanics.

2021-02-10 17:03 UTC, davidsiska-vega commented on specs/0035-liquidity-monitoring.md
> +Similarly to [price monitoring](0032-price-monitoring.md), the auction should be triggered pre-emptively. That is, the transaction that would have triggered the liquidity auction should be [re-]proce
I think all close-outs (LPs and other parties) should happen if there is volume on the book and only then should we enter an auction.

2021-02-10 17:04 UTC, davidsiska-vega commented on specs/0035-liquidity-monitoring.md
> +Similarly to [price monitoring](0032-price-monitoring.md), the auction should be triggered pre-emptively. That is, the transaction that would have triggered the liquidity auction should be [re-]proce
If we think the specs need clarifying I suggest a separate issue because it will impact both price monitoring and liquidity monitoring and is separate  to issue #483.

2021-02-11 11:59 UTC, witgaw commented on specs/0035-liquidity-monitoring.md
> +Similarly to [price monitoring](0032-price-monitoring.md), the auction should be triggered pre-emptively. That is, the transaction that would have triggered the liquidity auction should be [re-]proce
OK, thanks for clarifying. I'll create a separate update to the spec to cover that.

2021-02-11 11:59 UTC, witgaw approved these changes
Looks great now, thanks for incorporating my suggestions.

2021-02-11 13:06 UTC, merged