WIP: On-Chain Treasury - trading rewards
vegaprotocol/specs pull request #517
Opened 2021-03-31 14:28 UTC by tamlyn10

Closes #504

2021-03-31 14:52 UTC, davidsiska-vega commented
@davidsiska-vega after it's ready.

2021-05-12 13:56 UTC, tamlyn10 commented
Meeting booked for Friday 14th May morning

2021-06-03 10:34 UTC, EVODelavega commented on protocol/0000-on-chain-treasury-trading.md
> +1. good behaviour - never used or "donated to" insurance pool
Using the insurance pool is bad behaviour? What about loss socialisation? It's not the fault of the trader that their MTM win had to come from the insurance pool, but rather the fact that the traders holding an opposite position couldn't cover the MTM loss

2021-06-03 10:37 UTC, jeremyletang commented on protocol/0000-on-chain-treasury-trading.md
> +1. good behaviour - never used or "donated to" insurance pool
Well I think that meant used the insurance pool from the side of the party in fault, in order to pay the good behaving party darling.

2021-06-03 11:40 UTC, ValentinTrinque commented on protocol/0000-rewards.md
> +## Rewards
Discussed during spec review:

Rename Reward to Reward Scheme here, to dedicate the term Reward to the result of the Reward Function.

2021-06-28 13:56 UTC, edd requested changes

2021-06-28 13:56 UTC, edd commented on protocol/0000-reward-functions.md
> +- [ ] the reward pot is empty at the conclusion of the reward distribution
If we are running both 5.1 and 5.2, they both empty the 'pot' (for clarity: a pot is a single treasury account for each asset)(see above comment about the definition of a pot that may solve this)

2021-06-28 13:56 UTC, edd commented on protocol/0000-on-chain-treasury.md
> +The funds in the network treasury are spent either by direct governance action (transfer) or by mechanisms controlled by governance, such as a periodic transfer into a reward pot.
We need a concise, reasonable definition of a 'pot'. From reading the initial two lines here, a pot is a single reward account on each asset. However looking at 5.1 and 5.2, it suggests that each reward empties the pot - which would mean that those two cannot run simultaneously, which doesn't seem right?

2021-06-28 14:01 UTC, edd commented on protocol/0000-on-chain-treasury.md
> +The funds in the network treasury are spent either by direct governance action (transfer) or by mechanisms controlled by governance, such as a periodic transfer into a reward pot.
If it's the same as a reward pool below, the language needs to be standardised

2021-06-28 14:02 UTC, edd commented on protocol/0000-rewards-overview.md
> +Rewards are deployed using the Reward Functions. Individual Reward Pools are automatically created when an asset is transferred to the Reward.
There is one treasury account per asset. Is this also specifying that each reward will have an account asset?

2021-07-02 10:15 UTC, tamlyn10 commented on protocol/0000-reward-functions.md
> +- [ ] the reward pot is empty at the conclusion of the reward distribution
My understanding was there would be 1 x pot per reward scheme which is different to the top level treasury account which is 1 per asset.

2021-07-02 10:22 UTC, tamlyn10 commented on protocol/0000-rewards-overview.md
> +Rewards are deployed using the Reward Functions. Individual Reward Pools are automatically created when an asset is transferred to the Reward.
@edd could you take a look at the figure I've included with this PR and see if you agree with what I've mapped out in terms of 1 account per reward? If so, I can add more clarity about that reward account like when it gets created, deleted etc.

2021-07-08 11:25 UTC, barnabee commented
Merging post review with @davidsiska-vega @edd

2021-07-08 11:25 UTC, merged