API Node Spec
vegaprotocol/specs pull request #535
Opened 2021-05-07 13:49 UTC by peterbarrow

This new spec covers the changes we want to make in taking the API functionality out of the core node and implementing it in a stand alone executable in a new repository. We split the work into 2 stages, one to move the current functionality across and a second to improve and add more features to the API node.

2021-05-07 14:19 UTC, cityhunteur commented on non-protocol-specs/0003-api-node.md
> +An API node is a stand alone executable that connects to the eventbus stream of a stream node (also called a non-validator node). It constructs any data objects from the incoming data required to pro
> The API node is started at the same time as the stream node so that all events can be captured

I think we need to clarify this one; I thought this was not a hard requirement; and the API nodes will source the events as they come online.

2021-05-07 15:30 UTC, peterbarrow commented on non-protocol-specs/0003-api-node.md
> +An API node is a stand alone executable that connects to the eventbus stream of a stream node (also called a non-validator node). It constructs any data objects from the incoming data required to pro
Updated, does that make more sense now?

2021-05-07 15:50 UTC, cityhunteur commented on non-protocol-specs/0003-api-node.md
> +An API node is a stand alone executable that connects to the eventbus stream of a stream node (also called a non-validator node). It constructs any data objects from the incoming data required to pro
It does 👍

2021-05-11 11:07 UTC, edd requested changes
Some clarification in the acceptance criteria for stage 1, I think. Otherwise it sounds good.

2021-05-11 11:07 UTC, edd commented on non-protocol-specs/0003-api-node.md
> +An API node is a read only service that connects to a stream node (non-validator node) and gives users the ability to query the state of the network.The user can request information from the API node
```suggestion
An API node is a read only service that connects to a stream node (non-validator node) and gives users the ability to query the state of the network. The user can request information from the API nodes using GraphQL, gRPC and REST. The user can query the API node for one off snapshots of data or request a subscription of live data.
```

2021-05-11 11:07 UTC, edd commented on non-protocol-specs/0003-api-node.md
> +* All information that is emitted from the stream node is processed by the API node (no data is lost)
**question (blocking)**: This sounds good, but I’d like some more detail on how error handling will work:

- If a stream node stops emitting events forever, what can we do? 
- ~If a stream node is still processing blocks but not emitting events to the DataNode (connectivity, I guess) does it buffer events for the DataNode? If so how long for?~ Answered in stage 2

I assume the answer for stage one is ‘You just stop getting events forever’, which is probably roughly equivalent to now, which is OK. But let’s make it explicit

2021-05-11 11:07 UTC, edd commented on non-protocol-specs/0003-api-node.md
> +### Stage 2 (for further discussion)
**question (non-blocking)**:  Will the DataNode need block-level information that the Event Bus doesn’t currently have?  Off the top of my head the first two clients for this DataNode would be a Block Explorer and the Console needing more historical data. The Block explorer probably wants to get block information (which is in Tendermint, but not coming via the event bus). Is that out of scope?

2021-05-11 11:13 UTC, edd commented on non-protocol-specs/0003-api-node.md
> +* No API related code must be left in the Core Node
**question (blocking)**: Can we define this more? We’ve split our nodes in to three:

- Validator nodes. **GRPC? (see below),** no REST, no GraphQL.
- Stream nodes: GRPC event bus only.
- DataNodes (the thing this spec is about): GRPC, REST, GraphQL

Can anyone subscribe to the stream node’s event bus? I assume yes, and I assume that it would be up to the node operator to restrict this if they wanted.

Also presumably validators need some way for people to submit TXs? Or are we poking TXs directly in to Tendermint now? If so, which node does this? If it’s not validators that might be confusing. Of course if it is validators it might be confusing too. Either way, clarification required.

2021-05-11 11:21 UTC, edd commented
I’ve left a review asking for clarity in a few places. A question that correctly *isn’t* addressed is when should this split out in to a separate repo from the core, given that [vegaprotocol/vega](https://github.com/vegaprotocol/vega) is currently a private repo and this code will be useful to other people. 

My votes is for that being a stage 2 requirement, as per this spec. The reason for that is that the code in the API layers isn’t going to be changed significantly in stage 1, while to adapt in the process of implementing stage 2 will require  more sweeping changes. Let’s use stage 1 to get familiar with the API code and decide what says and what will need to change, and then plan how that migrates over to a repo while planning stage 2 in more depth.

2021-05-11 11:23 UTC, jeremyletang commented on non-protocol-specs/0003-api-node.md
> +* No API related code must be left in the Core Node
Ultimately the validator and stream nodes are the same, they just have a difference in configuration which make them part of consensus or not, but they shall exposes same APis.

So now knowing they are the same thing here's the APIs they would make available:
- submit transaction (as it is now pretty much, with the SubmitTx call, no prepare exists anymore).
- some informational things (e.g: healthchecks, statistics)
- The event bus.

2021-05-11 11:27 UTC, jeremyletang commented
> I’ve left a review asking for clarity in a few places. A question that correctly _isn’t_ addressed is when should this split out in to a separate repo from the core, given that [vegaprotocol/vega](https://github.com/vegaprotocol/vega) is currently a private repo and this code will be useful to other people.

I think the intent of phase one, is to completely decorelate the core to the APIs, which  the goal is to get it out of the core repo once that is done and is the finally achievement of part 1, Part to is basically possible because the APIs do not exists in the core, and can be built without any constraints from it runing with the core.

Also I'd really approach part 1 with the deliverable being this needs to be fully in another repo, just so we can make clear that we have no more dependencies between core and APIs, and don't get any suprise, or any non expected behaviour later on, when we finally get it out, and realise there was issues in the design or anything, to me it should be worked out of the core from the beginning.

2021-05-11 11:30 UTC, edd commented on non-protocol-specs/0003-api-node.md
> +* No API related code must be left in the Core Node
It would be good to clarify these definitions at the top of the file then:

- A *validator node* only exposes the event bus and a submitTx endpoint. All REST, GraphQL and other GRPC endpoints will be removed in stage 1 of this spec.
- A *stream node* is functionally identical to a validator node, but does not participate in the consensus of the underlying blockchain. A stream node can still be used to submit transactions.
- A *data node* is a new node type that subscribes to the event bus of a validator or stream node, and provides the REST, GraphQL and GRPC endpoints that were formerly built in to the core.

2021-05-11 11:31 UTC, jeremyletang commented on non-protocol-specs/0003-api-node.md
> +* No API related code must be left in the Core Node
Yes, that sounds like a good addition to it.

2021-05-11 11:39 UTC, edd commented on non-protocol-specs/0003-api-node.md
> +* No API related code must be left in the Core Node
Also worth noting that it’s plausible that in future a validator node will get its own GRPC commands that relate only to validator nodes. Which is fine as we are keeping the stream & submitTX endpoints in there directly, so it’s not like anyone is removing it entirely. I’m just being pedantic about the acceptance criteria that ‘No API related code…’ is in here. I guess the AC should be more like:

- The gateway code (GraphQL &  REST) is no longer in the core binary (i.e. validators and stream nodes **cannot** serve REST & GraphQL)
- The current GRPC endpoints should be reduced to a minimal set. All other endpoints should no longer exist in the core binary. The only endpoints should be:
  - Health check
  - Event bus
  - SubmitTransaction

2021-05-12 10:47 UTC, peterbarrow commented on non-protocol-specs/0003-api-node.md
> +* All information that is emitted from the stream node is processed by the API node (no data is lost)
Good thoughts. We will be able to tell that the streaming node has stopped sending us events as we expect a block time update every second or so. We can monitor that and shutdown with an error if we don't see the events for a given period of time.

2021-05-12 10:49 UTC, peterbarrow commented on non-protocol-specs/0003-api-node.md
> +### Stage 2 (for further discussion)
I would say tendermint specific events are not part of this scope. We can look in stage 2 about the best way to do this.

2021-05-26 15:10 UTC, jeremyletang commented
@vegaprotocol/core to review so it can be merged soon.

2021-07-07 10:02 UTC, edd approved these changes

2021-07-07 10:02 UTC, merged