Add freeform governance proposals to the governance spec
vegaprotocol/specs pull request #690
Opened 2021-09-15 11:00 UTC by davidsiska-vega

2021-09-16 14:12 UTC, edd requested changes
One question that needs an answer, otherwise this looks fine.

2021-09-16 14:12 UTC, edd commented on protocol/0028-governance.md
> +## 6. Freeform governance proposal
**Question (blocking)** Is there any requirement for the network to verify the hash of the text file?

My assumption is no, but this should be explicit.

2021-09-21 16:25 UTC, edd commented on protocol/0028-governance.md
> +
Can we specify a max length for the proposal text fields?

2021-09-21 16:38 UTC, davidsiska-vega commented on protocol/0028-governance.md
> +
Made it 255 characters, feel free to change.

2021-09-21 16:39 UTC, davidsiska-vega commented on protocol/0028-governance.md
> +## 6. Freeform governance proposal
You are correct and I've made the text explicit.

2021-09-21 18:30 UTC, edd approved these changes

2021-09-21 18:30 UTC, merged