Draft Key-Risk-and-management
vegaprotocol/specs pull request #721
Opened 2021-10-15 11:47 UTC by Vegaklaus

Vega related keys, their risks, and their management

2021-11-03 19:26 UTC, davidsiska-vega requested changes
I think this should be split into two documents. First one should be readme-keys.md and it should go directly into the https://github.com/vegaprotocol/networks repo.  

It should strictly document the current behaviour (none of the "we may implement" but it can link to the one below saying this is in the works). 

The second document should be a spec for the tendermint key certificate signing stuff and that should stay in the specs repo. 

What do you think?

Also, could you please define `n` and `t` somewhere before they're first used? Thx!

2021-11-11 11:35 UTC, jeremyletang commented on protocol/0000-002KeyManagement.md
> +gets lost, the the Vegsa tokens become unmovable. If they have previously been associated to a Vega key
```suggestion
gets lost, the Vegas tokens become unmovable. If they have previously been associated to a Vega key 
```

2021-11-11 11:48 UTC, jeremyletang approved these changes

2021-11-11 11:48 UTC, jeremyletang commented on protocol/0000-002KeyManagement.md
> +not just the one switching the key.(*)
Well not really, we assume that the validator willing to change it's key would pay the gas cost right? To remove / add a key a single transaction is required (2 actually, one for each action).

2021-11-11 11:48 UTC, jeremyletang commented on protocol/0000-002KeyManagement.md
> +and only used to sign the update transaction.
That is true now, nut once we have snapshots fully working we expect the following flow though:
- validator submit transaction to rotate key
- transaction is accepted and key will be rotated at block N
- validator shutdown node
- validator load new keey
- validator restart, and key is in use from block N

2021-11-11 11:48 UTC, jeremyletang commented on protocol/0000-002KeyManagement.md
> +Compromise of this key is only critical if a significant number of keys are compromised (i.e., 2/3); in this case, it is possible to authorize non-existing events on the Vega chain.
If we are speaking of the ethereum-event-forwarder, the key is really used only between a node and it's eef. But that being compromised, it would lead to the node eeventually emitting wrong event in the vega network.

Also it's probably worth noting that we wish to re-implement the eef as part of the core node, so this key will node be needed anymore.

2021-11-11 11:48 UTC, jeremyletang commented on protocol/0000-002KeyManagement.md
> +The Tenderint key is the only performance critical signing key in the Vega system. This is
```suggestion
The Tendermint key is the only performance critical signing key in the Vega system. This is
```

2021-11-11 11:48 UTC, jeremyletang commented on protocol/0000-002KeyManagement.md
> +As the certitifacion key is 'hot', i.e., needs to be reachable at any time, we also
```suggestion
As the certification key is 'hot', i.e., needs to be reachable at any time, we also
```

2021-11-12 18:47 UTC, Vegaklaus commented on protocol/0000-002KeyManagement.md
> +not just the one switching the key.(*)
If I understood Danny right, then all other validators need to remove you, and then add you again. Are these instead single transactions for which I can collect the signatures out of band ?

2021-11-19 10:00 UTC, merged