Update 0010-margin-orchestration.md
vegaprotocol/specs pull request #754
Opened 2021-11-23 22:33 UTC by Jiajia-Cui

updated the information when margin is recalculated

2021-12-01 13:08 UTC, davidsiska-vega requested changes
Please look at my comments and perhaps edit.

2021-12-01 13:08 UTC, davidsiska-vega commented on protocol/0010-margin-orchestration.md
> +1. After a new trade
Should this be mark price change?

2021-12-01 13:08 UTC, davidsiska-vega commented on protocol/0010-margin-orchestration.md
> -1. When market observable used in the [margin calculation](./0019-margin-calculator.md) changes
This one should still be there (for the future, for our only product now it doesn't matter).

2021-12-01 13:08 UTC, davidsiska-vega commented on protocol/0010-margin-orchestration.md
> +2. upon leaving an auction
I think leaving an auction updates the mark price so that would be covered by "mark price change".

2021-12-01 13:20 UTC, Jiajia-Cui commented on protocol/0010-margin-orchestration.md
> +1. After a new trade
No, it should be "after a new trade" because the new mark price can be the same as the old mark price, and margin for all will still be recalculated.

2021-12-01 13:21 UTC, Jiajia-Cui commented on protocol/0010-margin-orchestration.md
> -1. When market observable used in the [margin calculation](./0019-margin-calculator.md) changes
yes, makes sense

2021-12-01 13:22 UTC, Jiajia-Cui commented on protocol/0010-margin-orchestration.md
> +2. upon leaving an auction
Is the default mark price is "0" during an auction?

2022-01-05 12:36 UTC, witgaw commented on protocol/0010-margin-orchestration.md
> +1. After a new trade
New trade could still have the same price as the previous, "if the mark price changes" sounds correct to me.

2022-01-05 12:37 UTC, witgaw commented on protocol/0010-margin-orchestration.md
> +2. upon leaving an auction
Mark price is undetermined during opening auction and it's just the last mark price prior to going into the auction for other auction types.

2022-01-06 08:22 UTC, witgaw approved these changes
LGTM

2022-01-06 08:22 UTC, merged