First draft  of the 3-oregon-trail.md feature list
vegaprotocol/specs pull request #772
Opened 2022-01-04 21:05 UTC by gordsport

Closes #633 .

A first draft of the OT features to elicit feedback on the features and the priority order (core items taken from https://miro.com/app/board/o9J_lkFBHSw=/ Miro 2022 OKR planning

2022-01-04 21:07 UTC, gordsport commented
Created a first draft to review in the protocol design meeting 5th Jan 2022. 

@campbellssource - I have not yet gone through the OKR planning and looked for key Front End items we want to include for OT

2022-01-07 09:07 UTC, edd commented on milestones/3-oregon-trail.md
> +| **TBC** | Internalize the wallet | ?? - needs to have the core open source first: To simplify the deployment of vega and minimize the interaction with external softwares | [Issue](https://github.co
@ValentinTrinque is this still valid?

2022-01-07 09:07 UTC, edd commented on milestones/3-oregon-trail.md
> +| **1** | Fractional order sizes  | We need to support more prevision | [Spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0052-fractional-orders-positions.md) | @davidsiska-v
Support more what’s @davidsiska-vega?

2022-01-07 09:08 UTC, edd commented on milestones/3-oregon-trail.md
> +| **2** | 🤑 Incentivised data-node implementation | Because we want to incentivise other parties to run instances of the data node. Stretch because we need datanode-v2 first | [Project](https://githu
I think this should be a requirement, or the block explorer should be a stretch task - data node being reasonable is a requirement for a meaningful block explorer, as we have transaction indexing off. 

The olde block explorer works without either, but it’s pretty lame (I can say that, I made it)

2022-01-07 09:10 UTC, edd commented on milestones/3-oregon-trail.md
> +
Markets need to settle. Meaning: we need markets to halt properly. We don’t have time based oracles, so we either need those or we need the bot doing settlement, and we need to ensure markets suspend at the end. This might just be testing. I suspect it’s a little more.

2022-01-07 09:10 UTC, edd requested changes
See notes

2022-01-07 09:14 UTC, davidsiska-vega commented on milestones/3-oregon-trail.md
> +| **1** | Fractional order sizes  | We need to support more prevision | [Spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0052-fractional-orders-positions.md) | @davidsiska-v
I think it means "precision". But beyond that this is "support fractional volume on the book and order and position sizes". 

I personally think we can switch on trading without it because I can set up a 0.001BTCUSD market by correctly setting up the oracle if I think this is the size people want to trade. 

*But* @jeremyletang says that adding fractional orders any later would only make life more difficult hence it's there.

2022-01-07 09:16 UTC, davidsiska-vega commented on milestones/3-oregon-trail.md
> +
We also need the internal time oracle as per the spec (I think there is an issue for it @gordsport ) but I've not seen it tested.

2022-01-07 09:16 UTC, gordsport commented on milestones/3-oregon-trail.md
> +
We have a development task for 🤠 https://github.com/vegaprotocol/vega/issues/4478 that accounts for time based oracles. Happy to include in this document too along with settlement at expiry testing.

2022-01-12 11:15 UTC, gordsport commented on milestones/3-oregon-trail.md
> +| **2** | 🤑 Incentivised data-node implementation | Because we want to incentivise other parties to run instances of the data node. Stretch because we need datanode-v2 first | [Project](https://githu
Spike ticket on core to investigate APIs, incentives to come later

2022-01-12 11:19 UTC, gordsport reviewed
comments addressed

2022-01-12 11:19 UTC, gordsport commented on milestones/3-oregon-trail.md
> +| **1** | Fractional order sizes  | We need to support more prevision | [Spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0052-fractional-orders-positions.md) | @davidsiska-v
```suggestion
| **1** | Fractional order sizes  | We need to support more precision | [Spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0052-fractional-orders-positions.md) | @davidsiska-vega | Core</br>Front-End |
```

2022-01-12 11:20 UTC, merged