Floating-point consensus acceptance criteria
vegaprotocol/specs pull request #778
Opened 2022-01-10 14:57 UTC by witgaw

Added acceptance criteria + clarification on which events trigger which (re-)calculations.

Closes https://github.com/vegaprotocol/specs-internal/issues/765

2022-01-12 11:18 UTC, davidsiska-vega requested changes
I think we should expand all the individual acceptance criteria into stories of a few more steps so that QA can use them to create their tests. 

Happy to help flesh those out on a call @witgaw (at the moment I am a bit hazy on all the details).

2022-01-12 11:18 UTC, davidsiska-vega commented on protocol/0065-floating-point-consensus.md
> +- Default price monitoring bounds are 10% up and 10% down.
I think all the defaults should be phrased under one topic as one story that the QA can then test. So something like 
1) a market is proposed, 
2) verify that a fresh market is initialised with the correct defaults (list them)
3) verify that the defaults get updated with the calculated values.

2022-01-12 11:18 UTC, davidsiska-vega commented on protocol/0065-floating-point-consensus.md
> +- Market enactment triggers state variable recalculation (verify that default values are no longer used).
Could we have this as another topic / story for QA?

2022-01-19 11:54 UTC, edd commented
~I'm going to deal with the merge conflict after merging #799~

Edit: Done

2022-01-26 09:55 UTC, witgaw commented on protocol/0065-floating-point-consensus.md
> +- Default price monitoring bounds are 10% up and 10% down.
Added the scenarios sketches now.

2022-01-26 09:55 UTC, witgaw commented on protocol/0065-floating-point-consensus.md
> +- Market enactment triggers state variable recalculation (verify that default values are no longer used).
Added the scenarios sketches now.

2022-01-26 09:57 UTC, davidsiska-vega submitted a review, later dismissed
👍

2022-01-26 10:06 UTC, merged