Add acceptance criteria for limits
vegaprotocol/specs pull request #833
Opened 2022-02-02 14:55 UTC by edd

Added Acceptance Criteria for how the testnet limits work

- Added 10 ACs
  - 2 relate to the core functionality (this feature intentionally put most of the work on to the smart contract) - they control when Assets and Markets can be created
  - 8 relate to smart contract functionality, which is already built

Slightly weird edge cases: this is the first 'non protocol' spec that we have deemed requires testing. I wrestled with moving it in to the protocol, and keeping it out of the protocol. I went with the latter. It means that the AC codes in *this* file are actually codes from *another* file, which is weird. But it does mean that the coverage metrics can track this, which is the goal for now, so that's why I went with this. 
 
Closes #831

2022-02-04 17:10 UTC, edd commented
This is no longer WIP. It's pretty uncontroversial. @cpuja84 could you check if you're happy with how I put Acceptance Criteria in a non protocol spec? It's a bit of a weird case - it's sort of the balance of "Should this just be a spec in core" and "should it stay in this other folder". I went with the latter option, but the two Core specific ACs fit nicely in to the existing Governance spec, and the smart contract tests are... well I don't know.

But see what you think

2022-02-08 11:49 UTC, cpuja84 commented
@edd - I'm happy with the approach you have taken with ACs and they look great.
For Smart Contract Acceptance Criteria, may I suggest the choice of following ACs so that we atleast are able to track them. What are your thoughts ?

0003-limits-smartcontracts-0005
0003-limits-0005
0003-LATW-smartcontracts-0005
0003-LATW-0005

2022-02-11 16:12 UTC, cpuja84 requested changes
Smart Contract tests are not numbered, rest everything looks good

2022-02-11 16:12 UTC, cpuja84 commented on protocol/0028-GOVE-governance.md
> +- [ ] New asset proposals cannot be created before [`governance.proposal.asset.createFrom`](../non-protocol-specs/0003-limits-aka-training-wheels.md) is in the past (<a name="0028-GOVE-025" href="#00
Can we fix the create form links in both places, its broken currently.

2022-02-11 16:38 UTC, edd commented on protocol/0028-GOVE-governance.md
> +- [ ] New asset proposals cannot be created before [`governance.proposal.asset.createFrom`](../non-protocol-specs/0003-limits-aka-training-wheels.md) is in the past (<a name="0028-GOVE-025" href="#00
Done

2022-02-11 16:39 UTC, edd commented
I've added Acceptance Criteria tags (0003-NP-LIMI-001 onwards) to the smart contract ACs. Thanks for taking the time to remind me what we had agreed.

2022-02-11 16:52 UTC, cpuja84 commented on protocol/0028-GOVE-governance.md
> +- [ ] New asset proposals cannot be created before [`governance.proposal.asset.createFrom`](../non-protocol-specs/0003-limits-aka-training-wheels.md) is in the past (<a name="0028-GOVE-025" href="#00
Link still returns 404

2022-02-11 16:58 UTC, cpuja84 approved these changes
All sorted, happy to approve and merge it

2022-02-11 16:58 UTC, merged