Add testable acceptance criteria to 0034-PROB
vegaprotocol/specs pull request #842
Opened 2022-02-07 09:52 UTC by Jiajia-Cui

The acceptance criteria we had before were impossible to test for. 

This PR takes a feature test from `vega`, moves it to `qa-scenarios` and makes it into the one and only acceptance criteria for this spec.

2022-02-07 12:11 UTC, witgaw commented on qa-scenarios/verify-complex-shape-order-sizes.feature
> +      | sell | 12000020 | 185    |
@Jiajia-Cui do you understand how we end up with volume of `185` at price `12000020`? Is see `17` from `party-lp-1` and `167` from `party3`, so not sure where the extra 1 is coming from.

2022-02-07 12:13 UTC, witgaw commented on qa-scenarios/verify-complex-shape-order-sizes.feature
> +      | sell | 12000020 | 185    |
ah fine, there's `1` from line 24 (`party2`)

2022-02-07 12:24 UTC, witgaw requested changes
I don't think this should be tested without price monitoring bounds. 

I'm also not able to make intuitive sense of the numbers, not sure why buy LP orders have higher volumes (compared to sells) even though there's more of them.and their are closer to mid. 

Would be nice to be able to observe that:
1. If there's more orders on one side their individual sizes are larger (probably need a big difference, like 2 as many buys vs sells).
2. The order sizes increase as the offset increases (larger offset steps might be needed)

2022-02-07 19:52 UTC, davidsiska-vega commented
> not sure why buy LP orders have higher volumes (compared to sells) even though there's more of them and they are are closer to mid.

I think it's because:
```
volume = ceiling(liquidity_obligation x liquidity-normalised-proportion / probability_of_trading / price)
```
So (all other things being equal) sell side -> higher price -> less volume (and rounding of course exacerbates this).

2022-02-09 11:40 UTC, davidsiska-vega submitted a review, later dismissed
Two small things.

2022-02-09 11:40 UTC, davidsiska-vega commented on qa-scenarios/verify-complex-shape-order-sizes.feature
> +      | party-lp-1 | ETH/DEC19 | sell | 17     | 12000014 | STATUS_ACTIVE |
Can we choose bigger offsets here so that we see the volume increasing as we go away from best bid / best ask?

2022-02-09 11:40 UTC, davidsiska-vega commented on protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
> +    "## Acceptance Criteria\n",
Can all of these have their own label so that this spec has more than one acceptance criteria.

2022-02-09 11:42 UTC, witgaw requested changes

2022-02-09 11:42 UTC, witgaw commented on qa-scenarios/verify-complex-shape-order-sizes.feature
> +Scenario:  Test LP Volume being pushed by limit of Probability of Trading (capped at 1e-8);
Capped -> floored I think. If you agree then please also correct that in comments below.

2022-02-09 11:42 UTC, witgaw commented on qa-scenarios/volume-near-price-mon-bounds-2.feature
> +# Test volume and margin when LP volume is pushed inside price monitoring bounds
I think this whole file can be deleted, seems like those scenarios have already been copied / covered above.

2022-02-09 11:42 UTC, witgaw commented on qa-scenarios/volume-near-price-mon-bounds.feature
> +# Test volume and margin when LP volume is pushed inside price monitoring bounds
I think this whole file can be deleted, seems like those scenarios have already been copied / covered above.

2022-02-09 11:42 UTC, witgaw commented on qa-scenarios/verify-complex-shape-order-sizes.feature
> +      | party-lp-1 | ETH/DEC19 | sell | 17     | 12000014 | STATUS_ACTIVE |
Did you try to modify prices or offsets to see volumes increase as orders go further away from the mid? That's the main reason for "probability of trading" really so would be good to know if that's not the case or it's difficult to observe that in sensible markets.

2022-02-09 16:00 UTC, witgaw requested changes
If you could just uncomment the remaining scenarios in `lp-measure-test.feature` and add acceptance criteria tags (e.g. see how it was done here: https://github.com/vegaprotocol/specs-internal/blob/7b7bc7a15c1f907787dec0b0ea13507fbb2fbfcc/qa-scenarios/0059-delegation.feature#L60 
that will be ready to go in I think.

2022-02-09 16:00 UTC, witgaw commented on protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
>     ]
"5. Probability of trading decreases away from the mid-price (<a name=\"0034-PROB-005\" href=\"#0034-PROB-005\">0034-PROB-005</a>).\n",
    "\n"

2022-02-09 16:15 UTC, witgaw requested changes

2022-02-09 16:15 UTC, witgaw commented on qa-scenarios/lp-measure-test.feature
> +Feature: Verify the order size is correctly cumulated (0034-PROB-001); Probability of trading decreases away from the mid-price (0034-PROB-005)
The description from here should probably go to line 13 (the scenario), this is the description of entire feature file, so probably something along the lines of "Tests confirming probability of trading acceptance criteria" or whatever else you think makes sense.

2022-02-09 16:20 UTC, Jiajia-Cui commented on protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
> +    "## Acceptance Criteria\n",
comments been addressed

2022-02-09 16:21 UTC, Jiajia-Cui commented on qa-scenarios/verify-complex-shape-order-sizes.feature
> +      | party-lp-1 | ETH/DEC19 | sell | 17     | 12000014 | STATUS_ACTIVE |
comments been addressed

2022-02-09 16:24 UTC, witgaw approved these changes
LGTM, thanks a lot for all the edits - sorry if I made it seem more tedious then necessary but I think it looks great now and we won't have to revisit it for a good while (if at all), so hopefully less work in the long run.

2022-02-09 16:28 UTC, merged