Add ‘parked’ to order status, dedupe some ACs
vegaprotocol/specs pull request #860
Opened 2022-02-10 11:18 UTC by edd

- Add (short) section on parked orders to Order Status spec 
- Move Acceptance Criteria to the bottom of the file, which is the more common place
- Deduplicate ACs that are the same as the ones in the matching engine spec
- Add percentages to the reference script

Closes #858

2022-02-10 23:53 UTC, cpuja84 requested changes
I have left couple of comments @edd. Rest all looks great.

2022-02-10 23:53 UTC, cpuja84 commented on protocol/0008-TRAD-trading_workflow.md
> +1. [ ] Before a valid order is processed in any other way by Vega, the [party](./0016-PART-party.md)'s [margin levels](./0011-MARA-check_order_allocate_margin.md) are checked as though they had the o
Please could the link to party spec be corrected to 0017-PART-party.md

2022-02-10 23:53 UTC, cpuja84 commented on protocol/0026-AUCT-auctions.md
> +- [] As a user, I can place an order when the market is in auction mode, but it will not trade immediately. (<a href="./0068-MATC-matching_engine.md#0068-MATC-020">0068-MATC-020</a>)
Imho, 0068-MATC-020 shouldn't even be an acceptance criteria as that's just the broad category. The actual testing criteria is 0068-MATC-021 or 0068-MATC-022 onwards where we talk about different order types and their behaviours. I'd rename it as an AC for this spec only. Happy to be convinced otherwise.

2022-02-11 10:01 UTC, edd commented on protocol/0026-AUCT-auctions.md
> +- [] As a user, I can place an order when the market is in auction mode, but it will not trade immediately. (<a href="./0068-MATC-matching_engine.md#0068-MATC-020">0068-MATC-020</a>)
Nope - I'm convinced. I'll fix that too

2022-02-11 10:38 UTC, edd commented on protocol/0026-AUCT-auctions.md
> +- [] As a user, I can place an order when the market is in auction mode, but it will not trade immediately. (<a href="./0068-MATC-matching_engine.md#0068-MATC-020">0068-MATC-020</a>)
Removed

2022-02-11 10:40 UTC, edd commented on protocol/0008-TRAD-trading_workflow.md
> +1. [ ] Before a valid order is processed in any other way by Vega, the [party](./0016-PART-party.md)'s [margin levels](./0011-MARA-check_order_allocate_margin.md) are checked as though they had the o
Thanks for catching that. 

I was using a text editor that I hadn't configured to 'autocomplete' markdown links to local files. I also added another `make` command that catches bad links (`make links`). But: did I run it? I did naaaht.

2022-02-11 10:43 UTC, edd commented
@cpuja84 I've addressed all your comments

2022-02-11 11:09 UTC, edd commented
Rebased after merging #847 :heavy_check_mark:

2022-02-11 11:39 UTC, cpuja84 commented on protocol/0026-AUCT-auctions.md
> +- [] As a user, I can place an order when the market is in auction mode, but it will not trade immediately. (<a href="./0068-MATC-matching_engine.md#0068-MATC-020">0068-MATC-020</a>)
I think there's a misunderstanding here, what I meant was the acceptance criteria about orders in auction mode will not be traded immediately on spec 0026-auctions is accurate but it's referencing to `0068-MATC-020` is inaccurate. So this criteria needs to be on this spec but needs new AC code and `0068-MATC-020` essentially needs to be removed from AC code and only the criteria could stay for context. Hope this makes sense.

2022-02-11 11:40 UTC, cpuja84 requested changes
Added a new comment about earlier feedback.

2022-02-11 11:58 UTC, edd commented on protocol/0026-AUCT-auctions.md
> +- [] As a user, I can place an order when the market is in auction mode, but it will not trade immediately. (<a href="./0068-MATC-matching_engine.md#0068-MATC-020">0068-MATC-020</a>)
I mostly understand, but I don't know how to get to what you want from where we are after my fix. Could you make the change?

2022-02-11 13:38 UTC, cpuja84 commented on protocol/0026-AUCT-auctions.md
> +- [] As a user, I can place an order when the market is in auction mode, but it will not trade immediately. (<a href="./0068-MATC-matching_engine.md#0068-MATC-020">0068-MATC-020</a>)
My apologies, I think it was my mistake that I missed seeing the your new changes. I checked again and it all looks in order.

2022-02-11 13:39 UTC, cpuja84 approved these changes
Looks good now !

2022-02-11 13:39 UTC, merged