Coded features review: LP fees & rewards #4811
vegaprotocol/specs pull request #925
Opened 2022-02-19 10:21 UTC by Jiajia-Cui

Reviewing the feature test in issue #4814 [https://github.com/vegaprotocol/vega/issues/4814]

Initialised  from original test and added 2 scenarios 0042-LP-Fees-004 and 0042-LP-Fees-005 to cover edge cases : https://github.com/vegaprotocol/specs-internal/blob/lp-fees-test/qa-scenarios/LP-Fees-Rewards-Test.feature with added Acceptance criteria number

Create an extra case to cover scenario 0042-LP-Fees-006 when distribution period is very large: https://github.com/vegaprotocol/specs-internal/blob/lp-fees-test/qa-scenarios/LP-Fees-Rewards-Large-Distribution-Time.feature

2022-02-22 07:44 UTC, witgaw requested changes
Looks really good overall, please see comments below before merging though.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/Debug-Featuretest-BondSlashing.json
> +{
This file shouldn't be committed.

2022-02-22 07:44 UTC, witgaw commented on protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
> +       "1. Pegged Price and Volume from LP commitment should carry the correct amount\n",
I think tags are needed (e.g. `(<a name=\"0034-PROB-001\" href=\"#0034-PROB-001\">0034-PROB-001</a>)`).

2022-02-22 07:44 UTC, witgaw commented on protocol/0034-PROB-prob_weighted_liquidity_measure.ipynb
> +    "3. More details please see features tests: integration/features/liquidity-provisin \n",
This is a bit circular, ACs are meant to define what behaviours are expected and tests need to confirm that it's the case (they can still do other things of course). 

Perhaps we could substitute it with some concrete ones like: probability decreases away from the best bid ask price for buy orders and from the best ask price for sell orders.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Large-Distribution-Time.feature
> +    Then debug transfers
Nitpick: if possible we should remove any debug statements before merging the tests.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Large-Distribution-Time.feature
> +    And the accumulated liquidity fees should be "35" for the market "ETH/MAR22"
I think it would be good to finish this off by moving time forward so that accumulated liquidity fees get paid out to lp1 (checking transfers and balances).

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Large-Distribution-Time.feature
> +Feature: Test liquidity provider reward distribution; Check what happens when distribution period is large(both in genesis and mid-market)
The "mid-market" bit never seems to be checked, but I'm not sure how important that is.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Test.feature
> +    # these are different from the tests, but again, we end up with a 2/3 vs 1/3 fee share here.
I think it's 0.8 vs 0.2 (as implied by equity-like share).

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Test.feature
> +    # these are different from the tests, but again, we end up with a 2/3 vs 1/3 fee share here.
Same as above.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Test.feature
> +    And the accumulated liquidity fees should be "20" for the market "ETH/MAR22"
I think it would be worth to verify the fee distribution.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/LP-Fees-Rewards-Test.feature
> +  Scenario: 2 LPs joining at start, unequal commitments, Check what happens when distribution period gets set to a larger value (0042-LP-Fees-005)
Unless I'm missing something this test doesn't seem to do what the description says.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/liquidity-provision-bond-account.feature
> +  And the insurance pool balance should be "8154" for the market "ETH/MAR22"
Might be worth reconciling this figure with the shortfall (check MTM transfers) to make sure that it's indeed 0.2 (penalty factor) of the shortfall amount.

2022-02-22 07:44 UTC, witgaw commented on qa-scenarios/bond-slashing.feature.mock
> -Feature: Test liquidity provider bond slashing
Is this still meant to be merged as a .mock?

2022-02-25 15:47 UTC, Jiajia-Cui commented on qa-scenarios/bond-slashing.feature.mock
> -Feature: Test liquidity provider bond slashing
no, it should be removed. :)

2022-02-25 15:48 UTC, Jiajia-Cui commented on qa-scenarios/LP-Fees-Rewards-Test.feature
> +  Scenario: 2 LPs joining at start, unequal commitments, Check what happens when distribution period gets set to a larger value (0042-LP-Fees-005)
updated the description

2022-02-25 15:51 UTC, Jiajia-Cui commented on qa-scenarios/liquidity-provision-bond-account.feature
> +  And the insurance pool balance should be "8154" for the market "ETH/MAR22"
I am still looking at this one, I think there might an issue, but Elias thinks that its not a defect, in this test case bond got penalised for having bond account empty and then for having margin and general account empty. Still doing some investigation at the moment. 

https://github.com/vegaprotocol/vega/issues/4627

2022-02-25 15:51 UTC, Jiajia-Cui commented on qa-scenarios/bond-slashing.feature.mock
> -Feature: Test liquidity provider bond slashing
and the feature test should replace the mock one

2022-03-02 16:27 UTC, Jiajia-Cui commented on qa-scenarios/liquidity-provision-bond-account.feature
> +  And the insurance pool balance should be "8154" for the market "ETH/MAR22"
It's a behaviour when LP provider added a new order, network tries to top up the margin account with the additional order, and then when margin account is below Margin Release level, the margin account stays. So not a defect.

2022-03-02 16:28 UTC, merged