Update 0062-SPAM-spam_protection.md
vegaprotocol/specs pull request #953
Opened 2022-03-03 13:35 UTC by Vegaklaus

Added spam detection for trading & acceptance criteria

2022-03-03 15:02 UTC, davidsiska-vega commented
There seems to be a section of duplicate text, is that the way it should be?

2022-03-03 15:03 UTC, davidsiska-vega commented on protocol/0062-SPAM-spam_protection.md
> +### Minimum Functionallity for Trading
Is this new functionality? Or this documenting / clarifying stuff that's already implemented?

2022-03-03 15:03 UTC, davidsiska-vega commented on protocol/0062-SPAM-spam_protection.md
> +### Note: We need to verify that the numbers make sense.
Verify with who? Or how?

2022-03-03 15:04 UTC, davidsiska-vega commented on protocol/0062-SPAM-spam_protection.md
> +- A spam attack using votes/governance proposals is detected and the votes transactions are rejected, i.e.,
Could you please add details with exact sequence of events / numbers so that QA can pick it up and get going?

2022-03-03 15:04 UTC, davidsiska-vega reviewed
Thanks for this Klaus, I've left a few comments.

2022-03-04 16:23 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +### Minimum Functionallity for Trading
This is new; the trading spam protection was stuck in a PR to discuss options, the goal of this is to make something that's implementable on the short term. As far as I know, we don't have anything on spam for trading related transactions at this point, only on governance spam.

2022-03-04 19:09 UTC, ValentinTrinque commented on protocol/0062-SPAM-spam_protection.md
> +  - Voting with less than 100 vega
Since parties with equity-like share can vote on a market update proposal, I think we should rework this criteria to accept equity-like share.

2022-03-04 19:53 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +  - Voting with less than 100 vega
That would mean the implementation is ahead of the spec and we need a spec update first. Options I see:
- market proposal/updates are different from governance and get their own rules
- the other assets are counted for all governance votes as well
- market proposals/updates are seen as other market transactions (as newly specified), which take into account assets (not related to that market, but overall).

My first instinct would be to do the first, and handle this similar to governance votes but with a different asset definition

2022-03-04 20:24 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +
There is a possibility that the spam protection will perform less than stellar during the training-wheels phase, as traders will all operate on limited assets and it's thus very affordable for an attacker to maintain 100 traders that have the maximum possible assets & revenue. 
Options is see:
- We accept this
- We put in an additional training wheels mechanism that implements a limit on trader per account if the network is congested

2022-03-07 08:09 UTC, davidsiska-vega commented on protocol/0062-SPAM-spam_protection.md
> +
I think Ethereum gas prices are our friend in this case.

2022-03-07 08:18 UTC, davidsiska-vega commented on protocol/0062-SPAM-spam_protection.md
> +  - Voting with less than 100 vega
Could you please write down exactly against which network parameters are these being compared and what values are you assuming these network parameters have? The system tests aren't always written with the "default" parameters (and anyway, there isn't default as mainnet can be changed and we also have fairground etc whey they can be different).

2022-03-07 11:48 UTC, jeremyletang commented on protocol/0062-SPAM-spam_protection.md
> +3. signature verification
This might actually not be true, if not mistaken we first check replay, then spam, then signature.

2022-03-07 11:51 UTC, jeremyletang commented on protocol/0062-SPAM-spam_protection.md
> +- If possible given the time, this value should change from zero to a governance parameter defining the threshold in a normalized unit.
We do not have ETH at all for now, only erc20 tokens. Maybe we should precise that we reject the transaction if the party do not have a balance for the settlement asset of the market it tries to submit an order for.

2022-03-07 11:52 UTC, jeremyletang commented on protocol/0062-SPAM-spam_protection.md
> +*Minimum: All assets and revenues are in ETH until we have added other bridges*
Still not in ETH but in ERC20 token.

2022-03-07 11:53 UTC, jeremyletang commented on protocol/0062-SPAM-spam_protection.md
> +*End-Goal: There is an internal way to determine relative asset values. Vega provides (similar to what Libra intended)
let's not speak about libra pleeeease. no traces of facebook should even touch our things.

2022-03-07 11:55 UTC, jeremyletang requested changes
As suggested by Valentin, the specs needs update to cover spam protection with UpdateMarket proposals.

2022-03-07 13:19 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +*End-Goal: There is an internal way to determine relative asset values. Vega provides (similar to what Libra intended)
How about 'A basket of currencies roughly representing their promotional assets on Vega ?

2022-03-07 13:19 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +*Minimum: All assets and revenues are in ETH until we have added other bridges*
So the settlement in the first trades is in ERC20 token and not ETH ?

2022-03-07 13:21 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +- If possible given the time, this value should change from zero to a governance parameter defining the threshold in a normalized unit.
This will only be needed once trading has started, does that still hold then ?

2022-03-07 13:22 UTC, ze97286 commented on protocol/0062-SPAM-spam_protection.md
> +3. signature verification
as for what we're _doing_, it's signature verification, then replay then spam.

2022-03-07 13:23 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +3. signature verification
So in the current implementation, someone could use spam to fill the replay protection buffer ?

2022-03-07 13:25 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +
Mostly, but there's gaps left - given medium resources, one can create a spam account that is indistinguishable (if looking at assets/revenue generated) from someone who is honestly trading intensively

2022-03-07 13:25 UTC, ze97286 commented on protocol/0062-SPAM-spam_protection.md
> +3. signature verification
how would they do that?

2022-03-07 13:26 UTC, Vegaklaus commented on protocol/0062-SPAM-spam_protection.md
> +
We might want a temporary rule along 'If 0% of accounts caused 90% of traffic, they're slowed down (if we have tendermint prioritie queues, they could be put on lower priority)

2022-04-13 10:15 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> +*Minimum: All assets and revenues are in ETH until we have added other bridges*
Can we move this to the draft spec for future spam protection

2022-04-13 10:15 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> +*End-Goal: There is an internal way to determine relative asset values. Vega provides (similar to what Libra intended)
Can we move this to the draft spec for future spam protection

2022-04-13 10:15 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> +
Can we move this to the draft spec for future spam protection

2022-04-13 10:16 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> +
Can we move this to the draft spec for future spam protection

2022-06-08 10:03 UTC, davidsiska-vega submitted a review, later dismissed

2022-06-22 10:19 UTC, gordsport commented
Closing as this is is covered in current specs 

Will refer back as also contains future spec details

2022-06-22 10:19 UTC, closed without merging