Create 0072-spam-protection-PoW
vegaprotocol/specs pull request #972
Opened 2022-03-08 15:58 UTC by Vegaklaus

First draft of PoW spam protection

2022-03-11 13:41 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +  The same identifyer has not been used for another transaction
that can only be for transactions that were included in blocks

2022-03-11 13:51 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +  The same identifyer has not been used for another transaction
or otherwise if send to the same node.

2022-03-11 13:53 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +  The same block has not been used for more than <spam_PoW_number_of_tx_per_block> transactions
that's not true if increase_difficulty is > 0

2022-03-11 13:55 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +If increasing difficulty is set to 1, then more trnasactions can be tired to one block by increasing the difficulty;
is increasing difficulty a boolean or an int, i.e. is it used to increase the difficulty by i or just to say that difficulty needs to be increased by 1 for each additional tx?

2022-03-11 13:57 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +Parameters: <spam_PoW_number_of_past_blocks>
are these parameters hard coded? if not how does the client (e.g. wallet) get them? query vega?

2022-03-12 16:19 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +  The same block has not been used for more than <spam_PoW_number_of_tx_per_block> transactions
but tbh I don't think the concept of increase difficulty is useful. I don't know if the order of transactions in deliverTx has anything to do with the time they were received so lets say spam_PoW_number_of_tx_per_block is 5 and someone sent 5 transactions to node 1 and then 2 transactions to node 2 with the minimum difficulty - and lets say all would be added to the block. When we check for spam in deliverTx we don't know which 2 transactions should be checked for increased difficulty so unless I'm missing the point here, I don't think we should bother.

2022-03-13 19:12 UTC, Vegaklaus commented on protocol/0000-spam-protection-PoW
> +Parameters: <spam_PoW_number_of_past_blocks>
Good point. I was assuming it can be changed, but that would require the wallet to be able to query some configuration information from the datan/nodes/validators (they already query block height, would that add a lot of effort) ?

2022-03-13 19:18 UTC, Vegaklaus commented on protocol/0000-spam-protection-PoW
> +  The same block has not been used for more than <spam_PoW_number_of_tx_per_block> transactions
We could check that if there's, say, 10 transaction linked to one block, at least 5 of them are with the increased difficulty.
The idea of this was to make it possible for heavy traders to compute more and thus trade more, rather than having a fixed number of transactions that are possible, thus avoiding a scenario where honest traders can't trade anymore.

2022-03-13 19:20 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +Parameters: <spam_PoW_number_of_past_blocks>
adding it to the height request would be cheap but also kind of an odd place to put it. putting it anywhere else would require the client to run two queries to vega just for a single transaction. So it's a choice between bad options.

2022-03-13 19:35 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +  The same block has not been used for more than <spam_PoW_number_of_tx_per_block> transactions
I don't know what the baseline difficulty is going to be, and what value spam_PoW_number_of_past_blocks would have, so I don't know realistically if they can prepare too many transactions for a block number that's going to go out of scope. More likely they'd prefer to have it in the next block than to invest in increasing difficulty, but I may be wrong. On the other hand I just don't see how we verify it correctly, in the sense that we're verifying one transaction at the time, what difficulty to we verify it with? in your example, the default for the first 5 and the +1 for each further transaction, and if they fail? btw, the spec also mentions banning them if they have too many transactions.

2022-03-13 19:41 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +Parameters: <spam_PoW_number_of_past_blocks>
but I think I can live with it, i.e. have network parameters on vega side for those and return their values in the blockheight/hash query.

2022-03-14 14:07 UTC, davidsiska-vega commented on protocol/0000-spam-protection-PoW
> +            <spam_PoW_increasing difficulty>
Can we clearly call these network parameters. 

Can we give valid ranges plus sensible defaults.

2022-03-14 14:24 UTC, davidsiska-vega commented on protocol/0000-spam-protection-PoW
> +Acceptance Criteria:
Can we label following the usual format.

2022-03-14 18:17 UTC, Vegaklaus commented on protocol/0000-spam-protection-PoW
> +The hash-function used is SHA3 <pending verification>. To allow for a more fine-grained control over the difficulty
This may change, as SHA-3 may be too close for hash functions with existing specialised mining rigs.

2022-03-16 10:43 UTC, emilbayes commented
I have generated test vectors that we can include and have a few details on the exact method of PoW that was implemented in Go. The exact method is as follows:

```
PoW = hash("Vega_SPAM_PoW" || Hex(H(b)) || Hex(tid) || BEU64(x))
```

Where the prefix `Vega_SPAM_PoW` is an ASCII byte string, `Hex(.)` is the hex encoding of the byte string in ASCII and `BEU64` is the Big Endian encoding as an unsigned 64-bit integer. `||` denotes concatenation. It may also be worth noting that the hash function SHA-3 with 24 rounds is SHA-3-256 proper per spec (which does 24 rounds of the keccak permutation), which I first interpreted as being 24 iterations of SHA-3. (granted this may change per @Vegaklaus comment). Surveying the most popular implementations Rust implementations (for web wallet), it is not possible to customise the rounds or bit-rate, which is worth considering. Another option for more fine-grained control over difficulty may be a popcount of the first N bits.

Example in Rust:

```rust
use tiny_keccak::{Hasher, Sha3};

// Test vector for difficulty >= 8
let mut sha3 = Sha3::v256();
let mut digest = [0u8; 32];

let nonce: u64 = 402;
sha3.update(b"Vega_SPAM_PoW");
sha3.update(b"ffb67ea4111d466d363a5c8f355bf81e2e3504563af273f5de81a005a6247e14"); // H(b)
sha3.update(b"c40de04280ce8c40ee41b5005c23a1358b4fbf31f6dcb675e8246b174458274e"); // tid
sha3.update(&nonce.to_be_bytes());
sha3.finalize(&mut digest); // 0053ea7687bd7652803af4300a7e17868267c32e4fb7f09375c46c367fd7646b
```

Test vectors:

```json
[
  {
    "difficulty": 4,
    "nonce": 0,
    "blockHash": "792ca202b84226c739f9923046a0f4e7b5ff9e6f1b5636d8e26a8e2c5dec70ac",
    "tid": "3b8399cdffee2686d75d1a96d22cd49cd11f62c93da20e72239895bfdaf4b772",
    "proof": "03f9f7d9911d3ca37c3356f10cd04273e788d1f57a9bc2396e7b5aa2e8d74557"
  },
  {
    "difficulty": 8,
    "nonce": 402,
    "blockHash": "ffb67ea4111d466d363a5c8f355bf81e2e3504563af273f5de81a005a6247e14",
    "tid": "c40de04280ce8c40ee41b5005c23a1358b4fbf31f6dcb675e8246b174458274e",
    "proof": "0053ea7687bd7652803af4300a7e17868267c32e4fb7f09375c46c367fd7646b"
  },
  {
    "difficulty": 12,
    "nonce": 2560,
    "blockHash": "d9ae00ce4c4fc96d8e72bb18f6990b833cc7724ad70322604c572f6e194d777f",
    "tid": "fcbbb4cc8dcd402a07af050bb809a04bd82f9c95b6e5a56768d3724a4abb09f0",
    "proof": "0008bbe071959bfe7fc426c4f378fcdb9540b3f931f4a0b09469f5bf0fddcb86"
  },
  {
    "difficulty": 16,
    "nonce": 23845,
    "blockHash": "dc4b61de2138856406acdabcc502be708bff7c945857ea032011a8b4b0cf54f4",
    "tid": "3954a15b2e1ec457ae100c56e2aa43786b4612644926403d59fd8cdcb29d825f",
    "proof": "00000fd8f55699845ac3192af013928916050eab088437943708b83b27490862"
  },
  {
    "difficulty": 20,
    "nonce": 85863,
    "blockHash": "8890702af457ddcda01fba579a126adcecae954781500acb546fef9c8087a239",
    "tid": "74030ee7dc931be9d9cc5f2c9d44ac174b4144b377ef07a7bb1781856921dd43",
    "proof": "000007542dcb39d1471fd6c7424a547b9039382e055ceed10c839f2b76f88c0d"
  }
]
```

2022-03-18 08:00 UTC, ze97286 commented on protocol/0000-spam-protection-PoW
> +            <spam_PoW_difficulty>                           = 20   <should correspond to ca. 15 seconds on a PC>
as discussed offline, this should be 17 at most.

2022-03-20 11:01 UTC, ze97286 submitted a review, later dismissed

2022-04-24 11:09 UTC, barnabee commented on protocol/0072-SPPW-spam-protection-PoW.md
> +- Depending on how things pan out, we may have an issue with the timing; to make sure traders have sufficient time to get the block height needs us to have a large parameter of `<PoW_number_of_past_b
I am not sure I understand this. What would we consider "a large parameter of `<PoW_number_of_past_blocks>`"?

It would seem reasonable that I can query a data node for the latest block and get a response in less than 1 block at say 1–1.5 second blocks, so it would seem unlikely that I am using a hash more than 5 blocks old? I could presumably query regularly or even listen to a stream of this data, in which case 5 blocks seems a wide buffer beyond worst case?

2022-04-25 09:29 UTC, davidsiska-vega requested changes
Apart from the specific comments (and one suggestion); this spec now talks about things that have been implemented and so should as much as possible unambiguously set out what things are. We should thus remove the "could do this", "might do that" bits as much as possible.

2022-04-25 09:29 UTC, davidsiska-vega commented on protocol/0072-SPPW-spam-protection-PoW.md
> +Parameters: `<spam_PoW_number_of_past_blocks>`                = 100  (range: 10-500)
Could we label these the same as core, now that this has been implemented?

2022-04-25 09:29 UTC, davidsiska-vega commented on protocol/0072-SPPW-spam-protection-PoW.md
> +
```suggestion
Vega does not charge fees on transactions. Fees are only charged on trades that execute. The main reason for not charging transaction fees on transactions like limit order submissions or governance votes is that this is an activity that should be encouraged (limit orders provide price information and liquidity, governance votes are essential for smooth running of the system). Because of this Vega has a novel client-side-proof-of-work mechanism to prevent transaction spam. 
```

2022-04-25 09:29 UTC, davidsiska-vega commented on protocol/0072-SPPW-spam-protection-PoW.md
> + this; however, they can be verified post-agreement, and the offending vega-key can be banished for 4 epochs.
Are we hard-coding 4 epochs here?

2022-04-25 09:29 UTC, davidsiska-vega commented on protocol/0072-SPPW-spam-protection-PoW.md
> +- In the original spam protection, we want to do anti-spam before verifying signatures; this order, however, cannot be done if the consequence of spam is banishment. Thus, here the order is:
"Original spam protection" will be meaningless for most people reading this. Can we have a link to the relevant spec please?

2022-04-25 10:02 UTC, gordsport commented on protocol/0072-SPPW-spam-protection-PoW.md
> +- In the original spam protection, we want to do anti-spam before verifying signatures; this order, however, cannot be done if the consequence of spam is banishment. Thus, here the order is:
added link: https://github.com/vegaprotocol/specs-internal/pull/972/commits/f0543b3a59f341ad9a45960b03a352b5c026585a

2022-04-25 10:25 UTC, Vegaklaus commented on protocol/0072-SPPW-spam-protection-PoW.md
> + this; however, they can be verified post-agreement, and the offending vega-key can be banished for 4 epochs.
We can also turn this into a network parameter

2022-04-25 10:28 UTC, Vegaklaus commented on protocol/0072-SPPW-spam-protection-PoW.md
> +- Depending on how things pan out, we may have an issue with the timing; to make sure traders have sufficient time to get the block height needs us to have a large parameter of `<PoW_number_of_past_b
There may be an unfortunate combination here (I'm talking to a data-node/validator that is slow, have slow software myself, etc; we'd have to see how this actually would pan out in practice

2022-04-25 10:55 UTC, gordsport commented on protocol/0072-SPPW-spam-protection-PoW.md
> +Parameters: `<spam_PoW_number_of_past_blocks>`                = 100  (range: 10-500)
Hey @Vegaklaus 

I have updated the parameters in the spec to align with the network parameter names:

SpamPoWNumberOfPastBlocks = `spam.pow.numberOfPastBlocks`
SpamPoWDifficulty = `spam.pow.difficulty`
SpamPoWHashFunction = `spam.pow.hashFunction`
SpamPoWNumberOfTxPerBlock = `spam.pow.numberOfTxPerBlock`
SpamPoWIncreasingDifficulty = `spam.pow.increaseDifficulty`

in this commit: https://github.com/vegaprotocol/specs-internal/pull/972/commits/dd65fa9e8bb37d1fe524e845bec8fc433497798c

Please can you review and let me know if these are OK? (if not I can revert) 
(cc @davidsiska-vega )

2022-04-25 11:02 UTC, davidsiska-vega commented on protocol/0072-SPPW-spam-protection-PoW.md
> +Parameters: `<spam_PoW_number_of_past_blocks>`                = 100  (range: 10-500)
That's awesome, thanks @gordsport .

2022-04-25 11:04 UTC, davidsiska-vega commented on protocol/0072-SPPW-spam-protection-PoW.md
> + this; however, they can be verified post-agreement, and the offending vega-key can be banished for 4 epochs.
@ze97286 says hard coded; let's keep it for now because we have other stuff hard-coded in places.

2022-04-25 11:05 UTC, gordsport commented on protocol/0072-SPPW-spam-protection-PoW.md
> + this; however, they can be verified post-agreement, and the offending vega-key can be banished for 4 epochs.
@ze97286 - is this banishment period (4 epochs) a network param?

2022-04-25 11:06 UTC, gordsport commented on protocol/0000-spam-protection-PoW
> +Acceptance Criteria:
ACs are now captured with the AC codes as per other specs

2022-04-25 14:04 UTC, davidsiska-vega approved these changes

2022-04-25 15:06 UTC, merged