Added acceptance criteria from the spec-development-document
vegaprotocol/specs pull request #974
Opened 2022-03-09 08:47 UTC by Vegaklaus

closes #905 .

2022-03-09 09:40 UTC, gordsport requested changes

2022-03-09 09:40 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> +### Acceptance Criteria
@edd Please can you advise @Vegaklaus  in the addition of the AC codes in here so we can ensure this is picked up when covered in tests.

2022-03-09 09:40 UTC, gordsport commented on protocol/0062-SPAM-spam_protection.md
> + Show conversation
Can the following be removed:
"This conversation was marked as resolved by Vegaklaus
 Show conversation"

2022-03-09 11:55 UTC, edd commented on protocol/0062-SPAM-spam_protection.md
> +### Acceptance Criteria
I’ll go ahead and do it, then explain the logic! It’s outline here: https://github.com/vegaprotocol/approbation. One day I’d like to make it automatic. Not today though.

2022-03-09 12:06 UTC, edd approved these changes
I assigned AC codes, ands removed the bit @gordsport wanted to be removed

2022-03-09 12:06 UTC, edd commented on protocol/0062-SPAM-spam_protection.md
> +### Acceptance Criteria
So! Every acceptances criteria that could be an individual, testable thing is assigned a code. The codes are generated in the fashion described above, and put in as self-linking-links so they’re easy to copy and paste. Job done!

There were one or two that made me think QA might say ‘This isn’t testable’. We’ll remove them when someone says that!

2022-03-16 11:08 UTC, gordsport approved these changes

2022-03-16 11:09 UTC, merged