Data sourcing acceptance criteria
vegaprotocol/specs pull request #979
Opened 2022-03-14 13:11 UTC by barnabee

Review, update, and add acceptance criteria for data sourcing

2022-03-15 08:18 UTC, gordsport requested changes
Few minor typos and added AC codes - I have not reviewed the content of the ACs that will need to be done by @davidsiska-vega / @vegaprotocol/qa

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. If a data source combines a primary source (like a signed message) with a filter (for instance saying we are only interested in messages where ticker = GBPUSD and timestamp = 20211231T23:59:00) th
```suggestion
1. If a data source combines a primary source (like a signed message) with a filter (for instance saying we are only interested in messages where ticker = GBPUSD and timestamp = 20211231T23:59:00) then the complete data source definition defines the source and can be used to accept/reject transactions, so for an active data source is active, transactions from the same provider (pubkey, Ethereum contract/event, URL, etc.) do not form part of the defined data source. If submitted, they should be rejected where possible and must not supply data to the target for the data source if the metadata or data content itself is not selected by the source definition (e.g. because ticker and timestamp do not match a filter). (<a name="0045-DSRC-001" href="#0045-DSRC-001">0045-DSRC-001</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. When no reference to a data source remains in any active part of the system (for instance a non-cancelled/settled market), data source no longer needs to be tracked and can be discarded. Any trans
```suggestion
1. When no reference to a data source remains in any active part of the system (for instance a non-cancelled/settled market), data source no longer needs to be tracked and can be discarded. Any transactions that would previously have matched and been selected by that data source would be rejected/ignored. (<a name="0045-DSRC-002" href="#0045-DSRC-002">0045-DSRC-002</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. If the same complete data source (provider and filters, etc.) is referenced in multiple places (e.g. two separate active markets) then it will remain acrtive if any subset of those references rema
```suggestion
1. If the same complete data source (provider and filters, etc.) is referenced in multiple places (e.g. two separate active markets) then it will remain acrtive if any subset of those references remain active. For example 2 markets reference the same data source (full definition must match exactly) and one of those markets is closed/cancelled/settled before the other, either because some other difference in their definition or because of governance action. (<a name="0045-DSRC-003" href="#0045-DSRC-003">0045-DSRC-003</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. If multiple data sources share common roots (e.g. the same provider - pubkey etc. but different filters) and at least one of those sources filters out a transaction but at least one other selects
```suggestion
1. If multiple data sources share common roots (e.g. the same provider - pubkey etc. but different filters) and at least one of those sources filters out a transaction but at least one other selects it (all filters match), the transaction data must still be supplied for the sources that match and must not be supplied for the sources that don't match. (<a name="0045-DSRC-004" href="#0045-DSRC-004">0045-DSRC-004</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. If multiple data sources share common roots (e.g. the same provider - pubkey etc. but different filters) and all of the sources select it (all filters match), the transaction data must be supplied
```suggestion
1. If multiple data sources share common roots (e.g. the same provider - pubkey etc. but different filters) and all of the sources select it (all filters match), the transaction data must be supplied for ALL of the sources that match. (<a name="0045-DSRC-005" href="#0045-DSRC-005">0045-DSRC-005</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. If a data source reference is changed (e.g. via governance vote), the old source must be dropped and data/transactions matching that source must not reach the target.
```suggestion
1. If a data source reference is changed (e.g. via governance vote), the old source must be dropped and data/transactions matching that source must not reach the target. (<a name="0045-DSRC-006" href="#0045-DSRC-006">0045-DSRC-006</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. If a data source reference is changed (e.g. via governance vote), the new source must become active and data/transactions matching that source must reach the target.
```suggestion
1. If a data source reference is changed (e.g. via governance vote), the new source must become active and data/transactions matching that source must reach the target. (<a name="0045-DSRC-007" href="#0045-DSRC-007">0045-DSRC-007</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Changes in data source references (e.g. via governance vote) must allow changing betweeen any valid data source definitions, including to a data source of a different type of data source.
```suggestion
1. Changes in data source references (e.g. via governance vote) must allow changing between any valid data source definitions, including to a data source of a different type of data source. (<a name="0045-DSRC-008" href="#0045-DSRC-008">0045-DSRC-008</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data is not applied retrospectively, i.e. if a previous historic data point or data transaction would have matched a newly created data source, it must not be identified and applied to the new dat
```suggestion
1. Data is not applied retrospectively, i.e. if a previous historic data point or data transaction would have matched a newly created data source, it must not be identified and applied to the new data source (and therefore need not be stored by the core), only active data and new events created after the activation of the data source would be considered for the source. (<a name="0045-DSRC-009" href="#0045-DSRC-009">0045-DSRC-009</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Two data sources with the same definition that are active at the same time must always select and receive exactly the same data, in the same order
```suggestion
1. Two data sources with the same definition that are active at the same time must always select and receive exactly the same data, in the same order. (<a name="0045-DSRC-010" href="#0045-DSRC-010">0045-DSRC-010</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever p
```suggestion
1. Rejection of data sources either before submission/sequencing as transactions or when/if data is filtered/rejected after being sequenced on chain (if this happens - it should be avoided wherever possible to prevent spam attacks and reduce network load) must be accompanied by a message detailing the rejection reason (e.g. the filter, selector, or type check that failed). (<a name="0045-DSRC-011" href="#0045-DSRC-011">0045-DSRC-011</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to query an API and see all active data sources
```suggestion
1. It's possible to query an API and see all active data sources. (<a name="0045-DSRC-012" href="#0045-DSRC-012">0045-DSRC-012</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to listen to events or view logs and see all rejections and data source processing
```suggestion
1. It's possible to listen to events or view logs and see all rejections and data source processing. (<a name="0045-DSRC-013" href="#0045-DSRC-013">0045-DSRC-013</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. It's possible to listen to events and see all data that is supplied across all data sources or for any specific source
```suggestion
1. It's possible to listen to events and see all data that is supplied across all data sources or for any specific source. (<a name="0045-DSRC-014" href="#0045-DSRC-014">0045-DSRC-014</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data node carries historic data of at least all valid data that was supplied for each data source
```suggestion
1. Data node carries historic data of at least all valid data that was supplied for each data source. (<a name="0045-DSRC-015" href="#0045-DSRC-015">0045-DSRC-015</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0045-DSRC-data_sourcing.md
> +1. Data sources can be composed/nested arbitrarily (as long as the definition is valid), for example selecting a field on filtered data that itself was sourced by selecting a field on a message sent
```suggestion
1. Data sources can be composed/nested arbitrarily (as long as the definition is valid), for example selecting a field on filtered data that itself was sourced by selecting a field on a message sent by a signed data source (for example this might be processing a complex object in the source data. (<a name="0045-DSRC-016" href="#0045-DSRC-016">0045-DSRC-016</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0046-DSRM-data_source_signed_message.md
> +1. Reject any SubmitData tx that is a duplicate (i.e. contains exactly the same data payload and is for the same data source), even if it is signed by a different signer (assuming the source has mult
```suggestion
1. Reject any SubmitData tx that is a duplicate (i.e. contains exactly the same data payload and is for the same data source), even if it is signed by a different signer (assuming the source has multiple configured signers) or was submitted by a different Vega key. (<a name="0046-DSRM-016" href="#0046-DSRM-016">0046-DSRM-016</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Create a filter for each type of source provider and ensure that only data matching the filter gets through
```suggestion
	1. Create a filter for each type of source provider and ensure that only data matching the filter gets through. (<a name="0047-DSRF-001" href="#0047-DSRF-001">0047-DSRF-001</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Create the same filter for multiple types of provider and ensure that with the same input data, the output is the same
```suggestion
	1. Create the same filter for multiple types of provider and ensure that with the same input data, the output is the same. (<a name="0047-DSRF-002" href="#0047-DSRF-002">0047-DSRF-002</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Create a filter with multiple (AND) conditions and ensure that data is only passed through if all conditions are met
```suggestion
	1. Create a filter with multiple (AND) conditions and ensure that data is only passed through if all conditions are met. (<a name="0047-DSRF-003" href="#0047-DSRF-003">0047-DSRF-003</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Create a filter using an "OR" subfilter (if implemented) and ensure that data is passed through if any of the OR condiitons are met
```suggestion
	1. Create a filter using an "OR" sub-filter (if implemented) and ensure that data is passed through if any of the OR conditions are met. (<a name="0047-DSRF-004" href="#0047-DSRF-004">0047-DSRF-004</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. No data source event is emitted for a data source if the triggering event (SubmitData transaction, internal source, etc.) does not pass through the filter for that source
```suggestion
	1. No data source event is emitted for a data source if the triggering event (SubmitData transaction, internal source, etc.) does not pass through the filter for that source. (<a name="0047-DSRF-005" href="#0047-DSRF-005">0047-DSRF-005</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. No product/market processings is triggered by a data source when the event does not pass through the filters
```suggestion
	1. No product/market processings is triggered by a data source when the event does not pass through the filters. (<a name="0047-DSRF-006" href="#0047-DSRF-006">0047-DSRF-006</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. When data is filtered out and no event is emitted this is recorded either in logs or on the event bus (this may only happen on the receiving node if the event is a transaction that is rejected pr
```suggestion
	1. When data is filtered out and no event is emitted this is recorded either in logs or on the event bus (this may only happen on the receiving node if the event is a transaction that is rejected prior to being sequenced in a block). (<a name="0047-DSRF-007" href="#0047-DSRF-007">0047-DSRF-007</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters then data filt
```suggestion
	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters then data filtered out by one source can still be received by another, and vice versa. (<a name="0047-DSRF-008" href="#0047-DSRF-008">0047-DSRF-008</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other prope
```suggestion
	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other properties (i.e. they are not exactly the same definition) then any data that passes through and is emitted by both data sources results in a separate event/emission for each that references the appropriate source in each case. (<a name="0047-DSRF-009" href="#0047-DSRF-009">0047-DSRF-009</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other prope
```suggestion
	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other properties (i.e. they are not exactly the same definition) then any data that is filtered out by both data sources results in a separate log/event for each that references the appropriate source in each case. (<a name="0047-DSRF-010" href="#0047-DSRF-010">0047-DSRF-010</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other prope
```suggestion
	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other properties (i.e. they are not exactly the same definition) and the data is filtered out by one and emitted/passes through the other, then both the filtering out and the emission of the data are recorded in logs/events that reference the appropriate source. (<a name="0047-DSRF-011" href="#0047-DSRF-011">0047-DSRF-011</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other prope
```suggestion
	1. If two data sources originate from the same data point (transaction, event, etc.) and provider (SignedMessage signer group, internal market/object, etc.) but have different filters or other properties (i.e. they are not exactly the same definition) and the data is filtered out by one and emitted/passes through the other, then both the filtering out and the emission of the data are recorded in logs/events that reference the appropriate source. (<a name="0047-DSRF-011" href="#0047-DSRF-011">0047-DSRF-011</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Text fields can be filtered by equality (text matches filter data exactly)
```suggestion
	1. Text fields can be filtered by equality (text matches filter data exactly). (<a name="0047-DSRF-012" href="#0047-DSRF-012">0047-DSRF-012</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Number fields can be filtered by equality (number matches filter data exactly)
```suggestion
	1. Number fields can be filtered by equality (number matches filter data exactly). (<a name="0047-DSRF-013" href="#0047-DSRF-013">0047-DSRF-013</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Date + time fields can be filtered by equality (datetime matches filter data exactly)
```suggestion
	1. Date + time fields can be filtered by equality (datetime matches filter data exactly). (<a name="0047-DSRF-014" href="#0047-DSRF-014">0047-DSRF-014</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Number fields can be filtered by less than (number is less than filter data)
```suggestion
	1. Number fields can be filtered by less than (number is less than filter data). (<a name="0047-DSRF-015" href="#0047-DSRF-015">0047-DSRF-015</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Date + time fields can be filtered by less than (datetime is less than filter data))
```suggestion
	1. Date + time fields can be filtered by less than (datetime is less than filter data). (<a name="0047-DSRF-016" href="#0047-DSRF-016">0047-DSRF-016</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Number fields can be filtered by less than (number is less than or equal to filter data)
```suggestion
	1. Number fields can be filtered by less than or equal (number is less than or equal to filter data). (<a name="0047-DSRF-017" href="#0047-DSRF-017">0047-DSRF-017</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Date + time fields can be filtered by less than (datetime is less than or equal to filter data))
```suggestion
	1. Date + time fields can be filtered by less than or equal (datetime is less than or equal to filter data). (<a name="0047-DSRF-018" href="#0047-DSRF-018">0047-DSRF-018</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Number fields can be filtered by greater than (number is greater than filter data)
```suggestion
	1. Number fields can be filtered by greater than (number is greater than filter data). (<a name="0047-DSRF-019" href="#0047-DSRF-019">0047-DSRF-019</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Date + time fields can be filtered by greater than (datetime is greater than filter data))
```suggestion
	1. Date + time fields can be filtered by greater than (datetime is greater than filter data). (<a name="0047-DSRF-020" href="#0047-DSRF-020">0047-DSRF-020</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Number fields can be filtered by greater than (number is greater than or equal to filter data)
```suggestion
	1. Number fields can be filtered by greater than or equal (number is greater than or equal to filter data). (<a name="0047-DSRF-021" href="#0047-DSRF-021">0047-DSRF-021</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0047-DSRF-data_source_filter.md
> +	1. Date + time fields can be filtered by greater than (datetime is greater than or equal to filter data))
```suggestion
	1. Date + time fields can be filtered by greater than or equal (datetime is greater than or equal to filter data). (<a name="0047-DSRF-022" href="#0047-DSRF-022">0047-DSRF-022</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market that is already in Trading Terminated state so that the settlement data source is a Value source. The market settles immediately with the value provided as th
```suggestion
	1. Change a cash settled futures market that is already in Trading Terminated state so that the settlement data source is a Value source. The market settles immediately with the value provided as the settlement data. (<a name="0048-DSRI-001" href="#0048-DSRI-001">0048-DSRI-001</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market's trading terminatred trigger source to a blank Value data source (or one with any value, to be discarded) and ensure the market state changes
```suggestion
	1. Change a cash settled futures market's trading terminated trigger source to a blank Value data source (or one with any value, to be discarded) and ensure the market state changes. (<a name="0048-DSRI-002" href="#0048-DSRI-002">0048-DSRI-002</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Create a cash settled futures market with a time triggered value data source for the settlement data. Trigger trading terminated before the time speicifed in the trigger for the settlement data s
```suggestion
	1. Create a cash settled futures market with a time triggered value data source for the settlement data. Trigger trading terminated before the time specified in the trigger for the settlement data source. The market settles at the time specified in the trigger. (<a name="0048-DSRI-003" href="#0048-DSRI-003">0048-DSRI-003</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Create a cash settled futures market with a time triggered value data source  for the settlkement data. Trigger trading terminated after the time speicifed in the trigger for the settlement data
```suggestion
	1. Create a cash settled futures market with a time triggered value data source  for the settlement data. Trigger trading terminated after the time specified in the trigger for the settlement data source. The market settles immediately once trading terminated is triggered. (<a name="0048-DSRI-004" href="#0048-DSRI-004">0048-DSRI-004</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Create a cash settled futures market with the trading terminated trigger source beig a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
```suggestion
	1. Create a cash settled futures market with the trading terminated trigger source being a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being in the future. The market state changes to trading terminated at the time of the trigger.  (<a name="0048-DSRI-005" href="#0048-DSRI-005">0048-DSRI-005</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
```suggestion
	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being in the future. The market state changes to trading terminated at the time of the trigger. (<a name="0048-DSRI-006" href="#0048-DSRI-006">0048-DSRI-006</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being
```suggestion
	1. Change a cash settled futures market so the trading terminated trigger source becomes a time triggered blank Value data source (or one with any value, to be discarded) with the trigger time being in the past. The market state changes to trading terminated immediately. (<a name="0048-DSRI-007" href="#0048-DSRI-007">0048-DSRI-007</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market that is already in Trading Terminated state so that the settlement data source is a time triggered Value source with the trigger time in the past. The market
```suggestion
	1. Change a cash settled futures market that is already in Trading Terminated state so that the settlement data source is a time triggered Value source with the trigger time in the past. The market settles immediately with the value provided as the settlement data. (<a name="0048-DSRI-008" href="#0048-DSRI-008">0048-DSRI-008</a>)
```

2022-03-15 08:18 UTC, gordsport commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market that is already in Trading Terminated state so that the settlement data source is a time triggered Value source with the trigger time in the future. The marke
```suggestion
	1. Change a cash settled futures market that is already in Trading Terminated state so that the settlement data source is a time triggered Value source with the trigger time in the future. The market settles at the trigger time with the value provided as the settlement data. (<a name="0048-DSRI-009" href="#0048-DSRI-009">0048-DSRI-009</a>)
```

2022-03-15 15:50 UTC, davidsiska-vega commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Change a cash settled futures market's trading terminated trigger source to a blank Value data source (or one with any value, to be discarded) and ensure the market state changes. (<a name="0048-
@barnabee Can we be clear what the state change to? I suppose it should move to trading terminated mode but just checking to be 100% sure.

2022-03-15 15:53 UTC, davidsiska-vega commented on protocol/0048-DSRI-data_source_internal.md
> +	1. Create a cash settled futures market with a time triggered value data source for the settlement data. Trigger trading terminated before the time specified in the trigger for the settlement data s
@barnabee "Trigger trading terminated before the time specified in the trigger for the settlement data source" I don't follow this one, maybe you can re-phrase with more detail?

2022-03-15 15:54 UTC, davidsiska-vega requested changes
I don't know which of these are in scope for Oregon trail. At this stage this is important because that's where the testing effort should be focused. Could we label / highlight these somehow?

2022-03-16 11:45 UTC, davidsiska-vega commented
All for oregon trail.

2022-03-16 11:46 UTC, davidsiska-vega approved these changes

2022-03-16 11:46 UTC, gordsport approved these changes

2022-03-16 12:05 UTC, merged